delete from T_AUTHORITY;
insert into T_AUTHORITY (res_id, res_name, res_type, res_url, other_res, orders, pid, iconclass, script_text, update_ts, xtype)
values (606, '物流反馈', 2, 'order/wl.html', 'order/orderlist*', 6, 60, 'icon icon-search', null, to_date('06-09-2016', 'dd-mm-yyyy'), '0');
insert into T_AUTHORITY (res_id, res_name, res_type, res_url, other_res, orders, pid, iconclass, script_text, update_ts, xtype)
values (107, '资源管理', 2, 'system/auth/index.html', null, 7, 10, 'icon icon-circle', null, to_date('10-08-2016', 'dd-mm-yyyy'), '0');
insert into T_AUTHORITY (res_id, res_name, res_type, res_url, other_res, orders, pid, iconclass, script_text, update_ts, xtype)
values (506, '客户资金对账', 2, 'account/month.html', 'account/period/periodData', 6, 50, 'icon  icon-list-alt', null, to_date('10-08-2016', 'dd-mm-yyyy'), '0');
insert into T_AUTHORITY (res_id, res_name, res_type, res_url, other_res, orders, pid, iconclass, script_text, update_ts, xtype)
values (507, '客户合同返利', 2, 'account/custrebate.html', null, 7, 50, 'icon icon-file-alt', null, to_date('10-08-2016', 'dd-mm-yyyy'), '0');
insert into T_AUTHORITY (res_id, res_name, res_type, res_url, other_res, orders, pid, iconclass, script_text, update_ts, xtype)
values (60, '订单管理', 1, '#', null, 6, null, 'icon icon-shopping-cart', null, to_date('10-08-2016', 'dd-mm-yyyy'), '0');
insert into T_AUTHORITY (res_id, res_name, res_type, res_url, other_res, orders, pid, iconclass, script_text, update_ts, xtype)
values (601, '订单录入', 2, 'order/startOrder.html*', 'order/util/customer*,order/util/customerShip*,order/util/customerAccount*,order/util/custProduct*,order/addOrder*,order/util/validateNum*,order/orderAudit*', 1, 60, 'icon icon-plus-sign', null, to_date('10-08-2016', 'dd-mm-yyyy'), '0');
insert into T_AUTHORITY (res_id, res_name, res_type, res_url, other_res, orders, pid, iconclass, script_text, update_ts, xtype)
values (602, '订单查询', 2, 'order/index.html', null, 2, 60, 'icon icon-search', null, to_date('10-08-2016', 'dd-mm-yyyy'), '0');
insert into T_AUTHORITY (res_id, res_name, res_type, res_url, other_res, orders, pid, iconclass, script_text, update_ts, xtype)
values (70, '我的工作台', 1, '#', null, 7, null, 'icon  icon-desktop', null, to_date('10-08-2016', 'dd-mm-yyyy'), '0');
insert into T_AUTHORITY (res_id, res_name, res_type, res_url, other_res, orders, pid, iconclass, script_text, update_ts, xtype)
values (701, '我的申请', 2, 'process/myprocess.html', null, 1, 70, 'icon  icon-laptop', null, to_date('10-08-2016', 'dd-mm-yyyy'), '0');
insert into T_AUTHORITY (res_id, res_name, res_type, res_url, other_res, orders, pid, iconclass, script_text, update_ts, xtype)
values (702, '待处理', 2, 'process/forMe.html', null, 2, 70, 'icon icon-check', null, to_date('10-08-2016', 'dd-mm-yyyy'), '0');
insert into T_AUTHORITY (res_id, res_name, res_type, res_url, other_res, orders, pid, iconclass, script_text, update_ts, xtype)
values (80, '销售政策管理', 1, '#', null, 8, null, 'icon icon-book', null, to_date('10-08-2016', 'dd-mm-yyyy'), '0');
insert into T_AUTHORITY (res_id, res_name, res_type, res_url, other_res, orders, pid, iconclass, script_text, update_ts, xtype)
values (801, '销售政策管理', 2, 'salePolicy/index.html', null, 1, 80, 'icon icon-book', null, to_date('10-08-2016', 'dd-mm-yyyy'), '0');
insert into T_AUTHORITY (res_id, res_name, res_type, res_url, other_res, orders, pid, iconclass, script_text, update_ts, xtype)
values (802, '政策类型维护', 2, 'salepolicy/policyType/policytype.html', null, 2, 80, 'icon icon-book', null, to_date('10-08-2016', 'dd-mm-yyyy'), '0');
insert into T_AUTHORITY (res_id, res_name, res_type, res_url, other_res, orders, pid, iconclass, script_text, update_ts, xtype)
values (803, '政策人工核销', 2, '#', null, 3, 80, 'icon icon-book', null, to_date('10-08-2016', 'dd-mm-yyyy'), '0');
insert into T_AUTHORITY (res_id, res_name, res_type, res_url, other_res, orders, pid, iconclass, script_text, update_ts, xtype)
values (90, '费用管理', 1, '#', null, 9, null, 'icon icon-money', null, to_date('10-08-2016', 'dd-mm-yyyy'), '0');
insert into T_AUTHORITY (res_id, res_name, res_type, res_url, other_res, orders, pid, iconclass, script_text, update_ts, xtype)
values (901, '预算管理', 2, 'cost/index.html', null, 1, 90, 'icon  icon-indent-right', null, to_date('10-08-2016', 'dd-mm-yyyy'), '0');
insert into T_AUTHORITY (res_id, res_name, res_type, res_url, other_res, orders, pid, iconclass, script_text, update_ts, xtype)
values (902, '费用池管理', 2, 'cost/pool.html', null, 2, 90, 'icon icon-cloud', null, to_date('10-08-2016', 'dd-mm-yyyy'), '0');
insert into T_AUTHORITY (res_id, res_name, res_type, res_url, other_res, orders, pid, iconclass, script_text, update_ts, xtype)
values (903, '费用池调整', 2, 'cost/adjust/adjust.html', null, 3, 90, 'icon  icon-key', null, to_date('10-08-2016', 'dd-mm-yyyy'), '0');
insert into T_AUTHORITY (res_id, res_name, res_type, res_url, other_res, orders, pid, iconclass, script_text, update_ts, xtype)
values (904, '费用池统计', 2, 'cost/perid.html', null, 4, 90, 'icon icon-bar-chart', null, to_date('10-08-2016', 'dd-mm-yyyy'), '0');
insert into T_AUTHORITY (res_id, res_name, res_type, res_url, other_res, orders, pid, iconclass, script_text, update_ts, xtype)
values (100, '促销品管理', 1, '#', null, 10, null, 'icon icon-truck', null, to_date('10-08-2016', 'dd-mm-yyyy'), '0');
insert into T_AUTHORITY (res_id, res_name, res_type, res_url, other_res, orders, pid, iconclass, script_text, update_ts, xtype)
values (1001, '促销品物料管理', 2, 'promotion/promotionMaterial.html', null, 1, 100, 'icon  icon-bullhorn', null, to_date('10-08-2016', 'dd-mm-yyyy'), '0');
insert into T_AUTHORITY (res_id, res_name, res_type, res_url, other_res, orders, pid, iconclass, script_text, update_ts, xtype)
values (1002, '促销品库房管理', 2, 'promotion/promotionStores.html', null, 2, 100, 'icon icon-inbox', null, to_date('10-08-2016', 'dd-mm-yyyy'), '0');
insert into T_AUTHORITY (res_id, res_name, res_type, res_url, other_res, orders, pid, iconclass, script_text, update_ts, xtype)
values (1003, '促销品采购方维护', 2, 'promotion/promotionPUR.html', null, 3, 100, 'icon icon-truck', null, to_date('10-08-2016', 'dd-mm-yyyy'), '0');
insert into T_AUTHORITY (res_id, res_name, res_type, res_url, other_res, orders, pid, iconclass, script_text, update_ts, xtype)
values (1004, '促销品入库', 2, 'promotion/promotionIN.html', null, 4, 100, 'icon  icon-signin', null, to_date('10-08-2016', 'dd-mm-yyyy'), '0');
insert into T_AUTHORITY (res_id, res_name, res_type, res_url, other_res, orders, pid, iconclass, script_text, update_ts, xtype)
values (1005, '促销品出库', 2, 'promotion/promotionOUT.html', null, 5, 100, 'icon icon-upload-alt', null, to_date('10-08-2016', 'dd-mm-yyyy'), '0');
insert into T_AUTHORITY (res_id, res_name, res_type, res_url, other_res, orders, pid, iconclass, script_text, update_ts, xtype)
values (1006, '促销品查询', 2, 'promotion/promotionNum.html', null, 6, 100, 'icon  icon-certificate', null, to_date('10-08-2016', 'dd-mm-yyyy'), '0');
insert into T_AUTHORITY (res_id, res_name, res_type, res_url, other_res, orders, pid, iconclass, script_text, update_ts, xtype)
values (10, '系统管理', 1, '#', null, 1, null, 'icon  icon-cog', null, to_date('10-08-2016', 'dd-mm-yyyy'), '0');
insert into T_AUTHORITY (res_id, res_name, res_type, res_url, other_res, orders, pid, iconclass, script_text, update_ts, xtype)
values (101, '角色管理', 2, 'system/role/index.jhtml', null, 1, 10, 'icon icon-group', null, to_date('10-08-2016', 'dd-mm-yyyy'), '0');
insert into T_AUTHORITY (res_id, res_name, res_type, res_url, other_res, orders, pid, iconclass, script_text, update_ts, xtype)
values (205, '用户职位设定', 2, 'jobstation/jobset.html', 'Org/list', 5, 20, 'icon  icon-group', null, to_date('10-08-2016', 'dd-mm-yyyy'), '0');
insert into T_AUTHORITY (res_id, res_name, res_type, res_url, other_res, orders, pid, iconclass, script_text, update_ts, xtype)
values (301, '产品分类管理', 2, 'product/group.html', null, 1, 30, 'icon icon-hdd', null, to_date('10-08-2016', 'dd-mm-yyyy'), '0');
insert into T_AUTHORITY (res_id, res_name, res_type, res_url, other_res, orders, pid, iconclass, script_text, update_ts, xtype)
values (302, '产品信息管理', 2, 'product/product.html', null, 2, 30, 'icon icon-beer', null, to_date('10-08-2016', 'dd-mm-yyyy'), '0');
insert into T_AUTHORITY (res_id, res_name, res_type, res_url, other_res, orders, pid, iconclass, script_text, update_ts, xtype)
values (303, '工厂信息管理', 2, 'factory/factory.html', null, 3, 30, 'icon icon-columns', null, to_date('10-08-2016', 'dd-mm-yyyy'), '0');
insert into T_AUTHORITY (res_id, res_name, res_type, res_url, other_res, orders, pid, iconclass, script_text, update_ts, xtype)
values (40, '客户管理', 1, '#', null, 4, null, 'icon  icon-group', null, to_date('10-08-2016', 'dd-mm-yyyy'), '0');
insert into T_AUTHORITY (res_id, res_name, res_type, res_url, other_res, orders, pid, iconclass, script_text, update_ts, xtype)
values (50, '客户资金管理', 1, '#', null, 5, null, 'icon icon-credit-card', null, to_date('10-08-2016', 'dd-mm-yyyy'), '0');
insert into T_AUTHORITY (res_id, res_name, res_type, res_url, other_res, orders, pid, iconclass, script_text, update_ts, xtype)
values (501, '客户余额查询', 2, 'account/index.html', null, 1, 50, 'icon  icon-money', null, to_date('10-08-2016', 'dd-mm-yyyy'), '0');
insert into T_AUTHORITY (res_id, res_name, res_type, res_url, other_res, orders, pid, iconclass, script_text, update_ts, xtype)
values (102, '用户管理', 2, 'system/emp/index.html', null, 2, 10, 'icon icon-user', null, to_date('10-08-2016', 'dd-mm-yyyy'), '0');
insert into T_AUTHORITY (res_id, res_name, res_type, res_url, other_res, orders, pid, iconclass, script_text, update_ts, xtype)
values (103, '知识库管理', 2, 'knowledge/index.html', null, 3, 10, 'icon icon-hdd', null, to_date('10-08-2016', 'dd-mm-yyyy'), '0');
insert into T_AUTHORITY (res_id, res_name, res_type, res_url, other_res, orders, pid, iconclass, script_text, update_ts, xtype)
values (104, '公告管理', 2, 'system/notes/index.html', null, 4, 10, 'icon icon-bullhorn', null, to_date('10-08-2016', 'dd-mm-yyyy'), '0');
insert into T_AUTHORITY (res_id, res_name, res_type, res_url, other_res, orders, pid, iconclass, script_text, update_ts, xtype)
values (105, '字典管理', 2, 'system/dict/index.html', null, 5, 10, 'icon icon-book', null, to_date('10-08-2016', 'dd-mm-yyyy'), '0');
insert into T_AUTHORITY (res_id, res_name, res_type, res_url, other_res, orders, pid, iconclass, script_text, update_ts, xtype)
values (20, '组织管理', 1, '#', null, 2, null, 'icon icon-sitemap', null, to_date('10-08-2016', 'dd-mm-yyyy'), '0');
insert into T_AUTHORITY (res_id, res_name, res_type, res_url, other_res, orders, pid, iconclass, script_text, update_ts, xtype)
values (201, '组织架构管理', 2, 'Org/index.html', null, 1, 20, 'icon icon-th', null, to_date('10-08-2016', 'dd-mm-yyyy'), '0');
insert into T_AUTHORITY (res_id, res_name, res_type, res_url, other_res, orders, pid, iconclass, script_text, update_ts, xtype)
values (202, '销售区域设定', 2, 'Org/area.html', null, 2, 20, 'icon icon-globe', null, to_date('10-08-2016', 'dd-mm-yyyy'), '0');
insert into T_AUTHORITY (res_id, res_name, res_type, res_url, other_res, orders, pid, iconclass, script_text, update_ts, xtype)
values (203, '销售岗位管理', 2, 'Org/station.html', null, 3, 20, 'icon icon-user-md', null, to_date('10-08-2016', 'dd-mm-yyyy'), '0');
insert into T_AUTHORITY (res_id, res_name, res_type, res_url, other_res, orders, pid, iconclass, script_text, update_ts, xtype)
values (204, '组织职位管理', 2, 'jobstation/job.html', 'Org/list', 4, 20, 'icon icon-hospital', null, to_date('10-08-2016', 'dd-mm-yyyy'), '0');
insert into T_AUTHORITY (res_id, res_name, res_type, res_url, other_res, orders, pid, iconclass, script_text, update_ts, xtype)
values (30, '数据管理', 1, '#', null, 3, null, 'icon  icon-inbox', null, to_date('10-08-2016', 'dd-mm-yyyy'), '0');
insert into T_AUTHORITY (res_id, res_name, res_type, res_url, other_res, orders, pid, iconclass, script_text, update_ts, xtype)
values (502, '银行到款录入', 2, 'account/upaccount/upAccount.html', null, 2, 50, 'icon icon-hospital', null, to_date('10-08-2016', 'dd-mm-yyyy'), '0');
insert into T_AUTHORITY (res_id, res_name, res_type, res_url, other_res, orders, pid, iconclass, script_text, update_ts, xtype)
values (503, '资金确认', 2, 'account/upaccount/salesUpList.html', 'account/upaccount/accountcustomer*', 3, 50, 'icon icon-legal', null, to_date('10-08-2016', 'dd-mm-yyyy'), '0');
insert into T_AUTHORITY (res_id, res_name, res_type, res_url, other_res, orders, pid, iconclass, script_text, update_ts, xtype)
values (504, '资金上账', 2, 'account/upaccount/accountConfirm.html', null, 4, 50, 'icon  icon-upload', null, to_date('10-08-2016', 'dd-mm-yyyy'), '0');
insert into T_AUTHORITY (res_id, res_name, res_type, res_url, other_res, orders, pid, iconclass, script_text, update_ts, xtype)
values (505, '资金调整', 2, 'account/adjust/adjustList.html', null, 5, 50, 'icon icon-exchange', null, to_date('10-08-2016', 'dd-mm-yyyy'), '0');
insert into T_AUTHORITY (res_id, res_name, res_type, res_url, other_res, orders, pid, iconclass, script_text, update_ts, xtype)
values (402, '客户合同管理', 2, 'customer/page.html', null, 2, 40, 'icon  icon-file-alt', null, to_date('10-08-2016', 'dd-mm-yyyy'), '0');
insert into T_AUTHORITY (res_id, res_name, res_type, res_url, other_res, orders, pid, iconclass, script_text, update_ts, xtype)
values (403, '客户价格维护', 2, 'customer/setPrice.html', null, 3, 40, 'icon icon-lightbulb', null, to_date('10-08-2016', 'dd-mm-yyyy'), '0');
insert into T_AUTHORITY (res_id, res_name, res_type, res_url, other_res, orders, pid, iconclass, script_text, update_ts, xtype)
values (98, '配置与监控', 1, '#', null, 98, null, 'icon  icon-certificate', null, to_date('10-08-2016', 'dd-mm-yyyy'), '0');
insert into T_AUTHORITY (res_id, res_name, res_type, res_url, other_res, orders, pid, iconclass, script_text, update_ts, xtype)
values (9801, '全局参数配置', 2, 'monitor/config.html', null, 1, 98, 'icon icon-cogs', null, to_date('10-08-2016', 'dd-mm-yyyy'), '0');
insert into T_AUTHORITY (res_id, res_name, res_type, res_url, other_res, orders, pid, iconclass, script_text, update_ts, xtype)
values (9802, '全局异常信息配置', 2, 'monitor/exception.html', null, 2, 98, 'icon icon-warning-sign', null, to_date('10-08-2016', 'dd-mm-yyyy'), '0');
insert into T_AUTHORITY (res_id, res_name, res_type, res_url, other_res, orders, pid, iconclass, script_text, update_ts, xtype)
values (9803, '计划任务管理', 2, 'monitor/task.html', null, 3, 98, 'icon icon-tasks', null, to_date('10-08-2016', 'dd-mm-yyyy'), '0');
insert into T_AUTHORITY (res_id, res_name, res_type, res_url, other_res, orders, pid, iconclass, script_text, update_ts, xtype)
values (703, '历史申请', 2, 'process/history.html', null, 3, 70, 'icon icon-check', null, to_date('10-08-2016', 'dd-mm-yyyy'), '0');
insert into T_AUTHORITY (res_id, res_name, res_type, res_url, other_res, orders, pid, iconclass, script_text, update_ts, xtype)
values (9999, '公共权限', 1, '#', null, 0, null, null, null, to_date('10-08-2016', 'dd-mm-yyyy'), '1');
insert into T_AUTHORITY (res_id, res_name, res_type, res_url, other_res, orders, pid, iconclass, script_text, update_ts, xtype)
values (99990001, '首页权限', 3, 'index.jhtml', null, 1, 9999, null, null, to_date('10-08-2016', 'dd-mm-yyyy'), '1');
insert into T_AUTHORITY (res_id, res_name, res_type, res_url, other_res, orders, pid, iconclass, script_text, update_ts, xtype)
values (99990002, '总览页面', 3, 'dashboard.html', 'custNum,auditOrder,mytaskNum', 1, 9999, null, null, to_date('10-08-2016', 'dd-mm-yyyy'), '1');
insert into T_AUTHORITY (res_id, res_name, res_type, res_url, other_res, orders, pid, iconclass, script_text, update_ts, xtype)
values (10201, '查询用户', 3, 'system/emp/list*', 'Org/list', 1, 102, 'icon icon-circle', null, to_date('10-08-2016', 'dd-mm-yyyy'), '0');
insert into T_AUTHORITY (res_id, res_name, res_type, res_url, other_res, orders, pid, iconclass, script_text, update_ts, xtype)
values (10202, '新增用户', 3, 'system/emp/add', 'system/emp/checkUser*', 2, 102, 'icon icon-circle', null, to_date('10-08-2016', 'dd-mm-yyyy'), '0');
insert into T_AUTHORITY (res_id, res_name, res_type, res_url, other_res, orders, pid, iconclass, script_text, update_ts, xtype)
values (10203, '修改用户', 3, 'system/emp/edit', null, 3, 102, 'icon icon-circle', null, to_date('10-08-2016', 'dd-mm-yyyy'), '0');
insert into T_AUTHORITY (res_id, res_name, res_type, res_url, other_res, orders, pid, iconclass, script_text, update_ts, xtype)
values (10204, '删除用户', 3, 'system/emp/del', null, 4, 102, 'icon icon-circle', null, to_date('10-08-2016', 'dd-mm-yyyy'), '0');
insert into T_AUTHORITY (res_id, res_name, res_type, res_url, other_res, orders, pid, iconclass, script_text, update_ts, xtype)
values (10205, '重置密码', 3, 'system/emp/pwdRest', 'system/emp/pwdReset', 5, 102, 'icon icon-circle', null, to_date('10-08-2016', 'dd-mm-yyyy'), '0');
insert into T_AUTHORITY (res_id, res_name, res_type, res_url, other_res, orders, pid, iconclass, script_text, update_ts, xtype)
values (10206, '用户停用', 3, 'system/emp/userStop', null, 6, 102, 'icon icon-circle', null, to_date('10-08-2016', 'dd-mm-yyyy'), '0');
insert into T_AUTHORITY (res_id, res_name, res_type, res_url, other_res, orders, pid, iconclass, script_text, update_ts, xtype)
values (10207, '用户启用', 3, 'system/emp/userStart', null, 7, 102, 'icon icon-circle', null, to_date('10-08-2016', 'dd-mm-yyyy'), '0');
insert into T_AUTHORITY (res_id, res_name, res_type, res_url, other_res, orders, pid, iconclass, script_text, update_ts, xtype)
values (10301, '知识库查询', 3, 'knowledge/list*', 'knowledge/category', 1, 103, 'icon icon-circle', null, to_date('10-08-2016', 'dd-mm-yyyy'), '0');
insert into T_AUTHORITY (res_id, res_name, res_type, res_url, other_res, orders, pid, iconclass, script_text, update_ts, xtype)
values (10302, '新增知识库', 3, 'knowledge/addFile', null, 2, 103, 'icon icon-circle', null, to_date('10-08-2016', 'dd-mm-yyyy'), '0');
insert into T_AUTHORITY (res_id, res_name, res_type, res_url, other_res, orders, pid, iconclass, script_text, update_ts, xtype)
values (10303, '删除知识库', 3, 'knowledge/del', null, 3, 103, 'icon icon-circle', null, to_date('10-08-2016', 'dd-mm-yyyy'), '0');
insert into T_AUTHORITY (res_id, res_name, res_type, res_url, other_res, orders, pid, iconclass, script_text, update_ts, xtype)
values (10401, '公告查询', 3, 'system/notes/list*', 'system/notes/showall.html*', 1, 104, 'icon icon-circle', null, to_date('10-08-2016', 'dd-mm-yyyy'), '0');
insert into T_AUTHORITY (res_id, res_name, res_type, res_url, other_res, orders, pid, iconclass, script_text, update_ts, xtype)
values (10402, '查看公告', 3, 'admin/system/notes/look/*', null, 2, 104, 'icon icon-circle', null, to_date('10-08-2016', 'dd-mm-yyyy'), '0');
insert into T_AUTHORITY (res_id, res_name, res_type, res_url, other_res, orders, pid, iconclass, script_text, update_ts, xtype)
values (10403, '新增公告', 3, 'system/notes/notesAdd.html', 'Org/listPid,system/notes/uploadImg*,system/notes/add', 3, 104, 'icon icon-circle', null, to_date('10-08-2016', 'dd-mm-yyyy'), '0');
insert into T_AUTHORITY (res_id, res_name, res_type, res_url, other_res, orders, pid, iconclass, script_text, update_ts, xtype)
values (10404, '修改公告', 3, 'system/notes/preEdit*', 'Org/listPid,system/notes/uploadImg*,system/notes/add,system/notes/delAtta', 4, 104, 'icon icon-circle', null, to_date('10-08-2016', 'dd-mm-yyyy'), '0');
insert into T_AUTHORITY (res_id, res_name, res_type, res_url, other_res, orders, pid, iconclass, script_text, update_ts, xtype)
values (10405, '提交审批', 3, 'system/notes/apply', null, 5, 104, 'icon icon-circle', null, to_date('10-08-2016', 'dd-mm-yyyy'), '0');
insert into T_AUTHORITY (res_id, res_name, res_type, res_url, other_res, orders, pid, iconclass, script_text, update_ts, xtype)
values (10406, '公告审批', 3, 'system/notes/passed', null, 6, 104, 'icon icon-circle', null, to_date('10-08-2016', 'dd-mm-yyyy'), '0');
insert into T_AUTHORITY (res_id, res_name, res_type, res_url, other_res, orders, pid, iconclass, script_text, update_ts, xtype)
values (10407, '删除公告', 3, 'system/notes/del', null, 7, 104, 'icon icon-circle', null, to_date('10-08-2016', 'dd-mm-yyyy'), '0');
insert into T_AUTHORITY (res_id, res_name, res_type, res_url, other_res, orders, pid, iconclass, script_text, update_ts, xtype)
values (20101, '添加组织架构', 3, 'Org/add', null, 1, 201, 'icon icon-circle', null, to_date('13-09-2016 15:32:47', 'dd-mm-yyyy hh24:mi:ss'), '0');
insert into T_AUTHORITY (res_id, res_name, res_type, res_url, other_res, orders, pid, iconclass, script_text, update_ts, xtype)
values (20102, '修改组织架构', 3, 'Org/edit', null, 2, 201, 'icon icon-cicle', null, to_date('13-09-2016 15:35:50', 'dd-mm-yyyy hh24:mi:ss'), '0');
insert into T_AUTHORITY (res_id, res_name, res_type, res_url, other_res, orders, pid, iconclass, script_text, update_ts, xtype)
values (20103, '删除组织架构', 3, 'Org/del*', null, 3, 201, 'icon icon-cicle', null, to_date('13-09-2016 15:38:37', 'dd-mm-yyyy hh24:mi:ss'), '0');
insert into T_AUTHORITY (res_id, res_name, res_type, res_url, other_res, orders, pid, iconclass, script_text, update_ts, xtype)
values (20201, '销售区域授权', 3, 'Org/grant*', 'pub/area/list,Org/list,Org/getAuth*', 1, 202, 'icon icon-cicle', null, to_date('13-09-2016 15:41:11', 'dd-mm-yyyy hh24:mi:ss'), '0');
insert into T_AUTHORITY (res_id, res_name, res_type, res_url, other_res, orders, pid, iconclass, script_text, update_ts, xtype)
values (20301, '添加销售组织', 3, 'station/save*', 'system/emp/list*', 1, 203, 'icon icon-cicle', null, to_date('13-09-2016 15:43:19', 'dd-mm-yyyy hh24:mi:ss'), '0');
insert into T_AUTHORITY (res_id, res_name, res_type, res_url, other_res, orders, pid, iconclass, script_text, update_ts, xtype)
values (20302, '修改销售组织', 3, 'station/edit*', 'system/emp/list*', 2, 203, 'icon icon-cicle', null, to_date('13-09-2016 15:44:10', 'dd-mm-yyyy hh24:mi:ss'), '0');
insert into T_AUTHORITY (res_id, res_name, res_type, res_url, other_res, orders, pid, iconclass, script_text, update_ts, xtype)
values (20303, '删除销售组织', 3, 'station/delete*', null, 3, 203, 'icon icon-cicle', null, to_date('13-09-2016 15:44:55', 'dd-mm-yyyy hh24:mi:ss'), '0');
insert into T_AUTHORITY (res_id, res_name, res_type, res_url, other_res, orders, pid, iconclass, script_text, update_ts, xtype)
values (20401, '添加职位', 3, 'jobstation/save*', null, 1, 204, 'icon icon-cicle', null, to_date('13-09-2016 15:46:56', 'dd-mm-yyyy hh24:mi:ss'), '0');
insert into T_AUTHORITY (res_id, res_name, res_type, res_url, other_res, orders, pid, iconclass, script_text, update_ts, xtype)
values (20402, '修改职位', 3, 'jobstation/edit*', null, 2, 204, 'icon icon-cicle', null, to_date('13-09-2016 15:47:42', 'dd-mm-yyyy hh24:mi:ss'), '0');
insert into T_AUTHORITY (res_id, res_name, res_type, res_url, other_res, orders, pid, iconclass, script_text, update_ts, xtype)
values (20403, '删除职位', 3, 'jobstation/delete*', null, 3, 204, 'iocn icon-cicle', null, to_date('13-09-2016 15:48:22', 'dd-mm-yyyy hh24:mi:ss'), '0');
insert into T_AUTHORITY (res_id, res_name, res_type, res_url, other_res, orders, pid, iconclass, script_text, update_ts, xtype)
values (20501, '职位关联', 3, 'jobstation/jobset/relation*', 'jobstation/jobset/list*', 1, 205, 'icon icon-cicle', null, to_date('13-09-2016 15:49:59', 'dd-mm-yyyy hh24:mi:ss'), '0');
insert into T_AUTHORITY (res_id, res_name, res_type, res_url, other_res, orders, pid, iconclass, script_text, update_ts, xtype)
values (30101, '添加产品分类', 3, 'product/categroy/add*', null, 1, 301, 'icon icon-cicle', null, to_date('13-09-2016 15:52:33', 'dd-mm-yyyy hh24:mi:ss'), '0');
insert into T_AUTHORITY (res_id, res_name, res_type, res_url, other_res, orders, pid, iconclass, script_text, update_ts, xtype)
values (40201, '查询合同', 3, 'customer/contract/list*', null, 1, 402, 'icon icon-circle', null, to_date('14-09-2016', 'dd-mm-yyyy'), '0');
insert into T_AUTHORITY (res_id, res_name, res_type, res_url, other_res, orders, pid, iconclass, script_text, update_ts, xtype)
values (40202, '新增合同', 3, 'customer/addPaper.html', 'salePolicy/policyorg,org/powerOrg,customer/contract/addCustPaper,customer/contract/addPaperLine,customer/contract/lines?order*,customer/list*,pub/area/list*,customer/contract/factorys*,product/series*,product/iPackage*,product/brand*', 2, 402, 'icon icon-circle', null, to_date('14-09-2016', 'dd-mm-yyyy'), '0');
insert into T_AUTHORITY (res_id, res_name, res_type, res_url, other_res, orders, pid, iconclass, script_text, update_ts, xtype)
values (40203, '合同详情', 3, 'customer/contract/contractDetails.html*', 'customer/contract/lines*', 3, 402, 'icon icon-circle', null, to_date('14-09-2016', 'dd-mm-yyyy'), '0');
insert into T_AUTHORITY (res_id, res_name, res_type, res_url, other_res, orders, pid, iconclass, script_text, update_ts, xtype)
values (40204, '修改合同', 3, 'customer/contract/preEdit*', 'customer/contract/delPaperLines*,customer/contract/updateLines*,customer/contract/addPaperLine*', 4, 402, 'icon icon-circle', null, to_date('14-09-2016', 'dd-mm-yyyy'), '0');
insert into T_AUTHORITY (res_id, res_name, res_type, res_url, other_res, orders, pid, iconclass, script_text, update_ts, xtype)
values (40205, '删除合同', 3, 'customer/contract/delContract*', null, 5, 402, 'icon icon-circle', null, to_date('14-09-2016', 'dd-mm-yyyy'), '0');
insert into T_AUTHORITY (res_id, res_name, res_type, res_url, other_res, orders, pid, iconclass, script_text, update_ts, xtype)
values (40206, '合同提交审批', 3, 'customer/contract/updateContractStates*', null, 6, 402, 'icon icon-circle', null, to_date('14-09-2016', 'dd-mm-yyyy'), '0');
insert into T_AUTHORITY (res_id, res_name, res_type, res_url, other_res, orders, pid, iconclass, script_text, update_ts, xtype)
values (50101, '余额查询', 3, 'account/merchaccount*', null, 1, 501, 'icon icon-circle', null, to_date('14-09-2016', 'dd-mm-yyyy'), '0');
insert into T_AUTHORITY (res_id, res_name, res_type, res_url, other_res, orders, pid, iconclass, script_text, update_ts, xtype)
values (50201, '录入查询', 3, 'account/upaccount/inputList*', null, 1, 502, 'icon icon-circle', null, to_date('14-09-2016', 'dd-mm-yyyy'), '0');
insert into T_AUTHORITY (res_id, res_name, res_type, res_url, other_res, orders, pid, iconclass, script_text, update_ts, xtype)
values (50202, '录入新增', 3, 'account/upaccount/add*', 'account/upaccount/accountcustomer*', 2, 502, 'icon icon-circle', null, to_date('14-09-2016', 'dd-mm-yyyy'), '0');
insert into T_AUTHORITY (res_id, res_name, res_type, res_url, other_res, orders, pid, iconclass, script_text, update_ts, xtype)
values (50203, '录入修改', 3, 'account/upaccount/edit*', null, 3, 502, 'icon icon-circle', null, to_date('14-09-2016', 'dd-mm-yyyy'), '0');
insert into T_AUTHORITY (res_id, res_name, res_type, res_url, other_res, orders, pid, iconclass, script_text, update_ts, xtype)
values (50204, '录入删除', 4, 'account/upaccount/del*', null, 4, 502, 'icon icon-circle', null, to_date('14-09-2016', 'dd-mm-yyyy'), '0');
insert into T_AUTHORITY (res_id, res_name, res_type, res_url, other_res, orders, pid, iconclass, script_text, update_ts, xtype)
values (50205, '录入提交', 4, 'account/upaccount/submit*', null, 5, 502, 'icon icon-circle', null, to_date('14-09-2016', 'dd-mm-yyyy'), '0');
commit;
prompt 100 records committed...
insert into T_AUTHORITY (res_id, res_name, res_type, res_url, other_res, orders, pid, iconclass, script_text, update_ts, xtype)
values (50301, '资金确认查询', 3, 'account/upaccount/salesAccountList*', null, 1, 503, 'icon icon-circle', null, to_date('14-09-2016', 'dd-mm-yyyy'), '0');
insert into T_AUTHORITY (res_id, res_name, res_type, res_url, other_res, orders, pid, iconclass, script_text, update_ts, xtype)
values (50302, '资金确认', 3, 'account/upaccount/edit*', 'account/upaccount/salesConfirm*', 2, 503, 'icon icon-circle', null, to_date('14-09-2016', 'dd-mm-yyyy'), '0');
insert into T_AUTHORITY (res_id, res_name, res_type, res_url, other_res, orders, pid, iconclass, script_text, update_ts, xtype)
values (50303, '资金确认提交', 3, 'account/upaccount/submit*', null, 3, 503, 'icon icon-circle', null, to_date('14-09-2016', 'dd-mm-yyyy'), '0');
insert into T_AUTHORITY (res_id, res_name, res_type, res_url, other_res, orders, pid, iconclass, script_text, update_ts, xtype)
values (50401, '资金上账修改', 3, 'account/upaccount/edit*', null, 1, 504, 'icon icon-circle', null, to_date('10-08-2016', 'dd-mm-yyyy'), '0');
insert into T_AUTHORITY (res_id, res_name, res_type, res_url, other_res, orders, pid, iconclass, script_text, update_ts, xtype)
values (50402, '资金上账通过', 3, 'account/upaccount/submit*', null, 2, 504, 'icon icon-circle', null, to_date('10-08-2016', 'dd-mm-yyyy'), '0');
insert into T_AUTHORITY (res_id, res_name, res_type, res_url, other_res, orders, pid, iconclass, script_text, update_ts, xtype)
values (50403, '资金上账驳回', 3, 'account/upaccount/submit*', null, 3, 504, 'icon icon-circle', null, to_date('10-08-2016', 'dd-mm-yyyy'), '0');
insert into T_AUTHORITY (res_id, res_name, res_type, res_url, other_res, orders, pid, iconclass, script_text, update_ts, xtype)
values (50501, '资金调整查询', 3, 'account/adjust/list*', null, 1, 505, 'icon icon-circle', null, to_date('14-09-2016', 'dd-mm-yyyy'), '0');
insert into T_AUTHORITY (res_id, res_name, res_type, res_url, other_res, orders, pid, iconclass, script_text, update_ts, xtype)
values (50502, '资金调整录入', 3, 'account/adjust/add*', 'account/util/adjustorg,account/util/customer*', 2, 505, 'icon icon-circle', null, to_date('14-09-2016', 'dd-mm-yyyy'), '0');
insert into T_AUTHORITY (res_id, res_name, res_type, res_url, other_res, orders, pid, iconclass, script_text, update_ts, xtype)
values (50503, '资金调整修改', 3, 'account/adjust/edit*', 'account/util/adjustorg,account/util/customer*', 3, 505, 'icon icon-circle', null, to_date('14-09-2016', 'dd-mm-yyyy'), '0');
insert into T_AUTHORITY (res_id, res_name, res_type, res_url, other_res, orders, pid, iconclass, script_text, update_ts, xtype)
values (50504, '资金调整删除', 3, 'account/adjust/del*', null, 4, 505, 'icon icon-circle', null, to_date('14-09-2016', 'dd-mm-yyyy'), '0');
insert into T_AUTHORITY (res_id, res_name, res_type, res_url, other_res, orders, pid, iconclass, script_text, update_ts, xtype)
values (50505, '资金调整提交', 3, 'account/adjust/audit*', null, 5, 505, 'icon icon-circle', null, to_date('14-09-2016', 'dd-mm-yyyy'), '0');
insert into T_AUTHORITY (res_id, res_name, res_type, res_url, other_res, orders, pid, iconclass, script_text, update_ts, xtype)
values (50601, '资金对账查询', 3, 'account/period/list*', null, 1, 506, 'icon icon-circle', null, to_date('14-09-2016', 'dd-mm-yyyy'), '0');
insert into T_AUTHORITY (res_id, res_name, res_type, res_url, other_res, orders, pid, iconclass, script_text, update_ts, xtype)
values (50602, '资金对账明细', 3, 'account/period/detail*', 'account/period/custPeriod.html*', 2, 506, 'icon icon-circle', null, to_date('14-09-2016', 'dd-mm-yyyy'), '0');
insert into T_AUTHORITY (res_id, res_name, res_type, res_url, other_res, orders, pid, iconclass, script_text, update_ts, xtype)
values (50701, '合同返利查询', 3, 'account/rebate/list*', null, 1, 507, 'icon icon-circle', null, to_date('14-09-2016', 'dd-mm-yyyy'), '0');
insert into T_AUTHORITY (res_id, res_name, res_type, res_url, other_res, orders, pid, iconclass, script_text, update_ts, xtype)
values (50702, '合同返利明细', 3, 'account/rebate/orders*', null, 2, 507, 'icon icon-circle', null, to_date('14-09-2016', 'dd-mm-yyyy'), '0');
insert into T_AUTHORITY (res_id, res_name, res_type, res_url, other_res, orders, pid, iconclass, script_text, update_ts, xtype)
values (60201, '查询功能', 3, 'order/orderlist*', null, 1, 602, 'icon icon-circle', null, to_date('14-09-2016', 'dd-mm-yyyy'), '0');
insert into T_AUTHORITY (res_id, res_name, res_type, res_url, other_res, orders, pid, iconclass, script_text, update_ts, xtype)
values (60202, '修改功能', 3, 'order/orderedit.html*', 'order/util/linedata*,order/util/customerAccount*,order/util/custProduct*,order/edit/addline*,order/edit/editline*,order/edit/delLine*,order/specialorderEdit.html*,order/updateHeader*', 2, 602, 'icon icon-circle', null, to_date('14-09-2016', 'dd-mm-yyyy'), '0');
insert into T_AUTHORITY (res_id, res_name, res_type, res_url, other_res, orders, pid, iconclass, script_text, update_ts, xtype)
values (60203, '查看明细', 3, 'order/orderdetails.html*', 'order/util/linedata*,order/orderLineDetails*', 3, 602, 'icon icon-circle', null, to_date('14-09-2016', 'dd-mm-yyyy'), '0');
insert into T_AUTHORITY (res_id, res_name, res_type, res_url, other_res, orders, pid, iconclass, script_text, update_ts, xtype)
values (60204, '删除功能', 3, 'order/delorder*', null, 4, 602, 'icon icon-circle', null, to_date('14-09-2016', 'dd-mm-yyyy'), '0');
insert into T_AUTHORITY (res_id, res_name, res_type, res_url, other_res, orders, pid, iconclass, script_text, update_ts, xtype)
values (60205, '提交审批', 3, 'order/commitOrder*', 'order/orderAudit*,order/feedback*,order/manualSend*', 5, 602, 'icon icon-circle', null, to_date('14-09-2016', 'dd-mm-yyyy'), '0');
insert into T_AUTHORITY (res_id, res_name, res_type, res_url, other_res, orders, pid, iconclass, script_text, update_ts, xtype)
values (60206, '再次购买', 3, 'order/orderSaveAgain.html*', null, 6, 602, 'icon icon-circle', null, to_date('14-09-2016', 'dd-mm-yyyy'), '0');
insert into T_AUTHORITY (res_id, res_name, res_type, res_url, other_res, orders, pid, iconclass, script_text, update_ts, xtype)
values (60301, '退货查询', 3, 'orderBack/list*', null, 1, 603, 'icon icon-circle', null, to_date('14-09-2016', 'dd-mm-yyyy'), '0');
insert into T_AUTHORITY (res_id, res_name, res_type, res_url, other_res, orders, pid, iconclass, script_text, update_ts, xtype)
values (60302, '退货录入', 3, 'orderBack/add*', null, 2, 603, 'icon icon-circle', null, to_date('14-09-2016', 'dd-mm-yyyy'), '0');
insert into T_AUTHORITY (res_id, res_name, res_type, res_url, other_res, orders, pid, iconclass, script_text, update_ts, xtype)
values (60303, '退货修改', 3, 'orderBack/edit*', null, 3, 603, 'icon icon-circle', null, to_date('14-09-2016', 'dd-mm-yyyy'), '0');
insert into T_AUTHORITY (res_id, res_name, res_type, res_url, other_res, orders, pid, iconclass, script_text, update_ts, xtype)
values (60304, '退货删除', 3, 'orderBack/del*', null, 4, 603, 'icon icon-circle', null, to_date('14-09-2016', 'dd-mm-yyyy'), '0');
insert into T_AUTHORITY (res_id, res_name, res_type, res_url, other_res, orders, pid, iconclass, script_text, update_ts, xtype)
values (60305, '退货提交', 3, 'orderBack/updateStates*', null, 5, 603, 'icon icon-circle', null, to_date('14-09-2016', 'dd-mm-yyyy'), '0');
insert into T_AUTHORITY (res_id, res_name, res_type, res_url, other_res, orders, pid, iconclass, script_text, update_ts, xtype)
values (80101, '政策申请', 3, 'salePolicy/header/add*,salePolicy/lines/add*', null, 1, 801, 'icon icon-circle', null, to_date('14-09-2016', 'dd-mm-yyyy'), '0');
insert into T_AUTHORITY (res_id, res_name, res_type, res_url, other_res, orders, pid, iconclass, script_text, update_ts, xtype)
values (80102, '政策修改', 3, 'salePolicy/editPolicyLine*', null, 2, 801, 'icon icon-circle', null, to_date('14-09-2016', 'dd-mm-yyyy'), '0');
insert into T_AUTHORITY (res_id, res_name, res_type, res_url, other_res, orders, pid, iconclass, script_text, update_ts, xtype)
values (80103, '政策删除', 3, 'salePolicy/delpolicy*', null, 3, 801, 'icon icon-circle', null, to_date('14-09-2016', 'dd-mm-yyyy'), '0');
insert into T_AUTHORITY (res_id, res_name, res_type, res_url, other_res, orders, pid, iconclass, script_text, update_ts, xtype)
values (80104, '政策详情', 3, 'salePolicy/policyDetails.html*', null, 4, 801, 'icon icon-circle', null, to_date('14-09-2016', 'dd-mm-yyyy'), '0');
insert into T_AUTHORITY (res_id, res_name, res_type, res_url, other_res, orders, pid, iconclass, script_text, update_ts, xtype)
values (80105, '政策核销明细', 3, 'salePolicy/policyWriteOff.html*', null, 5, 801, 'icon icon-circle', null, to_date('14-09-2016', 'dd-mm-yyyy'), '0');
insert into T_AUTHORITY (res_id, res_name, res_type, res_url, other_res, orders, pid, iconclass, script_text, update_ts, xtype)
values (80106, '政策提交', 3, 'salePolicy/submit*', null, 6, 801, 'icon icon-circle', null, to_date('14-09-2016', 'dd-mm-yyyy'), '0');
insert into T_AUTHORITY (res_id, res_name, res_type, res_url, other_res, orders, pid, iconclass, script_text, update_ts, xtype)
values (80107, '政策查询', 3, 'salePolicy/policylist*', null, 7, 801, 'icon icon-circle', null, to_date('14-09-2016', 'dd-mm-yyyy'), '0');
insert into T_AUTHORITY (res_id, res_name, res_type, res_url, other_res, orders, pid, iconclass, script_text, update_ts, xtype)
values (80201, '政策类型查询', 3, 'salepolicy/policyType/applyTypeList*', null, 1, 802, 'icon icon-circle', null, to_date('14-09-2016', 'dd-mm-yyyy'), '0');
insert into T_AUTHORITY (res_id, res_name, res_type, res_url, other_res, orders, pid, iconclass, script_text, update_ts, xtype)
values (80202, '政策类型新增', 3, 'salepolicy/policyType/addPolicyType*', null, 2, 802, 'icon icon-circle', null, to_date('14-09-2016', 'dd-mm-yyyy'), '0');
insert into T_AUTHORITY (res_id, res_name, res_type, res_url, other_res, orders, pid, iconclass, script_text, update_ts, xtype)
values (80203, '政策类型修改', 3, 'salepolicy/policyType/editPolicyType*', null, 3, 802, 'icon icon-circle', null, to_date('14-09-2016', 'dd-mm-yyyy'), '0');
insert into T_AUTHORITY (res_id, res_name, res_type, res_url, other_res, orders, pid, iconclass, script_text, update_ts, xtype)
values (80204, '政策类型删除', 3, 'salepolicy/policyType/delPolicyType*', null, 4, 802, 'icon icon-circle', null, to_date('14-09-2016', 'dd-mm-yyyy'), '0');
insert into T_AUTHORITY (res_id, res_name, res_type, res_url, other_res, orders, pid, iconclass, script_text, update_ts, xtype)
values (100101, '查询', 3, 'promotion/material/list*', null, 1, 1001, 'icon icon-circle', null, to_date('14-09-2016', 'dd-mm-yyyy'), '0');
insert into T_AUTHORITY (res_id, res_name, res_type, res_url, other_res, orders, pid, iconclass, script_text, update_ts, xtype)
values (100102, '新增', 3, 'promotion/material/add*', null, 2, 1001, 'icon icon-circle', null, to_date('14-09-2016', 'dd-mm-yyyy'), '0');
insert into T_AUTHORITY (res_id, res_name, res_type, res_url, other_res, orders, pid, iconclass, script_text, update_ts, xtype)
values (100103, '修改', 3, 'promotion/material/edit*', null, 3, 1001, 'icon icon-circle', null, to_date('14-09-2016', 'dd-mm-yyyy'), '0');
insert into T_AUTHORITY (res_id, res_name, res_type, res_url, other_res, orders, pid, iconclass, script_text, update_ts, xtype)
values (100104, '删除', 3, 'promotion/material/del*', null, 4, 1001, 'icon icon-circle', null, to_date('14-09-2016', 'dd-mm-yyyy'), '0');
insert into T_AUTHORITY (res_id, res_name, res_type, res_url, other_res, orders, pid, iconclass, script_text, update_ts, xtype)
values (100201, '查询', 3, 'promotion/stores/list*', null, 1, 1002, 'icon icon-circle', null, to_date('14-09-2016', 'dd-mm-yyyy'), '0');
insert into T_AUTHORITY (res_id, res_name, res_type, res_url, other_res, orders, pid, iconclass, script_text, update_ts, xtype)
values (100202, '新增', 3, 'promotion/stores/add*', null, 2, 1002, 'icon icon-circle', null, to_date('14-09-2016', 'dd-mm-yyyy'), '0');
insert into T_AUTHORITY (res_id, res_name, res_type, res_url, other_res, orders, pid, iconclass, script_text, update_ts, xtype)
values (100203, '修改', 3, 'promotion/stores/edit*', null, 3, 1002, 'icon icon-circle', null, to_date('14-09-2016', 'dd-mm-yyyy'), '0');
insert into T_AUTHORITY (res_id, res_name, res_type, res_url, other_res, orders, pid, iconclass, script_text, update_ts, xtype)
values (100204, '删除', 3, 'promotion/stores/edl*', null, 4, 1002, 'icon icon-circle', null, to_date('14-09-2016', 'dd-mm-yyyy'), '0');
insert into T_AUTHORITY (res_id, res_name, res_type, res_url, other_res, orders, pid, iconclass, script_text, update_ts, xtype)
values (100301, '查询', 3, 'promotion/Pur/list*', null, 1, 1003, 'icon icon-circle', null, to_date('14-09-2016', 'dd-mm-yyyy'), '0');
insert into T_AUTHORITY (res_id, res_name, res_type, res_url, other_res, orders, pid, iconclass, script_text, update_ts, xtype)
values (100302, '新增', 3, 'promotion/Pur/add*', null, 2, 1003, 'icon icon-circle', null, to_date('14-09-2016', 'dd-mm-yyyy'), '0');
insert into T_AUTHORITY (res_id, res_name, res_type, res_url, other_res, orders, pid, iconclass, script_text, update_ts, xtype)
values (100303, '修改', 3, 'promotion/Pur/edit*', null, 3, 1003, 'icon icon-circle', null, to_date('14-09-2016', 'dd-mm-yyyy'), '0');
insert into T_AUTHORITY (res_id, res_name, res_type, res_url, other_res, orders, pid, iconclass, script_text, update_ts, xtype)
values (100304, '删除', 3, 'promotion/Pur/edl*', null, 4, 1003, 'icon icon-circle', null, to_date('14-09-2016', 'dd-mm-yyyy'), '0');
insert into T_AUTHORITY (res_id, res_name, res_type, res_url, other_res, orders, pid, iconclass, script_text, update_ts, xtype)
values (100401, '查询', 3, 'promotion/inv/list*', null, 1, 1004, 'icon icon-circle', null, to_date('14-09-2016', 'dd-mm-yyyy'), '0');
insert into T_AUTHORITY (res_id, res_name, res_type, res_url, other_res, orders, pid, iconclass, script_text, update_ts, xtype)
values (100402, '新增', 3, 'promotion/inv/addApply*', null, 2, 1004, 'icon icon-circle', null, to_date('14-09-2016', 'dd-mm-yyyy'), '0');
insert into T_AUTHORITY (res_id, res_name, res_type, res_url, other_res, orders, pid, iconclass, script_text, update_ts, xtype)
values (100403, '修改', 3, 'promotion/inv/editApply*', null, 3, 1004, 'icon icon-circle', null, to_date('14-09-2016', 'dd-mm-yyyy'), '0');
insert into T_AUTHORITY (res_id, res_name, res_type, res_url, other_res, orders, pid, iconclass, script_text, update_ts, xtype)
values (100404, '删除', 3, 'promotion/inv/delApply*', null, 4, 1004, 'icon icon-circle', null, to_date('14-09-2016', 'dd-mm-yyyy'), '0');
insert into T_AUTHORITY (res_id, res_name, res_type, res_url, other_res, orders, pid, iconclass, script_text, update_ts, xtype)
values (100405, '提交', 3, 'promotion/inv/updateStates*', null, 5, 1004, 'icon icon-circle', null, to_date('14-09-2016', 'dd-mm-yyyy'), '0');
insert into T_AUTHORITY (res_id, res_name, res_type, res_url, other_res, orders, pid, iconclass, script_text, update_ts, xtype)
values (100501, '查询', 3, 'promotion/inv/list*', null, 1, 1005, 'icon icon-circle', null, to_date('14-09-2016', 'dd-mm-yyyy'), '0');
insert into T_AUTHORITY (res_id, res_name, res_type, res_url, other_res, orders, pid, iconclass, script_text, update_ts, xtype)
values (100502, '新增', 3, 'promotion/inv/addApply*', null, 2, 1005, 'icon icon-circle', null, to_date('14-09-2016', 'dd-mm-yyyy'), '0');
insert into T_AUTHORITY (res_id, res_name, res_type, res_url, other_res, orders, pid, iconclass, script_text, update_ts, xtype)
values (100503, '修改', 3, 'promotion/inv/editApply*', null, 3, 1005, 'icon icon-circle', null, to_date('14-09-2016', 'dd-mm-yyyy'), '0');
insert into T_AUTHORITY (res_id, res_name, res_type, res_url, other_res, orders, pid, iconclass, script_text, update_ts, xtype)
values (100504, '删除', 3, 'promotion/inv/delApply*', null, 4, 1005, 'icon icon-circle', null, to_date('14-09-2016', 'dd-mm-yyyy'), '0');
insert into T_AUTHORITY (res_id, res_name, res_type, res_url, other_res, orders, pid, iconclass, script_text, update_ts, xtype)
values (100505, '提交', 3, 'promotion/inv/OutupdateStates*', null, 5, 1005, 'icon icon-circle', null, to_date('14-09-2016', 'dd-mm-yyyy'), '0');
insert into T_AUTHORITY (res_id, res_name, res_type, res_url, other_res, orders, pid, iconclass, script_text, update_ts, xtype)
values (70201, '查询待处理', 3, 'process/waitMe?*', null, 1, 702, 'icon icon-check', null, to_date('10-08-2016', 'dd-mm-yyyy'), '0');
insert into T_AUTHORITY (res_id, res_name, res_type, res_url, other_res, orders, pid, iconclass, script_text, update_ts, xtype)
values (70202, '处理', 3, 'process/look*', 'process/commit,process/rollBack,order/makeSure.html*,order/submitMakeSure.html*,order/detail.html*,order/submitSendProduct.html*,customer/view*,order/editFactory*,order/orderaudit.html*', 2, 702, 'icon icon-check', null, to_date('10-08-2016', 'dd-mm-yyyy'), '0');
insert into T_AUTHORITY (res_id, res_name, res_type, res_url, other_res, orders, pid, iconclass, script_text, update_ts, xtype)
values (106, '配送商用户', 2, 'system/emp/delivery.html', null, 6, 10, 'icon icon-circle', null, to_date('23-09-2016 14:31:24', 'dd-mm-yyyy hh24:mi:ss'), '0');
insert into T_AUTHORITY (res_id, res_name, res_type, res_url, other_res, orders, pid, iconclass, script_text, update_ts, xtype)
values (405, '零售商信息管理', 2, 'customer/retail.html', null, 5, 40, 'icon icon-circle', null, to_date('23-09-2016 14:41:33', 'dd-mm-yyyy hh24:mi:ss'), '0');
insert into T_AUTHORITY (res_id, res_name, res_type, res_url, other_res, orders, pid, iconclass, script_text, update_ts, xtype)
values (10101, '查询角色', 3, 'system/role/list*', null, 1, 101, 'icon icon-circle', null, to_date('10-08-2016', 'dd-mm-yyyy'), '0');
insert into T_AUTHORITY (res_id, res_name, res_type, res_url, other_res, orders, pid, iconclass, script_text, update_ts, xtype)
values (10102, '角色添加', 3, 'system/role/add', null, 2, 101, 'icon icon-circle', null, to_date('10-08-2016', 'dd-mm-yyyy'), '0');
insert into T_AUTHORITY (res_id, res_name, res_type, res_url, other_res, orders, pid, iconclass, script_text, update_ts, xtype)
values (10103, '角色修改', 3, 'system/role/edit', null, 3, 101, 'icon icon-circle', null, to_date('10-08-2016', 'dd-mm-yyyy'), '0');
insert into T_AUTHORITY (res_id, res_name, res_type, res_url, other_res, orders, pid, iconclass, script_text, update_ts, xtype)
values (10104, '角色删除', 3, 'system/role/del', null, 4, 101, 'icon icon-circle', null, to_date('10-08-2016', 'dd-mm-yyyy'), '0');
insert into T_AUTHORITY (res_id, res_name, res_type, res_url, other_res, orders, pid, iconclass, script_text, update_ts, xtype)
values (10105, '角色授权', 3, 'system/role/grant', 'system/role/getAuth*,system/auth/list', 5, 101, 'icon icon-circle', null, to_date('10-08-2016', 'dd-mm-yyyy'), '0');
insert into T_AUTHORITY (res_id, res_name, res_type, res_url, other_res, orders, pid, iconclass, script_text, update_ts, xtype)
values (30102, '修改产品分类', 3, 'product/categroy/edit*', 'categroy/categroys*', 2, 301, 'icon icon-cicle', null, to_date('13-09-2016 15:53:27', 'dd-mm-yyyy hh24:mi:ss'), '0');
insert into T_AUTHORITY (res_id, res_name, res_type, res_url, other_res, orders, pid, iconclass, script_text, update_ts, xtype)
values (30103, '删除产品分类', 3, 'product/categroy/del*', null, 3, 301, 'icon icon-cicle', null, to_date('13-09-2016 15:54:18', 'dd-mm-yyyy hh24:mi:ss'), '0');
insert into T_AUTHORITY (res_id, res_name, res_type, res_url, other_res, orders, pid, iconclass, script_text, update_ts, xtype)
values (30201, '添加照片', 3, 'product/upload*', 'product/attachment/delete/*', 1, 302, 'icon icon-cicle', null, to_date('13-09-2016 16:00:08', 'dd-mm-yyyy hh24:mi:ss'), '0');
insert into T_AUTHORITY (res_id, res_name, res_type, res_url, other_res, orders, pid, iconclass, script_text, update_ts, xtype)
values (30202, '添加分类', 3, 'product/material/edit*', 'product/categroy/categroys*', 2, 302, 'icon icon-cicle', null, to_date('13-09-2016 16:01:24', 'dd-mm-yyyy hh24:mi:ss'), '0');
insert into T_AUTHORITY (res_id, res_name, res_type, res_url, other_res, orders, pid, iconclass, script_text, update_ts, xtype)
values (30301, '查看物料信息', 3, 'factory/materials*', null, 1, 303, 'icon icon-cicle', null, to_date('13-09-2016 16:05:42', 'dd-mm-yyyy hh24:mi:ss'), '0');
insert into T_AUTHORITY (res_id, res_name, res_type, res_url, other_res, orders, pid, iconclass, script_text, update_ts, xtype)
values (30302, '工厂修改', 3, 'factory/edit*', null, 2, 303, 'icon icon-cicle', null, to_date('13-09-2016 16:06:41', 'dd-mm-yyyy hh24:mi:ss'), '0');
insert into T_AUTHORITY (res_id, res_name, res_type, res_url, other_res, orders, pid, iconclass, script_text, update_ts, xtype)
values (50404, '资金上账查询', 3, 'account/upaccount/upAccountList*', 'account/upaccount/getSapMsg*,account/upaccount/submit*', 4, 504, 'icon icon-circle', null, to_date('23-09-2016', 'dd-mm-yyyy'), '0');
insert into T_AUTHORITY (res_id, res_name, res_type, res_url, other_res, orders, pid, iconclass, script_text, update_ts, xtype)
values (401, '客户档案管理', 2, 'customer/list.html', 'customer/list*,Org/listPid*', 1, 40, 'icon icon-th-large', null, to_date('08-10-2016', 'dd-mm-yyyy'), '0');
insert into T_AUTHORITY (res_id, res_name, res_type, res_url, other_res, orders, pid, iconclass, script_text, update_ts, xtype)
values (40101, '客户档案添加', 3, 'customer/index.html', 'pub/area/list*,pub/area/listChildren*,customer/save.html,customer/submit.html,customer/partlySave.html', 1, 401, 'icon icon-lemon', null, to_date('08-10-2016', 'dd-mm-yyyy'), '0');
insert into T_AUTHORITY (res_id, res_name, res_type, res_url, other_res, orders, pid, iconclass, script_text, update_ts, xtype)
values (40102, '客户档案编辑', 3, 'customer/edit*', 'pub/area/list*,pub/area/listChildren*,customer/save.html,customer/submit.html,customer/partlySave.html', 2, 401, 'icon icon-lemon', null, to_date('08-10-2016', 'dd-mm-yyyy'), '0');
insert into T_AUTHORITY (res_id, res_name, res_type, res_url, other_res, orders, pid, iconclass, script_text, update_ts, xtype)
values (40103, '客户档案查看', 3, 'customer/view*', 'pub/area/list*,pub/area/listChildren*,customer/save.html,customer/submit.html,customer/partlySave.html', 3, 401, 'icon icon-lemon', null, to_date('08-10-2016', 'dd-mm-yyyy'), '0');
insert into T_AUTHORITY (res_id, res_name, res_type, res_url, other_res, orders, pid, iconclass, script_text, update_ts, xtype)
values (40104, '客户档案提交审批', 3, 'customer/apply*', 'customer/feedback*,customer/manualSend*', 4, 401, 'icon icon-lemon', null, to_date('08-10-2016', 'dd-mm-yyyy'), '0');
insert into T_AUTHORITY (res_id, res_name, res_type, res_url, other_res, orders, pid, iconclass, script_text, update_ts, xtype)
values (40105, '客户档案删除', 3, 'customer/del*', null, 5, 401, 'icon icon-lemon', null, to_date('08-10-2016', 'dd-mm-yyyy'), '0');
insert into T_AUTHORITY (res_id, res_name, res_type, res_url, other_res, orders, pid, iconclass, script_text, update_ts, xtype)
values (40106, '客户档案指定岗位', 3, 'customer/setPosition*', 'customer/station*', 6, 401, 'icon icon-lemon', null, to_date('08-10-2016', 'dd-mm-yyyy'), '0');
insert into T_AUTHORITY (res_id, res_name, res_type, res_url, other_res, orders, pid, iconclass, script_text, update_ts, xtype)
values (404, '客户库存上报', 2, 'customer/custinv.html', 'customer/custinv/list*', 4, 40, 'icon icon-cloud-upload', null, to_date('08-10-2016', 'dd-mm-yyyy'), '0');
insert into T_AUTHORITY (res_id, res_name, res_type, res_url, other_res, orders, pid, iconclass, script_text, update_ts, xtype)
values (40401, '客户库存上报添加', 3, 'customer/custinv/add*', 'order/util/custProduct*,customer/findCusts*,order/util/customer*', 1, 404, 'icon icon-lemon', null, to_date('08-10-2016', 'dd-mm-yyyy'), '0');
insert into T_AUTHORITY (res_id, res_name, res_type, res_url, other_res, orders, pid, iconclass, script_text, update_ts, xtype)
values (40402, '客户库存上报修改', 3, 'customer/custinv/edit*', 'order/util/custProduct*,customer/findCusts*,order/util/customer*', 2, 404, 'icon icon-lemon', null, to_date('08-10-2016', 'dd-mm-yyyy'), '0');
insert into T_AUTHORITY (res_id, res_name, res_type, res_url, other_res, orders, pid, iconclass, script_text, update_ts, xtype)
values (40403, '客户库存上报删除', 3, 'customer/custinv/delete*', 'order/util/custProduct*,customer/findCusts*,order/util/customer*', 3, 404, 'icon icon-lemon', null, to_date('08-10-2016', 'dd-mm-yyyy'), '0');
insert into T_AUTHORITY (res_id, res_name, res_type, res_url, other_res, orders, pid, iconclass, script_text, update_ts, xtype)
values (41, '虚拟仓库管理', 1, '#', null, 8, null, 'icon  icon-group', null, to_date('10-08-2016', 'dd-mm-yyyy'), '0');
insert into T_AUTHORITY (res_id, res_name, res_type, res_url, other_res, orders, pid, iconclass, script_text, update_ts, xtype)
values (411, '虚拟仓库信息查询', 2, 'vw/index.html', 'vw/list*', 1, 41, 'icon  icon-certificate', null, to_date('08-10-2016', 'dd-mm-yyyy'), '0');
insert into T_AUTHORITY (res_id, res_name, res_type, res_url, other_res, orders, pid, iconclass, script_text, update_ts, xtype)
values (603, '销售退货', 2, 'orderBack/orderBack.html', null, 3, 60, 'icon icon-search', null, to_date('06-09-2016', 'dd-mm-yyyy'), '0');
insert into T_AUTHORITY (res_id, res_name, res_type, res_url, other_res, orders, pid, iconclass, script_text, update_ts, xtype)
values (10501, '字典查询', 3, 'system/dict/list*', null, 1, 105, 'icon icon-circle', null, to_date('10-08-2016', 'dd-mm-yyyy'), '0');
insert into T_AUTHORITY (res_id, res_name, res_type, res_url, other_res, orders, pid, iconclass, script_text, update_ts, xtype)
values (10502, '新增字典', 3, 'system/dict/add', null, 2, 105, 'icon icon-circle', null, to_date('10-08-2016', 'dd-mm-yyyy'), '0');
insert into T_AUTHORITY (res_id, res_name, res_type, res_url, other_res, orders, pid, iconclass, script_text, update_ts, xtype)
values (10503, '修改字典', 3, 'system/dict/edit', null, 3, 105, 'icon icon-circle', null, to_date('10-08-2016', 'dd-mm-yyyy'), '0');
insert into T_AUTHORITY (res_id, res_name, res_type, res_url, other_res, orders, pid, iconclass, script_text, update_ts, xtype)
values (10504, '删除字典', 3, 'system/dict/del', null, 4, 105, 'icon icon-circle', null, to_date('10-08-2016', 'dd-mm-yyyy'), '0');
insert into T_AUTHORITY (res_id, res_name, res_type, res_url, other_res, orders, pid, iconclass, script_text, update_ts, xtype)
values (10505, '加载字典', 3, 'system/dict/init', null, 5, 105, 'icon icon-circle', null, to_date('10-08-2016', 'dd-mm-yyyy'), '0');
insert into T_AUTHORITY (res_id, res_name, res_type, res_url, other_res, orders, pid, iconclass, script_text, update_ts, xtype)
values (30104, '查询产品分类', 3, 'product/categroy/list*', null, 4, 301, 'icon icon-cicle', null, to_date('13-09-2016', 'dd-mm-yyyy'), '0');
insert into T_AUTHORITY (res_id, res_name, res_type, res_url, other_res, orders, pid, iconclass, script_text, update_ts, xtype)
values (30303, '工厂查询', 3, 'factory/list*', null, 3, 303, 'icon icon-cicle', null, to_date('13-09-2016', 'dd-mm-yyyy'), '0');
insert into T_AUTHORITY (res_id, res_name, res_type, res_url, other_res, orders, pid, iconclass, script_text, update_ts, xtype)
values (30203, '查询物料', 3, 'product/list*', 'product/categroy/list*,product/series*,product/iPackage*,product/brand*', 3, 302, 'icon icon-cicle', null, to_date('13-09-2016', 'dd-mm-yyyy'), '0');
insert into T_AUTHORITY (res_id, res_name, res_type, res_url, other_res, orders, pid, iconclass, script_text, update_ts, xtype)
values (70101, '申请记录查询', 3, 'process/listMy*', null, 1, 701, 'icon  icon-desktop', null, to_date('10-08-2016', 'dd-mm-yyyy'), '0');
insert into T_AUTHORITY (res_id, res_name, res_type, res_url, other_res, orders, pid, iconclass, script_text, update_ts, xtype)
values (70102, '查看流程', 3, 'process/view?*', null, 2, 701, 'icon  icon-desktop', null, to_date('10-08-2016', 'dd-mm-yyyy'), '0');
insert into T_AUTHORITY (res_id, res_name, res_type, res_url, other_res, orders, pid, iconclass, script_text, update_ts, xtype)
values (20104, '查询组织架构', 3, 'Org/listPid*', null, 4, 201, 'icon icon-cicle', null, to_date('13-09-2016', 'dd-mm-yyyy'), '0');
commit;
prompt 200 records committed...
insert into T_AUTHORITY (res_id, res_name, res_type, res_url, other_res, orders, pid, iconclass, script_text, update_ts, xtype)
values (20304, '查询销售岗位', 3, 'station/list*', 'Org/listArea', 4, 203, 'icon icon-cicle', null, to_date('13-09-2016', 'dd-mm-yyyy'), '0');
insert into T_AUTHORITY (res_id, res_name, res_type, res_url, other_res, orders, pid, iconclass, script_text, update_ts, xtype)
values (20404, '查询职位', 3, 'jobstation/list*', null, 4, 204, 'iocn icon-cicle', null, to_date('13-09-2016', 'dd-mm-yyyy'), '0');
insert into T_AUTHORITY (res_id, res_name, res_type, res_url, other_res, orders, pid, iconclass, script_text, update_ts, xtype)
values (99990003, '个人中心', 3, 'userCenter/user.jhtml', 'userCenter/edit', 1, 9999, null, null, to_date('10-08-2016', 'dd-mm-yyyy'), '1');
insert into T_AUTHORITY (res_id, res_name, res_type, res_url, other_res, orders, pid, iconclass, script_text, update_ts, xtype)
values (99990004, '修改密码', 3, 'userCenter/modifyPwd.jhtml', 'userCenter/pwd.jhtml', 1, 9999, null, null, to_date('10-08-2016', 'dd-mm-yyyy'), '1');
insert into T_AUTHORITY (res_id, res_name, res_type, res_url, other_res, orders, pid, iconclass, script_text, update_ts, xtype)
values (30204, '产品详情', 3, 'product/attachment*', null, 4, 302, 'icon icon-cicle', null, to_date('13-09-2016', 'dd-mm-yyyy'), '0');
insert into T_AUTHORITY (res_id, res_name, res_type, res_url, other_res, orders, pid, iconclass, script_text, update_ts, xtype)
values (99990005, '查询地区', 3, 'pub/area/listChildren', null, 11, 9999, null, null, to_date('10-08-2016', 'dd-mm-yyyy'), '1');
insert into T_AUTHORITY (res_id, res_name, res_type, res_url, other_res, orders, pid, iconclass, script_text, update_ts, xtype)
values (40107, '指定岗位', 3, 'customer/apply', null, 7, 401, 'icon icon-circle', null, to_date('14-09-2016', 'dd-mm-yyyy'), '0');
insert into T_AUTHORITY (res_id, res_name, res_type, res_url, other_res, orders, pid, iconclass, script_text, update_ts, xtype)
values (40301, '客户产品价格查询', 3, 'customer/sku/list*', 'product/series*,product/iPackage*,product/brand*', 1, 403, 'icon icon-circle', null, to_date('10-08-2016', 'dd-mm-yyyy'), '0');
insert into T_AUTHORITY (res_id, res_name, res_type, res_url, other_res, orders, pid, iconclass, script_text, update_ts, xtype)
values (60601, '追加物流', 3, 'order/appendWL*', 'order/submitWL.html*', 1, 606, 'icon icon-circle', null, null, '0');
insert into T_AUTHORITY (res_id, res_name, res_type, res_url, other_res, orders, pid, iconclass, script_text, update_ts, xtype)
values (607, '特殊订单录入', 2, 'order/specialstartOrder.html', 'order/util/customer*,order/util/customerShip*,order/util/customerAccount*,order/util/custProduct*,order/addOrder*,order/util/validateNum*,order/orderAudit*', 7, 60, 'icon icon-search', null, to_date('14-10-2016', 'dd-mm-yyyy'), '0');
insert into T_AUTHORITY (res_id, res_name, res_type, res_url, other_res, orders, pid, iconclass, script_text, update_ts, xtype)
values (508, '资金上账查询', 2, 'account/upaccount/accountSearch.html', 'account/upaccount/upAccountsearchList*', 8, 50, 'icon icon-search', null, to_date('21-10-2016', 'dd-mm-yyyy'), '0');
insert into T_AUTHORITY (res_id, res_name, res_type, res_url, other_res, orders, pid, iconclass, script_text, update_ts, xtype)
values (40302, '客户产品价格维护', 3, 'customer/sku/edit*', null, 1, 403, 'icon icon-circle', null, to_date('10-08-2016', 'dd-mm-yyyy'), '0');
commit;