package com.hhnz.order.mapper;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import com.hhnz.order.model.OmOrderLogistics;
import com.hhnz.order.model.OmOrderLogisticsExample;

public interface OmOrderLogisticsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table OM_ORDER_LOGISTICS
     *
     * @mbggenerated Mon Aug 29 11:13:55 CST 2016
     */
    int countByExample(OmOrderLogisticsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table OM_ORDER_LOGISTICS
     *
     * @mbggenerated Mon Aug 29 11:13:55 CST 2016
     */
    int deleteByExample(OmOrderLogisticsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table OM_ORDER_LOGISTICS
     *
     * @mbggenerated Mon Aug 29 11:13:55 CST 2016
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table OM_ORDER_LOGISTICS
     *
     * @mbggenerated Mon Aug 29 11:13:55 CST 2016
     */
    int insert(OmOrderLogistics record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table OM_ORDER_LOGISTICS
     *
     * @mbggenerated Mon Aug 29 11:13:55 CST 2016
     */
    int insertSelective(OmOrderLogistics record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table OM_ORDER_LOGISTICS
     *
     * @mbggenerated Mon Aug 29 11:13:55 CST 2016
     */
    List<OmOrderLogistics> selectByExample(OmOrderLogisticsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table OM_ORDER_LOGISTICS
     *
     * @mbggenerated Mon Aug 29 11:13:55 CST 2016
     */
    OmOrderLogistics selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table OM_ORDER_LOGISTICS
     *
     * @mbggenerated Mon Aug 29 11:13:55 CST 2016
     */
    int updateByExampleSelective(@Param("record") OmOrderLogistics record, @Param("example") OmOrderLogisticsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table OM_ORDER_LOGISTICS
     *
     * @mbggenerated Mon Aug 29 11:13:55 CST 2016
     */
    int updateByExample(@Param("record") OmOrderLogistics record, @Param("example") OmOrderLogisticsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table OM_ORDER_LOGISTICS
     *
     * @mbggenerated Mon Aug 29 11:13:55 CST 2016
     */
    int updateByPrimaryKeySelective(OmOrderLogistics record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table OM_ORDER_LOGISTICS
     *
     * @mbggenerated Mon Aug 29 11:13:55 CST 2016
     */
    int updateByPrimaryKey(OmOrderLogistics record);
}