package com.hhnz.organization.mapper;

import com.hhnz.organization.model.CrmOrganizationInvoices;
import com.hhnz.organization.model.CrmOrganizationInvoicesExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CrmOrganizationInvoicesMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CRM_ORGANIZATION_INVOICES
     *
     * @mbggenerated Thu Jan 05 13:30:03 CST 2017
     */
    int countByExample(CrmOrganizationInvoicesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CRM_ORGANIZATION_INVOICES
     *
     * @mbggenerated Thu Jan 05 13:30:03 CST 2017
     */
    int deleteByExample(CrmOrganizationInvoicesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CRM_ORGANIZATION_INVOICES
     *
     * @mbggenerated Thu Jan 05 13:30:03 CST 2017
     */
    int deleteByPrimaryKey(String organizationId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CRM_ORGANIZATION_INVOICES
     *
     * @mbggenerated Thu Jan 05 13:30:03 CST 2017
     */
    int insert(CrmOrganizationInvoices record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CRM_ORGANIZATION_INVOICES
     *
     * @mbggenerated Thu Jan 05 13:30:03 CST 2017
     */
    int insertSelective(CrmOrganizationInvoices record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CRM_ORGANIZATION_INVOICES
     *
     * @mbggenerated Thu Jan 05 13:30:03 CST 2017
     */
    List<CrmOrganizationInvoices> selectByExample(CrmOrganizationInvoicesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CRM_ORGANIZATION_INVOICES
     *
     * @mbggenerated Thu Jan 05 13:30:03 CST 2017
     */
    CrmOrganizationInvoices selectByPrimaryKey(String organizationId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CRM_ORGANIZATION_INVOICES
     *
     * @mbggenerated Thu Jan 05 13:30:03 CST 2017
     */
    int updateByExampleSelective(@Param("record") CrmOrganizationInvoices record, @Param("example") CrmOrganizationInvoicesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CRM_ORGANIZATION_INVOICES
     *
     * @mbggenerated Thu Jan 05 13:30:03 CST 2017
     */
    int updateByExample(@Param("record") CrmOrganizationInvoices record, @Param("example") CrmOrganizationInvoicesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CRM_ORGANIZATION_INVOICES
     *
     * @mbggenerated Thu Jan 05 13:30:03 CST 2017
     */
    int updateByPrimaryKeySelective(CrmOrganizationInvoices record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CRM_ORGANIZATION_INVOICES
     *
     * @mbggenerated Thu Jan 05 13:30:03 CST 2017
     */
    int updateByPrimaryKey(CrmOrganizationInvoices record);
}