package com.hhnz.salepolicy.model;

import java.util.Date;

public class OmPolicyType {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column OM_POLICY_TYPE.ID
     *
     * @mbggenerated Thu Aug 18 13:51:49 CST 2016
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column OM_POLICY_TYPE.NAME
     *
     * @mbggenerated Thu Aug 18 13:51:49 CST 2016
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column OM_POLICY_TYPE.TYPE
     *
     * @mbggenerated Thu Aug 18 13:51:49 CST 2016
     */
    private String type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column OM_POLICY_TYPE.ASSESSMENT
     *
     * @mbggenerated Thu Aug 18 13:51:49 CST 2016
     */
    private String assessment;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column OM_POLICY_TYPE.ASSESSMENT_TARGET
     *
     * @mbggenerated Thu Aug 18 13:51:49 CST 2016
     */
    private String assessmentTarget;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column OM_POLICY_TYPE.BENCHMARK
     *
     * @mbggenerated Thu Aug 18 13:51:49 CST 2016
     */
    private String benchmark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column OM_POLICY_TYPE.VERIFICATION
     *
     * @mbggenerated Thu Aug 18 13:51:49 CST 2016
     */
    private String verification;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column OM_POLICY_TYPE.DESCRIPTION
     *
     * @mbggenerated Thu Aug 18 13:51:49 CST 2016
     */
    private String description;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column OM_POLICY_TYPE.CREATE_TS
     *
     * @mbggenerated Thu Aug 18 13:51:49 CST 2016
     */
    private Date createTs;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column OM_POLICY_TYPE.CREATE_OID
     *
     * @mbggenerated Thu Aug 18 13:51:49 CST 2016
     */
    private Long createOid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column OM_POLICY_TYPE.UPDATE_TS
     *
     * @mbggenerated Thu Aug 18 13:51:49 CST 2016
     */
    private Date updateTs;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column OM_POLICY_TYPE.UPDATE_OID
     *
     * @mbggenerated Thu Aug 18 13:51:49 CST 2016
     */
    private Long updateOid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column OM_POLICY_TYPE.AUDIT_TS
     *
     * @mbggenerated Thu Aug 18 13:51:49 CST 2016
     */
    private Date auditTs;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column OM_POLICY_TYPE.AUDIT_OID
     *
     * @mbggenerated Thu Aug 18 13:51:49 CST 2016
     */
    private Long auditOid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column OM_POLICY_TYPE.STATES
     *
     * @mbggenerated Thu Aug 18 13:51:49 CST 2016
     */
    private String states;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column OM_POLICY_TYPE.ID
     *
     * @return the value of OM_POLICY_TYPE.ID
     *
     * @mbggenerated Thu Aug 18 13:51:49 CST 2016
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column OM_POLICY_TYPE.ID
     *
     * @param id the value for OM_POLICY_TYPE.ID
     *
     * @mbggenerated Thu Aug 18 13:51:49 CST 2016
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column OM_POLICY_TYPE.NAME
     *
     * @return the value of OM_POLICY_TYPE.NAME
     *
     * @mbggenerated Thu Aug 18 13:51:49 CST 2016
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column OM_POLICY_TYPE.NAME
     *
     * @param name the value for OM_POLICY_TYPE.NAME
     *
     * @mbggenerated Thu Aug 18 13:51:49 CST 2016
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column OM_POLICY_TYPE.TYPE
     *
     * @return the value of OM_POLICY_TYPE.TYPE
     *
     * @mbggenerated Thu Aug 18 13:51:49 CST 2016
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column OM_POLICY_TYPE.TYPE
     *
     * @param type the value for OM_POLICY_TYPE.TYPE
     *
     * @mbggenerated Thu Aug 18 13:51:49 CST 2016
     */
    public void setType(String type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column OM_POLICY_TYPE.ASSESSMENT
     *
     * @return the value of OM_POLICY_TYPE.ASSESSMENT
     *
     * @mbggenerated Thu Aug 18 13:51:49 CST 2016
     */
    public String getAssessment() {
        return assessment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column OM_POLICY_TYPE.ASSESSMENT
     *
     * @param assessment the value for OM_POLICY_TYPE.ASSESSMENT
     *
     * @mbggenerated Thu Aug 18 13:51:49 CST 2016
     */
    public void setAssessment(String assessment) {
        this.assessment = assessment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column OM_POLICY_TYPE.ASSESSMENT_TARGET
     *
     * @return the value of OM_POLICY_TYPE.ASSESSMENT_TARGET
     *
     * @mbggenerated Thu Aug 18 13:51:49 CST 2016
     */
    public String getAssessmentTarget() {
        return assessmentTarget;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column OM_POLICY_TYPE.ASSESSMENT_TARGET
     *
     * @param assessmentTarget the value for OM_POLICY_TYPE.ASSESSMENT_TARGET
     *
     * @mbggenerated Thu Aug 18 13:51:49 CST 2016
     */
    public void setAssessmentTarget(String assessmentTarget) {
        this.assessmentTarget = assessmentTarget;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column OM_POLICY_TYPE.BENCHMARK
     *
     * @return the value of OM_POLICY_TYPE.BENCHMARK
     *
     * @mbggenerated Thu Aug 18 13:51:49 CST 2016
     */
    public String getBenchmark() {
        return benchmark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column OM_POLICY_TYPE.BENCHMARK
     *
     * @param benchmark the value for OM_POLICY_TYPE.BENCHMARK
     *
     * @mbggenerated Thu Aug 18 13:51:49 CST 2016
     */
    public void setBenchmark(String benchmark) {
        this.benchmark = benchmark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column OM_POLICY_TYPE.VERIFICATION
     *
     * @return the value of OM_POLICY_TYPE.VERIFICATION
     *
     * @mbggenerated Thu Aug 18 13:51:49 CST 2016
     */
    public String getVerification() {
        return verification;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column OM_POLICY_TYPE.VERIFICATION
     *
     * @param verification the value for OM_POLICY_TYPE.VERIFICATION
     *
     * @mbggenerated Thu Aug 18 13:51:49 CST 2016
     */
    public void setVerification(String verification) {
        this.verification = verification;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column OM_POLICY_TYPE.DESCRIPTION
     *
     * @return the value of OM_POLICY_TYPE.DESCRIPTION
     *
     * @mbggenerated Thu Aug 18 13:51:49 CST 2016
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column OM_POLICY_TYPE.DESCRIPTION
     *
     * @param description the value for OM_POLICY_TYPE.DESCRIPTION
     *
     * @mbggenerated Thu Aug 18 13:51:49 CST 2016
     */
    public void setDescription(String description) {
        this.description = description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column OM_POLICY_TYPE.CREATE_TS
     *
     * @return the value of OM_POLICY_TYPE.CREATE_TS
     *
     * @mbggenerated Thu Aug 18 13:51:49 CST 2016
     */
    public Date getCreateTs() {
        return createTs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column OM_POLICY_TYPE.CREATE_TS
     *
     * @param createTs the value for OM_POLICY_TYPE.CREATE_TS
     *
     * @mbggenerated Thu Aug 18 13:51:49 CST 2016
     */
    public void setCreateTs(Date createTs) {
        this.createTs = createTs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column OM_POLICY_TYPE.CREATE_OID
     *
     * @return the value of OM_POLICY_TYPE.CREATE_OID
     *
     * @mbggenerated Thu Aug 18 13:51:49 CST 2016
     */
    public Long getCreateOid() {
        return createOid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column OM_POLICY_TYPE.CREATE_OID
     *
     * @param createOid the value for OM_POLICY_TYPE.CREATE_OID
     *
     * @mbggenerated Thu Aug 18 13:51:49 CST 2016
     */
    public void setCreateOid(Long createOid) {
        this.createOid = createOid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column OM_POLICY_TYPE.UPDATE_TS
     *
     * @return the value of OM_POLICY_TYPE.UPDATE_TS
     *
     * @mbggenerated Thu Aug 18 13:51:49 CST 2016
     */
    public Date getUpdateTs() {
        return updateTs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column OM_POLICY_TYPE.UPDATE_TS
     *
     * @param updateTs the value for OM_POLICY_TYPE.UPDATE_TS
     *
     * @mbggenerated Thu Aug 18 13:51:49 CST 2016
     */
    public void setUpdateTs(Date updateTs) {
        this.updateTs = updateTs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column OM_POLICY_TYPE.UPDATE_OID
     *
     * @return the value of OM_POLICY_TYPE.UPDATE_OID
     *
     * @mbggenerated Thu Aug 18 13:51:49 CST 2016
     */
    public Long getUpdateOid() {
        return updateOid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column OM_POLICY_TYPE.UPDATE_OID
     *
     * @param updateOid the value for OM_POLICY_TYPE.UPDATE_OID
     *
     * @mbggenerated Thu Aug 18 13:51:49 CST 2016
     */
    public void setUpdateOid(Long updateOid) {
        this.updateOid = updateOid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column OM_POLICY_TYPE.AUDIT_TS
     *
     * @return the value of OM_POLICY_TYPE.AUDIT_TS
     *
     * @mbggenerated Thu Aug 18 13:51:49 CST 2016
     */
    public Date getAuditTs() {
        return auditTs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column OM_POLICY_TYPE.AUDIT_TS
     *
     * @param auditTs the value for OM_POLICY_TYPE.AUDIT_TS
     *
     * @mbggenerated Thu Aug 18 13:51:49 CST 2016
     */
    public void setAuditTs(Date auditTs) {
        this.auditTs = auditTs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column OM_POLICY_TYPE.AUDIT_OID
     *
     * @return the value of OM_POLICY_TYPE.AUDIT_OID
     *
     * @mbggenerated Thu Aug 18 13:51:49 CST 2016
     */
    public Long getAuditOid() {
        return auditOid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column OM_POLICY_TYPE.AUDIT_OID
     *
     * @param auditOid the value for OM_POLICY_TYPE.AUDIT_OID
     *
     * @mbggenerated Thu Aug 18 13:51:49 CST 2016
     */
    public void setAuditOid(Long auditOid) {
        this.auditOid = auditOid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column OM_POLICY_TYPE.STATES
     *
     * @return the value of OM_POLICY_TYPE.STATES
     *
     * @mbggenerated Thu Aug 18 13:51:49 CST 2016
     */
    public String getStates() {
        return states;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column OM_POLICY_TYPE.STATES
     *
     * @param states the value for OM_POLICY_TYPE.STATES
     *
     * @mbggenerated Thu Aug 18 13:51:49 CST 2016
     */
    public void setStates(String states) {
        this.states = states;
    }
}