package com.hhnz.salepolicy.model;

public class OmPolicyLinesAllV {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column OM_POLICY_LINES_ALL_V.HEADER_ID
     *
     * @mbggenerated Wed Aug 24 14:00:52 CST 2016
     */
    private Long headerId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column OM_POLICY_LINES_ALL_V.ID
     *
     * @mbggenerated Wed Aug 24 14:00:52 CST 2016
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column OM_POLICY_LINES_ALL_V.MATERIAL_ID
     *
     * @mbggenerated Wed Aug 24 14:00:52 CST 2016
     */
    private String materialId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column OM_POLICY_LINES_ALL_V.SKU
     *
     * @mbggenerated Wed Aug 24 14:00:52 CST 2016
     */
    private String sku;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column OM_POLICY_LINES_ALL_V.MATERIAL_NAME
     *
     * @mbggenerated Wed Aug 24 14:00:52 CST 2016
     */
    private String materialName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column OM_POLICY_LINES_ALL_V.UNIT
     *
     * @mbggenerated Wed Aug 24 14:00:52 CST 2016
     */
    private String unit;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column OM_POLICY_LINES_ALL_V.PRICE
     *
     * @mbggenerated Wed Aug 24 14:00:52 CST 2016
     */
    private Long price;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column OM_POLICY_LINES_ALL_V.VERIFICATION
     *
     * @mbggenerated Wed Aug 24 14:00:52 CST 2016
     */
    private String verification;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column OM_POLICY_LINES_ALL_V.PRIMARY
     *
     * @mbggenerated Wed Aug 24 14:00:52 CST 2016
     */
    private String primary;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column OM_POLICY_LINES_ALL_V.DISCOUNT
     *
     * @mbggenerated Wed Aug 24 14:00:52 CST 2016
     */
    private String discount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column OM_POLICY_LINES_ALL_V.DISCOUNTSKU
     *
     * @mbggenerated Wed Aug 24 14:00:52 CST 2016
     */
    private String discountsku;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column OM_POLICY_LINES_ALL_V.LIMIT
     *
     * @mbggenerated Wed Aug 24 14:00:52 CST 2016
     */
    private String limit;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column OM_POLICY_LINES_ALL_V.DISCOUNT_INTENSITY
     *
     * @mbggenerated Wed Aug 24 14:00:52 CST 2016
     */
    private String discountIntensity;
    

	/**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column OM_POLICY_LINES_ALL_V.HEADER_ID
     *
     * @return the value of OM_POLICY_LINES_ALL_V.HEADER_ID
     *
     * @mbggenerated Wed Aug 24 14:00:52 CST 2016
     */
    public Long getHeaderId() {
        return headerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column OM_POLICY_LINES_ALL_V.HEADER_ID
     *
     * @param headerId the value for OM_POLICY_LINES_ALL_V.HEADER_ID
     *
     * @mbggenerated Wed Aug 24 14:00:52 CST 2016
     */
    public void setHeaderId(Long headerId) {
        this.headerId = headerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column OM_POLICY_LINES_ALL_V.ID
     *
     * @return the value of OM_POLICY_LINES_ALL_V.ID
     *
     * @mbggenerated Wed Aug 24 14:00:52 CST 2016
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column OM_POLICY_LINES_ALL_V.ID
     *
     * @param id the value for OM_POLICY_LINES_ALL_V.ID
     *
     * @mbggenerated Wed Aug 24 14:00:52 CST 2016
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column OM_POLICY_LINES_ALL_V.MATERIAL_ID
     *
     * @return the value of OM_POLICY_LINES_ALL_V.MATERIAL_ID
     *
     * @mbggenerated Wed Aug 24 14:00:52 CST 2016
     */
    public String getMaterialId() {
        return materialId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column OM_POLICY_LINES_ALL_V.MATERIAL_ID
     *
     * @param materialId the value for OM_POLICY_LINES_ALL_V.MATERIAL_ID
     *
     * @mbggenerated Wed Aug 24 14:00:52 CST 2016
     */
    public void setMaterialId(String materialId) {
        this.materialId = materialId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column OM_POLICY_LINES_ALL_V.SKU
     *
     * @return the value of OM_POLICY_LINES_ALL_V.SKU
     *
     * @mbggenerated Wed Aug 24 14:00:52 CST 2016
     */
    public String getSku() {
        return sku;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column OM_POLICY_LINES_ALL_V.SKU
     *
     * @param sku the value for OM_POLICY_LINES_ALL_V.SKU
     *
     * @mbggenerated Wed Aug 24 14:00:52 CST 2016
     */
    public void setSku(String sku) {
        this.sku = sku;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column OM_POLICY_LINES_ALL_V.MATERIAL_NAME
     *
     * @return the value of OM_POLICY_LINES_ALL_V.MATERIAL_NAME
     *
     * @mbggenerated Wed Aug 24 14:00:52 CST 2016
     */
    public String getMaterialName() {
        return materialName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column OM_POLICY_LINES_ALL_V.MATERIAL_NAME
     *
     * @param materialName the value for OM_POLICY_LINES_ALL_V.MATERIAL_NAME
     *
     * @mbggenerated Wed Aug 24 14:00:52 CST 2016
     */
    public void setMaterialName(String materialName) {
        this.materialName = materialName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column OM_POLICY_LINES_ALL_V.UNIT
     *
     * @return the value of OM_POLICY_LINES_ALL_V.UNIT
     *
     * @mbggenerated Wed Aug 24 14:00:52 CST 2016
     */
    public String getUnit() {
        return unit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column OM_POLICY_LINES_ALL_V.UNIT
     *
     * @param unit the value for OM_POLICY_LINES_ALL_V.UNIT
     *
     * @mbggenerated Wed Aug 24 14:00:52 CST 2016
     */
    public void setUnit(String unit) {
        this.unit = unit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column OM_POLICY_LINES_ALL_V.PRICE
     *
     * @return the value of OM_POLICY_LINES_ALL_V.PRICE
     *
     * @mbggenerated Wed Aug 24 14:00:52 CST 2016
     */
    public Long getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column OM_POLICY_LINES_ALL_V.PRICE
     *
     * @param price the value for OM_POLICY_LINES_ALL_V.PRICE
     *
     * @mbggenerated Wed Aug 24 14:00:52 CST 2016
     */
    public void setPrice(Long price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column OM_POLICY_LINES_ALL_V.VERIFICATION
     *
     * @return the value of OM_POLICY_LINES_ALL_V.VERIFICATION
     *
     * @mbggenerated Wed Aug 24 14:00:52 CST 2016
     */
    public String getVerification() {
        return verification;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column OM_POLICY_LINES_ALL_V.VERIFICATION
     *
     * @param verification the value for OM_POLICY_LINES_ALL_V.VERIFICATION
     *
     * @mbggenerated Wed Aug 24 14:00:52 CST 2016
     */
    public void setVerification(String verification) {
        this.verification = verification;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column OM_POLICY_LINES_ALL_V.PRIMARY
     *
     * @return the value of OM_POLICY_LINES_ALL_V.PRIMARY
     *
     * @mbggenerated Wed Aug 24 14:00:52 CST 2016
     */
    public String getPrimary() {
        return primary;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column OM_POLICY_LINES_ALL_V.PRIMARY
     *
     * @param primary the value for OM_POLICY_LINES_ALL_V.PRIMARY
     *
     * @mbggenerated Wed Aug 24 14:00:52 CST 2016
     */
    public void setPrimary(String primary) {
        this.primary = primary;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column OM_POLICY_LINES_ALL_V.DISCOUNT
     *
     * @return the value of OM_POLICY_LINES_ALL_V.DISCOUNT
     *
     * @mbggenerated Wed Aug 24 14:00:52 CST 2016
     */
    public String getDiscount() {
        return discount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column OM_POLICY_LINES_ALL_V.DISCOUNT
     *
     * @param discount the value for OM_POLICY_LINES_ALL_V.DISCOUNT
     *
     * @mbggenerated Wed Aug 24 14:00:52 CST 2016
     */
    public void setDiscount(String discount) {
        this.discount = discount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column OM_POLICY_LINES_ALL_V.DISCOUNTSKU
     *
     * @return the value of OM_POLICY_LINES_ALL_V.DISCOUNTSKU
     *
     * @mbggenerated Wed Aug 24 14:00:52 CST 2016
     */
    public String getDiscountsku() {
        return discountsku;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column OM_POLICY_LINES_ALL_V.DISCOUNTSKU
     *
     * @param discountsku the value for OM_POLICY_LINES_ALL_V.DISCOUNTSKU
     *
     * @mbggenerated Wed Aug 24 14:00:52 CST 2016
     */
    public void setDiscountsku(String discountsku) {
        this.discountsku = discountsku;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column OM_POLICY_LINES_ALL_V.LIMIT
     *
     * @return the value of OM_POLICY_LINES_ALL_V.LIMIT
     *
     * @mbggenerated Wed Aug 24 14:00:52 CST 2016
     */
    public String getLimit() {
        return limit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column OM_POLICY_LINES_ALL_V.LIMIT
     *
     * @param limit the value for OM_POLICY_LINES_ALL_V.LIMIT
     *
     * @mbggenerated Wed Aug 24 14:00:52 CST 2016
     */
    public void setLimit(String limit) {
        this.limit = limit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column OM_POLICY_LINES_ALL_V.DISCOUNT_INTENSITY
     *
     * @return the value of OM_POLICY_LINES_ALL_V.DISCOUNT_INTENSITY
     *
     * @mbggenerated Wed Aug 24 14:00:52 CST 2016
     */
    public String getDiscountIntensity() {
        return discountIntensity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column OM_POLICY_LINES_ALL_V.DISCOUNT_INTENSITY
     *
     * @param discountIntensity the value for OM_POLICY_LINES_ALL_V.DISCOUNT_INTENSITY
     *
     * @mbggenerated Wed Aug 24 14:00:52 CST 2016
     */
    public void setDiscountIntensity(String discountIntensity) {
        this.discountIntensity = discountIntensity;
    }
}