package com.hhnz.customerInv.mapper;

import com.hhnz.customerInv.model.CMerchCustProductLog;
import com.hhnz.customerInv.model.CMerchCustProductLogExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CMerchCustProductLogMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table C_MERCH_CUST_PRODUCT_LOG
     *
     * @mbggenerated Tue Dec 13 14:55:50 CST 2016
     */
    int countByExample(CMerchCustProductLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table C_MERCH_CUST_PRODUCT_LOG
     *
     * @mbggenerated Tue Dec 13 14:55:50 CST 2016
     */
    int deleteByExample(CMerchCustProductLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table C_MERCH_CUST_PRODUCT_LOG
     *
     * @mbggenerated Tue Dec 13 14:55:50 CST 2016
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table C_MERCH_CUST_PRODUCT_LOG
     *
     * @mbggenerated Tue Dec 13 14:55:50 CST 2016
     */
    int insert(CMerchCustProductLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table C_MERCH_CUST_PRODUCT_LOG
     *
     * @mbggenerated Tue Dec 13 14:55:50 CST 2016
     */
    int insertSelective(CMerchCustProductLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table C_MERCH_CUST_PRODUCT_LOG
     *
     * @mbggenerated Tue Dec 13 14:55:50 CST 2016
     */
    List<CMerchCustProductLog> selectByExample(CMerchCustProductLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table C_MERCH_CUST_PRODUCT_LOG
     *
     * @mbggenerated Tue Dec 13 14:55:50 CST 2016
     */
    CMerchCustProductLog selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table C_MERCH_CUST_PRODUCT_LOG
     *
     * @mbggenerated Tue Dec 13 14:55:50 CST 2016
     */
    int updateByExampleSelective(@Param("record") CMerchCustProductLog record, @Param("example") CMerchCustProductLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table C_MERCH_CUST_PRODUCT_LOG
     *
     * @mbggenerated Tue Dec 13 14:55:50 CST 2016
     */
    int updateByExample(@Param("record") CMerchCustProductLog record, @Param("example") CMerchCustProductLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table C_MERCH_CUST_PRODUCT_LOG
     *
     * @mbggenerated Tue Dec 13 14:55:50 CST 2016
     */
    int updateByPrimaryKeySelective(CMerchCustProductLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table C_MERCH_CUST_PRODUCT_LOG
     *
     * @mbggenerated Tue Dec 13 14:55:50 CST 2016
     */
    int updateByPrimaryKey(CMerchCustProductLog record);
}