package com.hhnz.cost.mapper;

import com.hhnz.cost.model.CrmCostMain;
import com.hhnz.cost.model.CrmCostMainExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CrmCostMainMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CRM_COST_MAIN
     *
     * @mbggenerated Mon Sep 26 16:32:22 CST 2016
     */
    int countByExample(CrmCostMainExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CRM_COST_MAIN
     *
     * @mbggenerated Mon Sep 26 16:32:22 CST 2016
     */
    int deleteByExample(CrmCostMainExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CRM_COST_MAIN
     *
     * @mbggenerated Mon Sep 26 16:32:22 CST 2016
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CRM_COST_MAIN
     *
     * @mbggenerated Mon Sep 26 16:32:22 CST 2016
     */
    int insert(CrmCostMain record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CRM_COST_MAIN
     *
     * @mbggenerated Mon Sep 26 16:32:22 CST 2016
     */
    int insertSelective(CrmCostMain record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CRM_COST_MAIN
     *
     * @mbggenerated Mon Sep 26 16:32:22 CST 2016
     */
    List<CrmCostMain> selectByExample(CrmCostMainExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CRM_COST_MAIN
     *
     * @mbggenerated Mon Sep 26 16:32:22 CST 2016
     */
    CrmCostMain selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CRM_COST_MAIN
     *
     * @mbggenerated Mon Sep 26 16:32:22 CST 2016
     */
    int updateByExampleSelective(@Param("record") CrmCostMain record, @Param("example") CrmCostMainExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CRM_COST_MAIN
     *
     * @mbggenerated Mon Sep 26 16:32:22 CST 2016
     */
    int updateByExample(@Param("record") CrmCostMain record, @Param("example") CrmCostMainExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CRM_COST_MAIN
     *
     * @mbggenerated Mon Sep 26 16:32:22 CST 2016
     */
    int updateByPrimaryKeySelective(CrmCostMain record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CRM_COST_MAIN
     *
     * @mbggenerated Mon Sep 26 16:32:22 CST 2016
     */
    int updateByPrimaryKey(CrmCostMain record);
}