package com.hhnz.crm.mapper;

import com.hhnz.crm.model.TRole;
import com.hhnz.crm.model.TRoleExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.ResultMap;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;

public interface TRoleMapper {
    /**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table T_ROLE
	 * @mbggenerated
	 */
	int countByExample(TRoleExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table T_ROLE
	 * @mbggenerated
	 */
	int deleteByExample(TRoleExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table T_ROLE
	 * @mbggenerated
	 */
	@Delete({ "delete from T_ROLE", "where ID = #{id,jdbcType=DECIMAL}" })
	int deleteByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table T_ROLE
	 * @mbggenerated
	 */
	@Insert({ "insert into T_ROLE (ID, ROLE_NAME, ", "ROLE_DESC, CREATE_TS, ", "UPDATE_TS, ROLE_TYPE)",
			"values (seq_role_id.nextval, #{roleName,jdbcType=VARCHAR}, ",
			"#{roleDesc,jdbcType=VARCHAR}, #{createTs,jdbcType=TIMESTAMP}, ",
			"#{updateTs,jdbcType=TIMESTAMP}, #{roleType,jdbcType=VARCHAR})" })
	int insert(TRole record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table T_ROLE
	 * @mbggenerated
	 */
	int insertSelective(TRole record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table T_ROLE
	 * @mbggenerated
	 */
	List<TRole> selectByExample(TRoleExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table T_ROLE
	 * @mbggenerated
	 */
	@Select({ "select", "ID, ROLE_NAME, ROLE_DESC, CREATE_TS, UPDATE_TS, ROLE_TYPE", "from T_ROLE",
			"where ID = #{id,jdbcType=DECIMAL}" })
	@ResultMap("BaseResultMap")
	TRole selectByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table T_ROLE
	 * @mbggenerated
	 */
	int updateByExampleSelective(@Param("record") TRole record, @Param("example") TRoleExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table T_ROLE
	 * @mbggenerated
	 */
	int updateByExample(@Param("record") TRole record, @Param("example") TRoleExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table T_ROLE
	 * @mbggenerated
	 */
	int updateByPrimaryKeySelective(TRole record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table T_ROLE
	 * @mbggenerated
	 */
	@Update({ "update T_ROLE", "set ROLE_NAME = #{roleName,jdbcType=VARCHAR},",
			"ROLE_DESC = #{roleDesc,jdbcType=VARCHAR},", "CREATE_TS = #{createTs,jdbcType=TIMESTAMP},",
			"UPDATE_TS = #{updateTs,jdbcType=TIMESTAMP},", "ROLE_TYPE = #{roleType,jdbcType=VARCHAR}",
			"where ID = #{id,jdbcType=DECIMAL}" })
	int updateByPrimaryKey(TRole record);

	List<Long> selectAuthsOfRole(@Param("id") Long id);

	@Select("select count(*) from t_employee where role_id = #{id}")
    int countRoleUser(@Param("id") Long id);
}