package com.hhnz.process.model;

import java.math.BigDecimal;
import java.util.Date;

public class VProcess {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column V_PROCESS.DEF_NAME
     *
     * @mbggenerated Mon Jul 11 22:01:21 CST 2016
     */
    private Object defName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column V_PROCESS.ID_
     *
     * @mbggenerated Mon Jul 11 22:01:21 CST 2016
     */
    private Object id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column V_PROCESS.PROC_INST_ID_
     *
     * @mbggenerated Mon Jul 11 22:01:21 CST 2016
     */
    private Object procInstId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column V_PROCESS.BUSINESS_KEY_
     *
     * @mbggenerated Mon Jul 11 22:01:21 CST 2016
     */
    private Object businessKey;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column V_PROCESS.PROC_DEF_ID_
     *
     * @mbggenerated Mon Jul 11 22:01:21 CST 2016
     */
    private Object procDefId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column V_PROCESS.START_TIME_
     *
     * @mbggenerated Mon Jul 11 22:01:21 CST 2016
     */
    private Date startTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column V_PROCESS.END_TIME_
     *
     * @mbggenerated Mon Jul 11 22:01:21 CST 2016
     */
    private Date endTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column V_PROCESS.DURATION_
     *
     * @mbggenerated Mon Jul 11 22:01:21 CST 2016
     */
    private BigDecimal duration;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column V_PROCESS.START_USER_ID_
     *
     * @mbggenerated Mon Jul 11 22:01:21 CST 2016
     */
    private Object startUserId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column V_PROCESS.START_ACT_ID_
     *
     * @mbggenerated Mon Jul 11 22:01:21 CST 2016
     */
    private Object startActId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column V_PROCESS.END_ACT_ID_
     *
     * @mbggenerated Mon Jul 11 22:01:21 CST 2016
     */
    private Object endActId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column V_PROCESS.SUPER_PROCESS_INSTANCE_ID_
     *
     * @mbggenerated Mon Jul 11 22:01:21 CST 2016
     */
    private Object superProcessInstanceId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column V_PROCESS.DELETE_REASON_
     *
     * @mbggenerated Mon Jul 11 22:01:21 CST 2016
     */
    private Object deleteReason;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column V_PROCESS.TENANT_ID_
     *
     * @mbggenerated Mon Jul 11 22:01:21 CST 2016
     */
    private Object tenantId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column V_PROCESS.NAME_
     *
     * @mbggenerated Mon Jul 11 22:01:21 CST 2016
     */
    private Object name;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column V_PROCESS.DEF_NAME
     *
     * @return the value of V_PROCESS.DEF_NAME
     *
     * @mbggenerated Mon Jul 11 22:01:21 CST 2016
     */
    public Object getDefName() {
        return defName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column V_PROCESS.DEF_NAME
     *
     * @param defName the value for V_PROCESS.DEF_NAME
     *
     * @mbggenerated Mon Jul 11 22:01:21 CST 2016
     */
    public void setDefName(Object defName) {
        this.defName = defName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column V_PROCESS.ID_
     *
     * @return the value of V_PROCESS.ID_
     *
     * @mbggenerated Mon Jul 11 22:01:21 CST 2016
     */
    public Object getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column V_PROCESS.ID_
     *
     * @param id the value for V_PROCESS.ID_
     *
     * @mbggenerated Mon Jul 11 22:01:21 CST 2016
     */
    public void setId(Object id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column V_PROCESS.PROC_INST_ID_
     *
     * @return the value of V_PROCESS.PROC_INST_ID_
     *
     * @mbggenerated Mon Jul 11 22:01:21 CST 2016
     */
    public Object getProcInstId() {
        return procInstId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column V_PROCESS.PROC_INST_ID_
     *
     * @param procInstId the value for V_PROCESS.PROC_INST_ID_
     *
     * @mbggenerated Mon Jul 11 22:01:21 CST 2016
     */
    public void setProcInstId(Object procInstId) {
        this.procInstId = procInstId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column V_PROCESS.BUSINESS_KEY_
     *
     * @return the value of V_PROCESS.BUSINESS_KEY_
     *
     * @mbggenerated Mon Jul 11 22:01:21 CST 2016
     */
    public Object getBusinessKey() {
        return businessKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column V_PROCESS.BUSINESS_KEY_
     *
     * @param businessKey the value for V_PROCESS.BUSINESS_KEY_
     *
     * @mbggenerated Mon Jul 11 22:01:21 CST 2016
     */
    public void setBusinessKey(Object businessKey) {
        this.businessKey = businessKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column V_PROCESS.PROC_DEF_ID_
     *
     * @return the value of V_PROCESS.PROC_DEF_ID_
     *
     * @mbggenerated Mon Jul 11 22:01:21 CST 2016
     */
    public Object getProcDefId() {
        return procDefId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column V_PROCESS.PROC_DEF_ID_
     *
     * @param procDefId the value for V_PROCESS.PROC_DEF_ID_
     *
     * @mbggenerated Mon Jul 11 22:01:21 CST 2016
     */
    public void setProcDefId(Object procDefId) {
        this.procDefId = procDefId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column V_PROCESS.START_TIME_
     *
     * @return the value of V_PROCESS.START_TIME_
     *
     * @mbggenerated Mon Jul 11 22:01:21 CST 2016
     */
    public Date getStartTime() {
        return startTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column V_PROCESS.START_TIME_
     *
     * @param startTime the value for V_PROCESS.START_TIME_
     *
     * @mbggenerated Mon Jul 11 22:01:21 CST 2016
     */
    public void setStartTime(Date startTime) {
        this.startTime = startTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column V_PROCESS.END_TIME_
     *
     * @return the value of V_PROCESS.END_TIME_
     *
     * @mbggenerated Mon Jul 11 22:01:21 CST 2016
     */
    public Date getEndTime() {
        return endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column V_PROCESS.END_TIME_
     *
     * @param endTime the value for V_PROCESS.END_TIME_
     *
     * @mbggenerated Mon Jul 11 22:01:21 CST 2016
     */
    public void setEndTime(Date endTime) {
        this.endTime = endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column V_PROCESS.DURATION_
     *
     * @return the value of V_PROCESS.DURATION_
     *
     * @mbggenerated Mon Jul 11 22:01:21 CST 2016
     */
    public BigDecimal getDuration() {
        return duration;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column V_PROCESS.DURATION_
     *
     * @param duration the value for V_PROCESS.DURATION_
     *
     * @mbggenerated Mon Jul 11 22:01:21 CST 2016
     */
    public void setDuration(BigDecimal duration) {
        this.duration = duration;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column V_PROCESS.START_USER_ID_
     *
     * @return the value of V_PROCESS.START_USER_ID_
     *
     * @mbggenerated Mon Jul 11 22:01:21 CST 2016
     */
    public Object getStartUserId() {
        return startUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column V_PROCESS.START_USER_ID_
     *
     * @param startUserId the value for V_PROCESS.START_USER_ID_
     *
     * @mbggenerated Mon Jul 11 22:01:21 CST 2016
     */
    public void setStartUserId(Object startUserId) {
        this.startUserId = startUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column V_PROCESS.START_ACT_ID_
     *
     * @return the value of V_PROCESS.START_ACT_ID_
     *
     * @mbggenerated Mon Jul 11 22:01:21 CST 2016
     */
    public Object getStartActId() {
        return startActId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column V_PROCESS.START_ACT_ID_
     *
     * @param startActId the value for V_PROCESS.START_ACT_ID_
     *
     * @mbggenerated Mon Jul 11 22:01:21 CST 2016
     */
    public void setStartActId(Object startActId) {
        this.startActId = startActId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column V_PROCESS.END_ACT_ID_
     *
     * @return the value of V_PROCESS.END_ACT_ID_
     *
     * @mbggenerated Mon Jul 11 22:01:21 CST 2016
     */
    public Object getEndActId() {
        return endActId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column V_PROCESS.END_ACT_ID_
     *
     * @param endActId the value for V_PROCESS.END_ACT_ID_
     *
     * @mbggenerated Mon Jul 11 22:01:21 CST 2016
     */
    public void setEndActId(Object endActId) {
        this.endActId = endActId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column V_PROCESS.SUPER_PROCESS_INSTANCE_ID_
     *
     * @return the value of V_PROCESS.SUPER_PROCESS_INSTANCE_ID_
     *
     * @mbggenerated Mon Jul 11 22:01:21 CST 2016
     */
    public Object getSuperProcessInstanceId() {
        return superProcessInstanceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column V_PROCESS.SUPER_PROCESS_INSTANCE_ID_
     *
     * @param superProcessInstanceId the value for V_PROCESS.SUPER_PROCESS_INSTANCE_ID_
     *
     * @mbggenerated Mon Jul 11 22:01:21 CST 2016
     */
    public void setSuperProcessInstanceId(Object superProcessInstanceId) {
        this.superProcessInstanceId = superProcessInstanceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column V_PROCESS.DELETE_REASON_
     *
     * @return the value of V_PROCESS.DELETE_REASON_
     *
     * @mbggenerated Mon Jul 11 22:01:21 CST 2016
     */
    public Object getDeleteReason() {
        return deleteReason;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column V_PROCESS.DELETE_REASON_
     *
     * @param deleteReason the value for V_PROCESS.DELETE_REASON_
     *
     * @mbggenerated Mon Jul 11 22:01:21 CST 2016
     */
    public void setDeleteReason(Object deleteReason) {
        this.deleteReason = deleteReason;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column V_PROCESS.TENANT_ID_
     *
     * @return the value of V_PROCESS.TENANT_ID_
     *
     * @mbggenerated Mon Jul 11 22:01:21 CST 2016
     */
    public Object getTenantId() {
        return tenantId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column V_PROCESS.TENANT_ID_
     *
     * @param tenantId the value for V_PROCESS.TENANT_ID_
     *
     * @mbggenerated Mon Jul 11 22:01:21 CST 2016
     */
    public void setTenantId(Object tenantId) {
        this.tenantId = tenantId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column V_PROCESS.NAME_
     *
     * @return the value of V_PROCESS.NAME_
     *
     * @mbggenerated Mon Jul 11 22:01:21 CST 2016
     */
    public Object getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column V_PROCESS.NAME_
     *
     * @param name the value for V_PROCESS.NAME_
     *
     * @mbggenerated Mon Jul 11 22:01:21 CST 2016
     */
    public void setName(Object name) {
        this.name = name;
    }
}