package com.hhnz.crm.mapper;

import com.hhnz.crm.model.TNotes;
import com.hhnz.crm.model.TNotesExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TNotesMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_NOTES
     *
     * @mbggenerated Mon Jul 25 15:22:06 CST 2016
     */
    int countByExample(TNotesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_NOTES
     *
     * @mbggenerated Mon Jul 25 15:22:06 CST 2016
     */
    int deleteByExample(TNotesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_NOTES
     *
     * @mbggenerated Mon Jul 25 15:22:06 CST 2016
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_NOTES
     *
     * @mbggenerated Mon Jul 25 15:22:06 CST 2016
     */
    int insert(TNotes record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_NOTES
     *
     * @mbggenerated Mon Jul 25 15:22:06 CST 2016
     */
    int insertSelective(TNotes record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_NOTES
     *
     * @mbggenerated Mon Jul 25 15:22:06 CST 2016
     */
    List<TNotes> selectByExampleWithBLOBs(TNotesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_NOTES
     *
     * @mbggenerated Mon Jul 25 15:22:06 CST 2016
     */
    List<TNotes> selectByExample(TNotesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_NOTES
     *
     * @mbggenerated Mon Jul 25 15:22:06 CST 2016
     */
    TNotes selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_NOTES
     *
     * @mbggenerated Mon Jul 25 15:22:06 CST 2016
     */
    int updateByExampleSelective(@Param("record") TNotes record, @Param("example") TNotesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_NOTES
     *
     * @mbggenerated Mon Jul 25 15:22:06 CST 2016
     */
    int updateByExampleWithBLOBs(@Param("record") TNotes record, @Param("example") TNotesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_NOTES
     *
     * @mbggenerated Mon Jul 25 15:22:06 CST 2016
     */
    int updateByExample(@Param("record") TNotes record, @Param("example") TNotesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_NOTES
     *
     * @mbggenerated Mon Jul 25 15:22:06 CST 2016
     */
    int updateByPrimaryKeySelective(TNotes record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_NOTES
     *
     * @mbggenerated Mon Jul 25 15:22:06 CST 2016
     */
    int updateByPrimaryKeyWithBLOBs(TNotes record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_NOTES
     *
     * @mbggenerated Mon Jul 25 15:22:06 CST 2016
     */
    int updateByPrimaryKey(TNotes record);
}