package com.hhnz.organization.mapper;

import com.hhnz.organization.model.TJobStation;
import com.hhnz.organization.model.TJobStationExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Select;

public interface TJobStationMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_JOB_STATION
     *
     * @mbggenerated Tue Aug 02 16:42:28 CST 2016
     */
    int countByExample(TJobStationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_JOB_STATION
     *
     * @mbggenerated Tue Aug 02 16:42:28 CST 2016
     */
    int deleteByExample(TJobStationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_JOB_STATION
     *
     * @mbggenerated Tue Aug 02 16:42:28 CST 2016
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_JOB_STATION
     *
     * @mbggenerated Tue Aug 02 16:42:28 CST 2016
     */
    int insert(TJobStation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_JOB_STATION
     *
     * @mbggenerated Tue Aug 02 16:42:28 CST 2016
     */
    int insertSelective(TJobStation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_JOB_STATION
     *
     * @mbggenerated Tue Aug 02 16:42:28 CST 2016
     */
    List<TJobStation> selectByExample(TJobStationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_JOB_STATION
     *
     * @mbggenerated Tue Aug 02 16:42:28 CST 2016
     */
    TJobStation selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_JOB_STATION
     *
     * @mbggenerated Tue Aug 02 16:42:28 CST 2016
     */
    int updateByExampleSelective(@Param("record") TJobStation record, @Param("example") TJobStationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_JOB_STATION
     *
     * @mbggenerated Tue Aug 02 16:42:28 CST 2016
     */
    int updateByExample(@Param("record") TJobStation record, @Param("example") TJobStationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_JOB_STATION
     *
     * @mbggenerated Tue Aug 02 16:42:28 CST 2016
     */
    int updateByPrimaryKeySelective(TJobStation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_JOB_STATION
     *
     * @mbggenerated Tue Aug 02 16:42:28 CST 2016
     */
    int updateByPrimaryKey(TJobStation record);


    @Select("SELECT org_id||name FROM t_job_station where name =#{name} and org_id in (select id from crm_sales_organization start with id = #{id} connect by prior pid = id) and job_type=2 order by length(org_id) desc")
    List<String> findJobNamesById(@Param("id") String id,@Param("name") String name);
}