package com.hhnz.organization.model;

import java.util.Date;

public class TJobUserV {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_JOB_USER_V.STATIONNAME
     *
     * @mbggenerated Thu Aug 04 14:42:02 CST 2016
     */
    private String stationname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_JOB_USER_V.JOB_ID
     *
     * @mbggenerated Thu Aug 04 14:42:02 CST 2016
     */
    private String jobId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_JOB_USER_V.EMP_ID
     *
     * @mbggenerated Thu Aug 04 14:42:02 CST 2016
     */
    private Long empId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_JOB_USER_V.ID
     *
     * @mbggenerated Thu Aug 04 14:42:02 CST 2016
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_JOB_USER_V.NAME
     *
     * @mbggenerated Thu Aug 04 14:42:02 CST 2016
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_JOB_USER_V.PID
     *
     * @mbggenerated Thu Aug 04 14:42:02 CST 2016
     */
    private Long pid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_JOB_USER_V.IS_SALESMAN
     *
     * @mbggenerated Thu Aug 04 14:42:02 CST 2016
     */
    private String isSalesman;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_JOB_USER_V.CARD_NO
     *
     * @mbggenerated Thu Aug 04 14:42:02 CST 2016
     */
    private String cardNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_JOB_USER_V.CARD_ADDRESS
     *
     * @mbggenerated Thu Aug 04 14:42:02 CST 2016
     */
    private String cardAddress;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_JOB_USER_V.CONTACT_ADDRESS
     *
     * @mbggenerated Thu Aug 04 14:42:02 CST 2016
     */
    private String contactAddress;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_JOB_USER_V.CONTACT_TEL
     *
     * @mbggenerated Thu Aug 04 14:42:02 CST 2016
     */
    private String contactTel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_JOB_USER_V.CREATE_TS
     *
     * @mbggenerated Thu Aug 04 14:42:02 CST 2016
     */
    private Date createTs;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_JOB_USER_V.ENTRY_TS
     *
     * @mbggenerated Thu Aug 04 14:42:02 CST 2016
     */
    private Date entryTs;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_JOB_USER_V.QUIT_TS
     *
     * @mbggenerated Thu Aug 04 14:42:02 CST 2016
     */
    private Date quitTs;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_JOB_USER_V.STATES
     *
     * @mbggenerated Thu Aug 04 14:42:02 CST 2016
     */
    private String states;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_JOB_USER_V.LOGIN_NAME
     *
     * @mbggenerated Thu Aug 04 14:42:02 CST 2016
     */
    private String loginName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_JOB_USER_V.PASSWD
     *
     * @mbggenerated Thu Aug 04 14:42:02 CST 2016
     */
    private String passwd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_JOB_USER_V.EXP_DATE
     *
     * @mbggenerated Thu Aug 04 14:42:02 CST 2016
     */
    private Date expDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_JOB_USER_V.LASTUPDATES
     *
     * @mbggenerated Thu Aug 04 14:42:02 CST 2016
     */
    private Date lastupdates;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_JOB_USER_V.PWD_ERROR_COUNT
     *
     * @mbggenerated Thu Aug 04 14:42:02 CST 2016
     */
    private String pwdErrorCount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_JOB_USER_V.LOGIN_TS
     *
     * @mbggenerated Thu Aug 04 14:42:02 CST 2016
     */
    private Date loginTs;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_JOB_USER_V.LASTLOGINID
     *
     * @mbggenerated Thu Aug 04 14:42:02 CST 2016
     */
    private String lastloginid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_JOB_USER_V.EMAIL
     *
     * @mbggenerated Thu Aug 04 14:42:02 CST 2016
     */
    private String email;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_JOB_USER_V.UPDATE_TS
     *
     * @mbggenerated Thu Aug 04 14:42:02 CST 2016
     */
    private Date updateTs;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_JOB_USER_V.ROLE_ID
     *
     * @mbggenerated Thu Aug 04 14:42:02 CST 2016
     */
    private Long roleId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_JOB_USER_V.LEVELS
     *
     * @mbggenerated Thu Aug 04 14:42:02 CST 2016
     */
    private String levels;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_JOB_USER_V.ORGANIZATION_ID
     *
     * @mbggenerated Thu Aug 04 14:42:02 CST 2016
     */
    private String organizationId;
    
    private String team;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_JOB_USER_V.STATIONNAME
     *
     * @return the value of T_JOB_USER_V.STATIONNAME
     *
     * @mbggenerated Thu Aug 04 14:42:02 CST 2016
     */
    public String getStationname() {
        return stationname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_JOB_USER_V.STATIONNAME
     *
     * @param stationname the value for T_JOB_USER_V.STATIONNAME
     *
     * @mbggenerated Thu Aug 04 14:42:02 CST 2016
     */
    public void setStationname(String stationname) {
        this.stationname = stationname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_JOB_USER_V.JOB_ID
     *
     * @return the value of T_JOB_USER_V.JOB_ID
     *
     * @mbggenerated Thu Aug 04 14:42:02 CST 2016
     */
    public String getJobId() {
        return jobId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_JOB_USER_V.JOB_ID
     *
     * @param jobId the value for T_JOB_USER_V.JOB_ID
     *
     * @mbggenerated Thu Aug 04 14:42:02 CST 2016
     */
    public void setJobId(String jobId) {
        this.jobId = jobId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_JOB_USER_V.EMP_ID
     *
     * @return the value of T_JOB_USER_V.EMP_ID
     *
     * @mbggenerated Thu Aug 04 14:42:02 CST 2016
     */
    public Long getEmpId() {
        return empId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_JOB_USER_V.EMP_ID
     *
     * @param empId the value for T_JOB_USER_V.EMP_ID
     *
     * @mbggenerated Thu Aug 04 14:42:02 CST 2016
     */
    public void setEmpId(Long empId) {
        this.empId = empId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_JOB_USER_V.ID
     *
     * @return the value of T_JOB_USER_V.ID
     *
     * @mbggenerated Thu Aug 04 14:42:02 CST 2016
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_JOB_USER_V.ID
     *
     * @param id the value for T_JOB_USER_V.ID
     *
     * @mbggenerated Thu Aug 04 14:42:02 CST 2016
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_JOB_USER_V.NAME
     *
     * @return the value of T_JOB_USER_V.NAME
     *
     * @mbggenerated Thu Aug 04 14:42:02 CST 2016
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_JOB_USER_V.NAME
     *
     * @param name the value for T_JOB_USER_V.NAME
     *
     * @mbggenerated Thu Aug 04 14:42:02 CST 2016
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_JOB_USER_V.PID
     *
     * @return the value of T_JOB_USER_V.PID
     *
     * @mbggenerated Thu Aug 04 14:42:02 CST 2016
     */
    public Long getPid() {
        return pid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_JOB_USER_V.PID
     *
     * @param pid the value for T_JOB_USER_V.PID
     *
     * @mbggenerated Thu Aug 04 14:42:02 CST 2016
     */
    public void setPid(Long pid) {
        this.pid = pid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_JOB_USER_V.IS_SALESMAN
     *
     * @return the value of T_JOB_USER_V.IS_SALESMAN
     *
     * @mbggenerated Thu Aug 04 14:42:02 CST 2016
     */
    public String getIsSalesman() {
        return isSalesman;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_JOB_USER_V.IS_SALESMAN
     *
     * @param isSalesman the value for T_JOB_USER_V.IS_SALESMAN
     *
     * @mbggenerated Thu Aug 04 14:42:02 CST 2016
     */
    public void setIsSalesman(String isSalesman) {
        this.isSalesman = isSalesman;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_JOB_USER_V.CARD_NO
     *
     * @return the value of T_JOB_USER_V.CARD_NO
     *
     * @mbggenerated Thu Aug 04 14:42:02 CST 2016
     */
    public String getCardNo() {
        return cardNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_JOB_USER_V.CARD_NO
     *
     * @param cardNo the value for T_JOB_USER_V.CARD_NO
     *
     * @mbggenerated Thu Aug 04 14:42:02 CST 2016
     */
    public void setCardNo(String cardNo) {
        this.cardNo = cardNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_JOB_USER_V.CARD_ADDRESS
     *
     * @return the value of T_JOB_USER_V.CARD_ADDRESS
     *
     * @mbggenerated Thu Aug 04 14:42:02 CST 2016
     */
    public String getCardAddress() {
        return cardAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_JOB_USER_V.CARD_ADDRESS
     *
     * @param cardAddress the value for T_JOB_USER_V.CARD_ADDRESS
     *
     * @mbggenerated Thu Aug 04 14:42:02 CST 2016
     */
    public void setCardAddress(String cardAddress) {
        this.cardAddress = cardAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_JOB_USER_V.CONTACT_ADDRESS
     *
     * @return the value of T_JOB_USER_V.CONTACT_ADDRESS
     *
     * @mbggenerated Thu Aug 04 14:42:02 CST 2016
     */
    public String getContactAddress() {
        return contactAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_JOB_USER_V.CONTACT_ADDRESS
     *
     * @param contactAddress the value for T_JOB_USER_V.CONTACT_ADDRESS
     *
     * @mbggenerated Thu Aug 04 14:42:02 CST 2016
     */
    public void setContactAddress(String contactAddress) {
        this.contactAddress = contactAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_JOB_USER_V.CONTACT_TEL
     *
     * @return the value of T_JOB_USER_V.CONTACT_TEL
     *
     * @mbggenerated Thu Aug 04 14:42:02 CST 2016
     */
    public String getContactTel() {
        return contactTel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_JOB_USER_V.CONTACT_TEL
     *
     * @param contactTel the value for T_JOB_USER_V.CONTACT_TEL
     *
     * @mbggenerated Thu Aug 04 14:42:02 CST 2016
     */
    public void setContactTel(String contactTel) {
        this.contactTel = contactTel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_JOB_USER_V.CREATE_TS
     *
     * @return the value of T_JOB_USER_V.CREATE_TS
     *
     * @mbggenerated Thu Aug 04 14:42:02 CST 2016
     */
    public Date getCreateTs() {
        return createTs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_JOB_USER_V.CREATE_TS
     *
     * @param createTs the value for T_JOB_USER_V.CREATE_TS
     *
     * @mbggenerated Thu Aug 04 14:42:02 CST 2016
     */
    public void setCreateTs(Date createTs) {
        this.createTs = createTs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_JOB_USER_V.ENTRY_TS
     *
     * @return the value of T_JOB_USER_V.ENTRY_TS
     *
     * @mbggenerated Thu Aug 04 14:42:02 CST 2016
     */
    public Date getEntryTs() {
        return entryTs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_JOB_USER_V.ENTRY_TS
     *
     * @param entryTs the value for T_JOB_USER_V.ENTRY_TS
     *
     * @mbggenerated Thu Aug 04 14:42:02 CST 2016
     */
    public void setEntryTs(Date entryTs) {
        this.entryTs = entryTs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_JOB_USER_V.QUIT_TS
     *
     * @return the value of T_JOB_USER_V.QUIT_TS
     *
     * @mbggenerated Thu Aug 04 14:42:02 CST 2016
     */
    public Date getQuitTs() {
        return quitTs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_JOB_USER_V.QUIT_TS
     *
     * @param quitTs the value for T_JOB_USER_V.QUIT_TS
     *
     * @mbggenerated Thu Aug 04 14:42:02 CST 2016
     */
    public void setQuitTs(Date quitTs) {
        this.quitTs = quitTs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_JOB_USER_V.STATES
     *
     * @return the value of T_JOB_USER_V.STATES
     *
     * @mbggenerated Thu Aug 04 14:42:02 CST 2016
     */
    public String getStates() {
        return states;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_JOB_USER_V.STATES
     *
     * @param states the value for T_JOB_USER_V.STATES
     *
     * @mbggenerated Thu Aug 04 14:42:02 CST 2016
     */
    public void setStates(String states) {
        this.states = states;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_JOB_USER_V.LOGIN_NAME
     *
     * @return the value of T_JOB_USER_V.LOGIN_NAME
     *
     * @mbggenerated Thu Aug 04 14:42:02 CST 2016
     */
    public String getLoginName() {
        return loginName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_JOB_USER_V.LOGIN_NAME
     *
     * @param loginName the value for T_JOB_USER_V.LOGIN_NAME
     *
     * @mbggenerated Thu Aug 04 14:42:02 CST 2016
     */
    public void setLoginName(String loginName) {
        this.loginName = loginName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_JOB_USER_V.PASSWD
     *
     * @return the value of T_JOB_USER_V.PASSWD
     *
     * @mbggenerated Thu Aug 04 14:42:02 CST 2016
     */
    public String getPasswd() {
        return passwd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_JOB_USER_V.PASSWD
     *
     * @param passwd the value for T_JOB_USER_V.PASSWD
     *
     * @mbggenerated Thu Aug 04 14:42:02 CST 2016
     */
    public void setPasswd(String passwd) {
        this.passwd = passwd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_JOB_USER_V.EXP_DATE
     *
     * @return the value of T_JOB_USER_V.EXP_DATE
     *
     * @mbggenerated Thu Aug 04 14:42:02 CST 2016
     */
    public Date getExpDate() {
        return expDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_JOB_USER_V.EXP_DATE
     *
     * @param expDate the value for T_JOB_USER_V.EXP_DATE
     *
     * @mbggenerated Thu Aug 04 14:42:02 CST 2016
     */
    public void setExpDate(Date expDate) {
        this.expDate = expDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_JOB_USER_V.LASTUPDATES
     *
     * @return the value of T_JOB_USER_V.LASTUPDATES
     *
     * @mbggenerated Thu Aug 04 14:42:02 CST 2016
     */
    public Date getLastupdates() {
        return lastupdates;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_JOB_USER_V.LASTUPDATES
     *
     * @param lastupdates the value for T_JOB_USER_V.LASTUPDATES
     *
     * @mbggenerated Thu Aug 04 14:42:02 CST 2016
     */
    public void setLastupdates(Date lastupdates) {
        this.lastupdates = lastupdates;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_JOB_USER_V.PWD_ERROR_COUNT
     *
     * @return the value of T_JOB_USER_V.PWD_ERROR_COUNT
     *
     * @mbggenerated Thu Aug 04 14:42:02 CST 2016
     */
    public String getPwdErrorCount() {
        return pwdErrorCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_JOB_USER_V.PWD_ERROR_COUNT
     *
     * @param pwdErrorCount the value for T_JOB_USER_V.PWD_ERROR_COUNT
     *
     * @mbggenerated Thu Aug 04 14:42:02 CST 2016
     */
    public void setPwdErrorCount(String pwdErrorCount) {
        this.pwdErrorCount = pwdErrorCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_JOB_USER_V.LOGIN_TS
     *
     * @return the value of T_JOB_USER_V.LOGIN_TS
     *
     * @mbggenerated Thu Aug 04 14:42:02 CST 2016
     */
    public Date getLoginTs() {
        return loginTs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_JOB_USER_V.LOGIN_TS
     *
     * @param loginTs the value for T_JOB_USER_V.LOGIN_TS
     *
     * @mbggenerated Thu Aug 04 14:42:02 CST 2016
     */
    public void setLoginTs(Date loginTs) {
        this.loginTs = loginTs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_JOB_USER_V.LASTLOGINID
     *
     * @return the value of T_JOB_USER_V.LASTLOGINID
     *
     * @mbggenerated Thu Aug 04 14:42:02 CST 2016
     */
    public String getLastloginid() {
        return lastloginid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_JOB_USER_V.LASTLOGINID
     *
     * @param lastloginid the value for T_JOB_USER_V.LASTLOGINID
     *
     * @mbggenerated Thu Aug 04 14:42:02 CST 2016
     */
    public void setLastloginid(String lastloginid) {
        this.lastloginid = lastloginid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_JOB_USER_V.EMAIL
     *
     * @return the value of T_JOB_USER_V.EMAIL
     *
     * @mbggenerated Thu Aug 04 14:42:02 CST 2016
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_JOB_USER_V.EMAIL
     *
     * @param email the value for T_JOB_USER_V.EMAIL
     *
     * @mbggenerated Thu Aug 04 14:42:02 CST 2016
     */
    public void setEmail(String email) {
        this.email = email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_JOB_USER_V.UPDATE_TS
     *
     * @return the value of T_JOB_USER_V.UPDATE_TS
     *
     * @mbggenerated Thu Aug 04 14:42:02 CST 2016
     */
    public Date getUpdateTs() {
        return updateTs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_JOB_USER_V.UPDATE_TS
     *
     * @param updateTs the value for T_JOB_USER_V.UPDATE_TS
     *
     * @mbggenerated Thu Aug 04 14:42:02 CST 2016
     */
    public void setUpdateTs(Date updateTs) {
        this.updateTs = updateTs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_JOB_USER_V.ROLE_ID
     *
     * @return the value of T_JOB_USER_V.ROLE_ID
     *
     * @mbggenerated Thu Aug 04 14:42:02 CST 2016
     */
    public Long getRoleId() {
        return roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_JOB_USER_V.ROLE_ID
     *
     * @param roleId the value for T_JOB_USER_V.ROLE_ID
     *
     * @mbggenerated Thu Aug 04 14:42:02 CST 2016
     */
    public void setRoleId(Long roleId) {
        this.roleId = roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_JOB_USER_V.LEVELS
     *
     * @return the value of T_JOB_USER_V.LEVELS
     *
     * @mbggenerated Thu Aug 04 14:42:02 CST 2016
     */
    public String getLevels() {
        return levels;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_JOB_USER_V.LEVELS
     *
     * @param levels the value for T_JOB_USER_V.LEVELS
     *
     * @mbggenerated Thu Aug 04 14:42:02 CST 2016
     */
    public void setLevels(String levels) {
        this.levels = levels;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_JOB_USER_V.ORGANIZATION_ID
     *
     * @return the value of T_JOB_USER_V.ORGANIZATION_ID
     *
     * @mbggenerated Thu Aug 04 14:42:02 CST 2016
     */
    public String getOrganizationId() {
        return organizationId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_JOB_USER_V.ORGANIZATION_ID
     *
     * @param organizationId the value for T_JOB_USER_V.ORGANIZATION_ID
     *
     * @mbggenerated Thu Aug 04 14:42:02 CST 2016
     */
    public void setOrganizationId(String organizationId) {
        this.organizationId = organizationId;
    }

    public String getTeam() {
      return team;
    }

    public void setTeam(String team) {
      this.team = team;
    }
    
}