package com.hhnz.cost.mapper;

import com.hhnz.cost.model.CrmBudgetMain;
import com.hhnz.cost.model.CrmBudgetMainExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CrmBudgetMainMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CRM_BUDGET_MAIN
     *
     * @mbggenerated Thu Aug 18 11:41:20 CST 2016
     */
    int countByExample(CrmBudgetMainExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CRM_BUDGET_MAIN
     *
     * @mbggenerated Thu Aug 18 11:41:20 CST 2016
     */
    int deleteByExample(CrmBudgetMainExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CRM_BUDGET_MAIN
     *
     * @mbggenerated Thu Aug 18 11:41:20 CST 2016
     */
    int insert(CrmBudgetMain record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CRM_BUDGET_MAIN
     *
     * @mbggenerated Thu Aug 18 11:41:20 CST 2016
     */
    int insertSelective(CrmBudgetMain record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CRM_BUDGET_MAIN
     *
     * @mbggenerated Thu Aug 18 11:41:20 CST 2016
     */
    List<CrmBudgetMain> selectByExample(CrmBudgetMainExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CRM_BUDGET_MAIN
     *
     * @mbggenerated Thu Aug 18 11:41:20 CST 2016
     */
    int updateByExampleSelective(@Param("record") CrmBudgetMain record, @Param("example") CrmBudgetMainExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CRM_BUDGET_MAIN
     *
     * @mbggenerated Thu Aug 18 11:41:20 CST 2016
     */
    int updateByExample(@Param("record") CrmBudgetMain record, @Param("example") CrmBudgetMainExample example);
}