CREATE OR REPLACE VIEW OM_ORDER_DELIVERED_V AS
SELECT OD."DELIVERY_NO",OD."SAP_ORDER_ID",OD."NUM",OD."POST_TIME",OD."ORDERITEM_SAP_NO",OD."DELIVERYITEM_NO",
       OS.NUM AS ORDER_NUM,
       OH.ID AS ORDER_ID,
       (SELECT MB.MATERIAL_NAME
          FROM T_MATERIAL_BASE MB
         WHERE MB.SAP_ID = OS.MATERIAL_ID) AS MATERAIL_NAME
  FROM OM_ORDER_DELIVERED OD --sap发货数据表
  LEFT JOIN OM_ORDER_HEADERS_ALL OH --订单头
    ON OH.SAP_ORDER_ID = OD.SAP_ORDER_ID
  LEFT JOIN OM_ORDER_SPILTS OS --订单明细（对应SAP行项目）
    ON OS.ORDERITEM_SAP_NO = OD.ORDERITEM_SAP_NO  AND OS.HEADER_ID = OH.ID;
