package com.hhnz.crm.model;

import java.util.Date;

public class TEmployee {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_EMPLOYEE.ID
     *
     * @mbggenerated Fri Sep 23 10:05:50 CST 2016
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_EMPLOYEE.NAME
     *
     * @mbggenerated Fri Sep 23 10:05:50 CST 2016
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_EMPLOYEE.PID
     *
     * @mbggenerated Fri Sep 23 10:05:50 CST 2016
     */
    private Long pid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_EMPLOYEE.IS_SALESMAN
     *
     * @mbggenerated Fri Sep 23 10:05:50 CST 2016
     */
    private String isSalesman;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_EMPLOYEE.CARD_NO
     *
     * @mbggenerated Fri Sep 23 10:05:50 CST 2016
     */
    private String cardNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_EMPLOYEE.CARD_ADDRESS
     *
     * @mbggenerated Fri Sep 23 10:05:50 CST 2016
     */
    private String cardAddress;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_EMPLOYEE.CONTACT_ADDRESS
     *
     * @mbggenerated Fri Sep 23 10:05:50 CST 2016
     */
    private String contactAddress;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_EMPLOYEE.CONTACT_TEL
     *
     * @mbggenerated Fri Sep 23 10:05:50 CST 2016
     */
    private String contactTel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_EMPLOYEE.CREATE_TS
     *
     * @mbggenerated Fri Sep 23 10:05:50 CST 2016
     */
    private Date createTs;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_EMPLOYEE.ENTRY_TS
     *
     * @mbggenerated Fri Sep 23 10:05:50 CST 2016
     */
    private Date entryTs;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_EMPLOYEE.QUIT_TS
     *
     * @mbggenerated Fri Sep 23 10:05:50 CST 2016
     */
    private Date quitTs;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_EMPLOYEE.STATES
     *
     * @mbggenerated Fri Sep 23 10:05:50 CST 2016
     */
    private String states;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_EMPLOYEE.LOGIN_NAME
     *
     * @mbggenerated Fri Sep 23 10:05:50 CST 2016
     */
    private String loginName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_EMPLOYEE.PASSWD
     *
     * @mbggenerated Fri Sep 23 10:05:50 CST 2016
     */
    private String passwd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_EMPLOYEE.EXP_DATE
     *
     * @mbggenerated Fri Sep 23 10:05:50 CST 2016
     */
    private Date expDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_EMPLOYEE.LASTUPDATES
     *
     * @mbggenerated Fri Sep 23 10:05:50 CST 2016
     */
    private Date lastupdates;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_EMPLOYEE.PWD_ERROR_COUNT
     *
     * @mbggenerated Fri Sep 23 10:05:50 CST 2016
     */
    private String pwdErrorCount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_EMPLOYEE.LOGIN_TS
     *
     * @mbggenerated Fri Sep 23 10:05:50 CST 2016
     */
    private Date loginTs;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_EMPLOYEE.LASTLOGINID
     *
     * @mbggenerated Fri Sep 23 10:05:50 CST 2016
     */
    private String lastloginid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_EMPLOYEE.EMAIL
     *
     * @mbggenerated Fri Sep 23 10:05:50 CST 2016
     */
    private String email;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_EMPLOYEE.UPDATE_TS
     *
     * @mbggenerated Fri Sep 23 10:05:50 CST 2016
     */
    private Date updateTs;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_EMPLOYEE.ROLE_ID
     *
     * @mbggenerated Fri Sep 23 10:05:50 CST 2016
     */
    private Long roleId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_EMPLOYEE.LEVELS
     *
     * @mbggenerated Fri Sep 23 10:05:50 CST 2016
     */
    private String levels;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_EMPLOYEE.ORGANIZATION_ID
     *
     * @mbggenerated Fri Sep 23 10:05:50 CST 2016
     */
    private String organizationId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_EMPLOYEE.USER_TYPE
     *
     * @mbggenerated Fri Sep 23 10:05:50 CST 2016
     */
    private String userType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_EMPLOYEE.MERCH_ID
     *
     * @mbggenerated Fri Sep 23 10:05:50 CST 2016
     */
    private Long merchId;
    
    private String merchName;
    
    public String getMerchName() {
      return merchName;
    }

    public void setMerchName(String merchName) {
      this.merchName = merchName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_EMPLOYEE.ID
     *
     * @return the value of T_EMPLOYEE.ID
     *
     * @mbggenerated Fri Sep 23 10:05:50 CST 2016
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_EMPLOYEE.ID
     *
     * @param id the value for T_EMPLOYEE.ID
     *
     * @mbggenerated Fri Sep 23 10:05:50 CST 2016
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_EMPLOYEE.NAME
     *
     * @return the value of T_EMPLOYEE.NAME
     *
     * @mbggenerated Fri Sep 23 10:05:50 CST 2016
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_EMPLOYEE.NAME
     *
     * @param name the value for T_EMPLOYEE.NAME
     *
     * @mbggenerated Fri Sep 23 10:05:50 CST 2016
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_EMPLOYEE.PID
     *
     * @return the value of T_EMPLOYEE.PID
     *
     * @mbggenerated Fri Sep 23 10:05:50 CST 2016
     */
    public Long getPid() {
        return pid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_EMPLOYEE.PID
     *
     * @param pid the value for T_EMPLOYEE.PID
     *
     * @mbggenerated Fri Sep 23 10:05:50 CST 2016
     */
    public void setPid(Long pid) {
        this.pid = pid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_EMPLOYEE.IS_SALESMAN
     *
     * @return the value of T_EMPLOYEE.IS_SALESMAN
     *
     * @mbggenerated Fri Sep 23 10:05:50 CST 2016
     */
    public String getIsSalesman() {
        return isSalesman;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_EMPLOYEE.IS_SALESMAN
     *
     * @param isSalesman the value for T_EMPLOYEE.IS_SALESMAN
     *
     * @mbggenerated Fri Sep 23 10:05:50 CST 2016
     */
    public void setIsSalesman(String isSalesman) {
        this.isSalesman = isSalesman;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_EMPLOYEE.CARD_NO
     *
     * @return the value of T_EMPLOYEE.CARD_NO
     *
     * @mbggenerated Fri Sep 23 10:05:50 CST 2016
     */
    public String getCardNo() {
        return cardNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_EMPLOYEE.CARD_NO
     *
     * @param cardNo the value for T_EMPLOYEE.CARD_NO
     *
     * @mbggenerated Fri Sep 23 10:05:50 CST 2016
     */
    public void setCardNo(String cardNo) {
        this.cardNo = cardNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_EMPLOYEE.CARD_ADDRESS
     *
     * @return the value of T_EMPLOYEE.CARD_ADDRESS
     *
     * @mbggenerated Fri Sep 23 10:05:50 CST 2016
     */
    public String getCardAddress() {
        return cardAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_EMPLOYEE.CARD_ADDRESS
     *
     * @param cardAddress the value for T_EMPLOYEE.CARD_ADDRESS
     *
     * @mbggenerated Fri Sep 23 10:05:50 CST 2016
     */
    public void setCardAddress(String cardAddress) {
        this.cardAddress = cardAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_EMPLOYEE.CONTACT_ADDRESS
     *
     * @return the value of T_EMPLOYEE.CONTACT_ADDRESS
     *
     * @mbggenerated Fri Sep 23 10:05:50 CST 2016
     */
    public String getContactAddress() {
        return contactAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_EMPLOYEE.CONTACT_ADDRESS
     *
     * @param contactAddress the value for T_EMPLOYEE.CONTACT_ADDRESS
     *
     * @mbggenerated Fri Sep 23 10:05:50 CST 2016
     */
    public void setContactAddress(String contactAddress) {
        this.contactAddress = contactAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_EMPLOYEE.CONTACT_TEL
     *
     * @return the value of T_EMPLOYEE.CONTACT_TEL
     *
     * @mbggenerated Fri Sep 23 10:05:50 CST 2016
     */
    public String getContactTel() {
        return contactTel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_EMPLOYEE.CONTACT_TEL
     *
     * @param contactTel the value for T_EMPLOYEE.CONTACT_TEL
     *
     * @mbggenerated Fri Sep 23 10:05:50 CST 2016
     */
    public void setContactTel(String contactTel) {
        this.contactTel = contactTel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_EMPLOYEE.CREATE_TS
     *
     * @return the value of T_EMPLOYEE.CREATE_TS
     *
     * @mbggenerated Fri Sep 23 10:05:50 CST 2016
     */
    public Date getCreateTs() {
        return createTs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_EMPLOYEE.CREATE_TS
     *
     * @param createTs the value for T_EMPLOYEE.CREATE_TS
     *
     * @mbggenerated Fri Sep 23 10:05:50 CST 2016
     */
    public void setCreateTs(Date createTs) {
        this.createTs = createTs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_EMPLOYEE.ENTRY_TS
     *
     * @return the value of T_EMPLOYEE.ENTRY_TS
     *
     * @mbggenerated Fri Sep 23 10:05:50 CST 2016
     */
    public Date getEntryTs() {
        return entryTs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_EMPLOYEE.ENTRY_TS
     *
     * @param entryTs the value for T_EMPLOYEE.ENTRY_TS
     *
     * @mbggenerated Fri Sep 23 10:05:50 CST 2016
     */
    public void setEntryTs(Date entryTs) {
        this.entryTs = entryTs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_EMPLOYEE.QUIT_TS
     *
     * @return the value of T_EMPLOYEE.QUIT_TS
     *
     * @mbggenerated Fri Sep 23 10:05:50 CST 2016
     */
    public Date getQuitTs() {
        return quitTs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_EMPLOYEE.QUIT_TS
     *
     * @param quitTs the value for T_EMPLOYEE.QUIT_TS
     *
     * @mbggenerated Fri Sep 23 10:05:50 CST 2016
     */
    public void setQuitTs(Date quitTs) {
        this.quitTs = quitTs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_EMPLOYEE.STATES
     *
     * @return the value of T_EMPLOYEE.STATES
     *
     * @mbggenerated Fri Sep 23 10:05:50 CST 2016
     */
    public String getStates() {
        return states;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_EMPLOYEE.STATES
     *
     * @param states the value for T_EMPLOYEE.STATES
     *
     * @mbggenerated Fri Sep 23 10:05:50 CST 2016
     */
    public void setStates(String states) {
        this.states = states;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_EMPLOYEE.LOGIN_NAME
     *
     * @return the value of T_EMPLOYEE.LOGIN_NAME
     *
     * @mbggenerated Fri Sep 23 10:05:50 CST 2016
     */
    public String getLoginName() {
        return loginName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_EMPLOYEE.LOGIN_NAME
     *
     * @param loginName the value for T_EMPLOYEE.LOGIN_NAME
     *
     * @mbggenerated Fri Sep 23 10:05:50 CST 2016
     */
    public void setLoginName(String loginName) {
        this.loginName = loginName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_EMPLOYEE.PASSWD
     *
     * @return the value of T_EMPLOYEE.PASSWD
     *
     * @mbggenerated Fri Sep 23 10:05:50 CST 2016
     */
    public String getPasswd() {
        return passwd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_EMPLOYEE.PASSWD
     *
     * @param passwd the value for T_EMPLOYEE.PASSWD
     *
     * @mbggenerated Fri Sep 23 10:05:50 CST 2016
     */
    public void setPasswd(String passwd) {
        this.passwd = passwd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_EMPLOYEE.EXP_DATE
     *
     * @return the value of T_EMPLOYEE.EXP_DATE
     *
     * @mbggenerated Fri Sep 23 10:05:50 CST 2016
     */
    public Date getExpDate() {
        return expDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_EMPLOYEE.EXP_DATE
     *
     * @param expDate the value for T_EMPLOYEE.EXP_DATE
     *
     * @mbggenerated Fri Sep 23 10:05:50 CST 2016
     */
    public void setExpDate(Date expDate) {
        this.expDate = expDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_EMPLOYEE.LASTUPDATES
     *
     * @return the value of T_EMPLOYEE.LASTUPDATES
     *
     * @mbggenerated Fri Sep 23 10:05:50 CST 2016
     */
    public Date getLastupdates() {
        return lastupdates;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_EMPLOYEE.LASTUPDATES
     *
     * @param lastupdates the value for T_EMPLOYEE.LASTUPDATES
     *
     * @mbggenerated Fri Sep 23 10:05:50 CST 2016
     */
    public void setLastupdates(Date lastupdates) {
        this.lastupdates = lastupdates;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_EMPLOYEE.PWD_ERROR_COUNT
     *
     * @return the value of T_EMPLOYEE.PWD_ERROR_COUNT
     *
     * @mbggenerated Fri Sep 23 10:05:50 CST 2016
     */
    public String getPwdErrorCount() {
        return pwdErrorCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_EMPLOYEE.PWD_ERROR_COUNT
     *
     * @param pwdErrorCount the value for T_EMPLOYEE.PWD_ERROR_COUNT
     *
     * @mbggenerated Fri Sep 23 10:05:50 CST 2016
     */
    public void setPwdErrorCount(String pwdErrorCount) {
        this.pwdErrorCount = pwdErrorCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_EMPLOYEE.LOGIN_TS
     *
     * @return the value of T_EMPLOYEE.LOGIN_TS
     *
     * @mbggenerated Fri Sep 23 10:05:50 CST 2016
     */
    public Date getLoginTs() {
        return loginTs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_EMPLOYEE.LOGIN_TS
     *
     * @param loginTs the value for T_EMPLOYEE.LOGIN_TS
     *
     * @mbggenerated Fri Sep 23 10:05:50 CST 2016
     */
    public void setLoginTs(Date loginTs) {
        this.loginTs = loginTs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_EMPLOYEE.LASTLOGINID
     *
     * @return the value of T_EMPLOYEE.LASTLOGINID
     *
     * @mbggenerated Fri Sep 23 10:05:50 CST 2016
     */
    public String getLastloginid() {
        return lastloginid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_EMPLOYEE.LASTLOGINID
     *
     * @param lastloginid the value for T_EMPLOYEE.LASTLOGINID
     *
     * @mbggenerated Fri Sep 23 10:05:50 CST 2016
     */
    public void setLastloginid(String lastloginid) {
        this.lastloginid = lastloginid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_EMPLOYEE.EMAIL
     *
     * @return the value of T_EMPLOYEE.EMAIL
     *
     * @mbggenerated Fri Sep 23 10:05:50 CST 2016
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_EMPLOYEE.EMAIL
     *
     * @param email the value for T_EMPLOYEE.EMAIL
     *
     * @mbggenerated Fri Sep 23 10:05:50 CST 2016
     */
    public void setEmail(String email) {
        this.email = email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_EMPLOYEE.UPDATE_TS
     *
     * @return the value of T_EMPLOYEE.UPDATE_TS
     *
     * @mbggenerated Fri Sep 23 10:05:50 CST 2016
     */
    public Date getUpdateTs() {
        return updateTs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_EMPLOYEE.UPDATE_TS
     *
     * @param updateTs the value for T_EMPLOYEE.UPDATE_TS
     *
     * @mbggenerated Fri Sep 23 10:05:50 CST 2016
     */
    public void setUpdateTs(Date updateTs) {
        this.updateTs = updateTs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_EMPLOYEE.ROLE_ID
     *
     * @return the value of T_EMPLOYEE.ROLE_ID
     *
     * @mbggenerated Fri Sep 23 10:05:50 CST 2016
     */
    public Long getRoleId() {
        return roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_EMPLOYEE.ROLE_ID
     *
     * @param roleId the value for T_EMPLOYEE.ROLE_ID
     *
     * @mbggenerated Fri Sep 23 10:05:50 CST 2016
     */
    public void setRoleId(Long roleId) {
        this.roleId = roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_EMPLOYEE.LEVELS
     *
     * @return the value of T_EMPLOYEE.LEVELS
     *
     * @mbggenerated Fri Sep 23 10:05:50 CST 2016
     */
    public String getLevels() {
        return levels;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_EMPLOYEE.LEVELS
     *
     * @param levels the value for T_EMPLOYEE.LEVELS
     *
     * @mbggenerated Fri Sep 23 10:05:50 CST 2016
     */
    public void setLevels(String levels) {
        this.levels = levels;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_EMPLOYEE.ORGANIZATION_ID
     *
     * @return the value of T_EMPLOYEE.ORGANIZATION_ID
     *
     * @mbggenerated Fri Sep 23 10:05:50 CST 2016
     */
    public String getOrganizationId() {
        return organizationId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_EMPLOYEE.ORGANIZATION_ID
     *
     * @param organizationId the value for T_EMPLOYEE.ORGANIZATION_ID
     *
     * @mbggenerated Fri Sep 23 10:05:50 CST 2016
     */
    public void setOrganizationId(String organizationId) {
        this.organizationId = organizationId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_EMPLOYEE.USER_TYPE
     *
     * @return the value of T_EMPLOYEE.USER_TYPE
     *
     * @mbggenerated Fri Sep 23 10:05:50 CST 2016
     */
    public String getUserType() {
        return userType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_EMPLOYEE.USER_TYPE
     *
     * @param userType the value for T_EMPLOYEE.USER_TYPE
     *
     * @mbggenerated Fri Sep 23 10:05:50 CST 2016
     */
    public void setUserType(String userType) {
        this.userType = userType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_EMPLOYEE.MERCH_ID
     *
     * @return the value of T_EMPLOYEE.MERCH_ID
     *
     * @mbggenerated Fri Sep 23 10:05:50 CST 2016
     */
    public Long getMerchId() {
        return merchId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_EMPLOYEE.MERCH_ID
     *
     * @param merchId the value for T_EMPLOYEE.MERCH_ID
     *
     * @mbggenerated Fri Sep 23 10:05:50 CST 2016
     */
    public void setMerchId(Long merchId) {
        this.merchId = merchId;
    }
}