package com.hhnz.cost.model;

import com.hhnz.util.db.Page;

import java.util.ArrayList;
import java.util.List;

public class CrmCostBalancesVExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table CRM_COST_BALANCES_V
     *
     * @mbggenerated Wed Sep 14 14:23:08 CST 2016
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table CRM_COST_BALANCES_V
     *
     * @mbggenerated Wed Sep 14 14:23:08 CST 2016
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table CRM_COST_BALANCES_V
     *
     * @mbggenerated Wed Sep 14 14:23:08 CST 2016
     */
    protected List<Criteria> oredCriteria;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table CRM_COST_BALANCES_V
     *
     * @mbggenerated Wed Sep 14 14:23:08 CST 2016
     */
    protected Page page;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CRM_COST_BALANCES_V
     *
     * @mbggenerated Wed Sep 14 14:23:08 CST 2016
     */
    public CrmCostBalancesVExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CRM_COST_BALANCES_V
     *
     * @mbggenerated Wed Sep 14 14:23:08 CST 2016
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CRM_COST_BALANCES_V
     *
     * @mbggenerated Wed Sep 14 14:23:08 CST 2016
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CRM_COST_BALANCES_V
     *
     * @mbggenerated Wed Sep 14 14:23:08 CST 2016
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CRM_COST_BALANCES_V
     *
     * @mbggenerated Wed Sep 14 14:23:08 CST 2016
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CRM_COST_BALANCES_V
     *
     * @mbggenerated Wed Sep 14 14:23:08 CST 2016
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CRM_COST_BALANCES_V
     *
     * @mbggenerated Wed Sep 14 14:23:08 CST 2016
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CRM_COST_BALANCES_V
     *
     * @mbggenerated Wed Sep 14 14:23:08 CST 2016
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CRM_COST_BALANCES_V
     *
     * @mbggenerated Wed Sep 14 14:23:08 CST 2016
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CRM_COST_BALANCES_V
     *
     * @mbggenerated Wed Sep 14 14:23:08 CST 2016
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CRM_COST_BALANCES_V
     *
     * @mbggenerated Wed Sep 14 14:23:08 CST 2016
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CRM_COST_BALANCES_V
     *
     * @mbggenerated Wed Sep 14 14:23:08 CST 2016
     */
    public void setPage(Page page) {
        this.page=page;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CRM_COST_BALANCES_V
     *
     * @mbggenerated Wed Sep 14 14:23:08 CST 2016
     */
    public Page getPage() {
        return page;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table CRM_COST_BALANCES_V
     *
     * @mbggenerated Wed Sep 14 14:23:08 CST 2016
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andCostTypeidIsNull() {
            addCriterion("COST_TYPEID is null");
            return (Criteria) this;
        }

        public Criteria andCostTypeidIsNotNull() {
            addCriterion("COST_TYPEID is not null");
            return (Criteria) this;
        }

        public Criteria andCostTypeidEqualTo(String value) {
            addCriterion("COST_TYPEID =", value, "costTypeid");
            return (Criteria) this;
        }

        public Criteria andCostTypeidNotEqualTo(String value) {
            addCriterion("COST_TYPEID <>", value, "costTypeid");
            return (Criteria) this;
        }

        public Criteria andCostTypeidGreaterThan(String value) {
            addCriterion("COST_TYPEID >", value, "costTypeid");
            return (Criteria) this;
        }

        public Criteria andCostTypeidGreaterThanOrEqualTo(String value) {
            addCriterion("COST_TYPEID >=", value, "costTypeid");
            return (Criteria) this;
        }

        public Criteria andCostTypeidLessThan(String value) {
            addCriterion("COST_TYPEID <", value, "costTypeid");
            return (Criteria) this;
        }

        public Criteria andCostTypeidLessThanOrEqualTo(String value) {
            addCriterion("COST_TYPEID <=", value, "costTypeid");
            return (Criteria) this;
        }

        public Criteria andCostTypeidIn(List<String> values) {
            addCriterion("COST_TYPEID in", values, "costTypeid");
            return (Criteria) this;
        }

        public Criteria andCostTypeidNotIn(List<String> values) {
            addCriterion("COST_TYPEID not in", values, "costTypeid");
            return (Criteria) this;
        }

        public Criteria andCostTypeidBetween(String value1, String value2) {
            addCriterion("COST_TYPEID between", value1, value2, "costTypeid");
            return (Criteria) this;
        }

        public Criteria andCostTypeidNotBetween(String value1, String value2) {
            addCriterion("COST_TYPEID not between", value1, value2, "costTypeid");
            return (Criteria) this;
        }

        public Criteria andIdIsNull() {
            addCriterion("ID is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("ID is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Long id) {
            addCriterion("ID =", id, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Long value) {
            addCriterion("ID <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Long value) {
            addCriterion("ID >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Long value) {
            addCriterion("ID >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Long value) {
            addCriterion("ID <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Long value) {
            addCriterion("ID <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLike(Long value) {
            addCriterion("ID like", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotLike(Long value) {
            addCriterion("ID not like", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Long> values) {
            addCriterion("ID in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Long> values) {
            addCriterion("ID not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Long value1, Long value2) {
            addCriterion("ID between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Long value1, Long value2) {
            addCriterion("ID not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andOrgnameIsNull() {
            addCriterion("ORGNAME is null");
            return (Criteria) this;
        }

        public Criteria andOrgnameIsNotNull() {
            addCriterion("ORGNAME is not null");
            return (Criteria) this;
        }

        public Criteria andOrgnameEqualTo(String value) {
            addCriterion("ORGNAME =", value, "orgname");
            return (Criteria) this;
        }

        public Criteria andOrgnameNotEqualTo(String value) {
            addCriterion("ORGNAME <>", value, "orgname");
            return (Criteria) this;
        }

        public Criteria andOrgnameGreaterThan(String value) {
            addCriterion("ORGNAME >", value, "orgname");
            return (Criteria) this;
        }

        public Criteria andOrgnameGreaterThanOrEqualTo(String value) {
            addCriterion("ORGNAME >=", value, "orgname");
            return (Criteria) this;
        }

        public Criteria andOrgnameLessThan(String value) {
            addCriterion("ORGNAME <", value, "orgname");
            return (Criteria) this;
        }

        public Criteria andOrgnameLessThanOrEqualTo(String value) {
            addCriterion("ORGNAME <=", value, "orgname");
            return (Criteria) this;
        }

        public Criteria andOrgnameLike(String value) {
            addCriterion("ORGNAME like", value, "orgname");
            return (Criteria) this;
        }

        public Criteria andOrgnameNotLike(String value) {
            addCriterion("ORGNAME not like", value, "orgname");
            return (Criteria) this;
        }

        public Criteria andOrgnameIn(List<String> values) {
            addCriterion("ORGNAME in", values, "orgname");
            return (Criteria) this;
        }

        public Criteria andOrgnameNotIn(List<String> values) {
            addCriterion("ORGNAME not in", values, "orgname");
            return (Criteria) this;
        }

        public Criteria andOrgnameBetween(String value1, String value2) {
            addCriterion("ORGNAME between", value1, value2, "orgname");
            return (Criteria) this;
        }

        public Criteria andOrgnameNotBetween(String value1, String value2) {
            addCriterion("ORGNAME not between", value1, value2, "orgname");
            return (Criteria) this;
        }
        
        public Criteria andOrgidLike(String value) {
            addCriterion("orgid like", value,"orgid");
            return (Criteria) this;
        }
        
        public Criteria andOrgidEqualTo(String value) {
            addCriterion("orgid =", value,"orgid");
            return (Criteria) this;
        }
        
        public Criteria andRegionIdIsNull() {
            addCriterion("REGION_ID is null");
            return (Criteria) this;
        }

        public Criteria andRegionIdIsNotNull() {
            addCriterion("REGION_ID is not null");
            return (Criteria) this;
        }

        public Criteria andRegionIdEqualTo(String value) {
            addCriterion("REGION_ID =", value, "regionId");
            return (Criteria) this;
        }

        public Criteria andRegionIdNotEqualTo(String value) {
            addCriterion("REGION_ID <>", value, "regionId");
            return (Criteria) this;
        }

        public Criteria andRegionIdGreaterThan(String value) {
            addCriterion("REGION_ID >", value, "regionId");
            return (Criteria) this;
        }

        public Criteria andRegionIdGreaterThanOrEqualTo(String value) {
            addCriterion("REGION_ID >=", value, "regionId");
            return (Criteria) this;
        }

        public Criteria andRegionIdLessThan(String value) {
            addCriterion("REGION_ID <", value, "regionId");
            return (Criteria) this;
        }

        public Criteria andRegionIdLessThanOrEqualTo(String value) {
            addCriterion("REGION_ID <=", value, "regionId");
            return (Criteria) this;
        }

        public Criteria andRegionIdLike(String value) {
            addCriterion("REGION_ID like", value, "regionId");
            return (Criteria) this;
        }

        public Criteria andRegionIdNotLike(String value) {
            addCriterion("REGION_ID not like", value, "regionId");
            return (Criteria) this;
        }

        public Criteria andRegionIdIn(List<String> values) {
            addCriterion("REGION_ID in", values, "regionId");
            return (Criteria) this;
        }

        public Criteria andRegionIdNotIn(List<String> values) {
            addCriterion("REGION_ID not in", values, "regionId");
            return (Criteria) this;
        }

        public Criteria andRegionIdBetween(String value1, String value2) {
            addCriterion("REGION_ID between", value1, value2, "regionId");
            return (Criteria) this;
        }

        public Criteria andRegionIdNotBetween(String value1, String value2) {
            addCriterion("REGION_ID not between", value1, value2, "regionId");
            return (Criteria) this;
        }

        public Criteria andRegionNameIsNull() {
            addCriterion("REGION_NAME is null");
            return (Criteria) this;
        }

        public Criteria andRegionNameIsNotNull() {
            addCriterion("REGION_NAME is not null");
            return (Criteria) this;
        }

        public Criteria andRegionNameEqualTo(String value) {
            addCriterion("REGION_NAME =", value, "regionName");
            return (Criteria) this;
        }

        public Criteria andRegionNameNotEqualTo(String value) {
            addCriterion("REGION_NAME <>", value, "regionName");
            return (Criteria) this;
        }

        public Criteria andRegionNameGreaterThan(String value) {
            addCriterion("REGION_NAME >", value, "regionName");
            return (Criteria) this;
        }

        public Criteria andRegionNameGreaterThanOrEqualTo(String value) {
            addCriterion("REGION_NAME >=", value, "regionName");
            return (Criteria) this;
        }

        public Criteria andRegionNameLessThan(String value) {
            addCriterion("REGION_NAME <", value, "regionName");
            return (Criteria) this;
        }

        public Criteria andRegionNameLessThanOrEqualTo(String value) {
            addCriterion("REGION_NAME <=", value, "regionName");
            return (Criteria) this;
        }

        public Criteria andRegionNameLike(String value) {
            addCriterion("REGION_NAME like", value, "regionName");
            return (Criteria) this;
        }

        public Criteria andRegionNameNotLike(String value) {
            addCriterion("REGION_NAME not like", value, "regionName");
            return (Criteria) this;
        }

        public Criteria andRegionNameIn(List<String> values) {
            addCriterion("REGION_NAME in", values, "regionName");
            return (Criteria) this;
        }

        public Criteria andRegionNameNotIn(List<String> values) {
            addCriterion("REGION_NAME not in", values, "regionName");
            return (Criteria) this;
        }

        public Criteria andRegionNameBetween(String value1, String value2) {
            addCriterion("REGION_NAME between", value1, value2, "regionName");
            return (Criteria) this;
        }

        public Criteria andRegionNameNotBetween(String value1, String value2) {
            addCriterion("REGION_NAME not between", value1, value2, "regionName");
            return (Criteria) this;
        }

        public Criteria andProvIdIsNull() {
            addCriterion("PROV_ID is null");
            return (Criteria) this;
        }

        public Criteria andProvIdIsNotNull() {
            addCriterion("PROV_ID is not null");
            return (Criteria) this;
        }

        public Criteria andProvIdEqualTo(String value) {
            addCriterion("PROV_ID =", value, "provId");
            return (Criteria) this;
        }

        public Criteria andProvIdNotEqualTo(String value) {
            addCriterion("PROV_ID <>", value, "provId");
            return (Criteria) this;
        }

        public Criteria andProvIdGreaterThan(String value) {
            addCriterion("PROV_ID >", value, "provId");
            return (Criteria) this;
        }

        public Criteria andProvIdGreaterThanOrEqualTo(String value) {
            addCriterion("PROV_ID >=", value, "provId");
            return (Criteria) this;
        }

        public Criteria andProvIdLessThan(String value) {
            addCriterion("PROV_ID <", value, "provId");
            return (Criteria) this;
        }

        public Criteria andProvIdLessThanOrEqualTo(String value) {
            addCriterion("PROV_ID <=", value, "provId");
            return (Criteria) this;
        }

        public Criteria andProvIdLike(String value) {
            addCriterion("PROV_ID like", value, "provId");
            return (Criteria) this;
        }

        public Criteria andProvIdNotLike(String value) {
            addCriterion("PROV_ID not like", value, "provId");
            return (Criteria) this;
        }

        public Criteria andProvIdIn(List<String> values) {
            addCriterion("PROV_ID in", values, "provId");
            return (Criteria) this;
        }

        public Criteria andProvIdNotIn(List<String> values) {
            addCriterion("PROV_ID not in", values, "provId");
            return (Criteria) this;
        }

        public Criteria andProvIdBetween(String value1, String value2) {
            addCriterion("PROV_ID between", value1, value2, "provId");
            return (Criteria) this;
        }

        public Criteria andProvIdNotBetween(String value1, String value2) {
            addCriterion("PROV_ID not between", value1, value2, "provId");
            return (Criteria) this;
        }

        public Criteria andProvNameIsNull() {
            addCriterion("PROV_NAME is null");
            return (Criteria) this;
        }

        public Criteria andProvNameIsNotNull() {
            addCriterion("PROV_NAME is not null");
            return (Criteria) this;
        }

        public Criteria andProvNameEqualTo(String value) {
            addCriterion("PROV_NAME =", value, "provName");
            return (Criteria) this;
        }

        public Criteria andProvNameNotEqualTo(String value) {
            addCriterion("PROV_NAME <>", value, "provName");
            return (Criteria) this;
        }

        public Criteria andProvNameGreaterThan(String value) {
            addCriterion("PROV_NAME >", value, "provName");
            return (Criteria) this;
        }

        public Criteria andProvNameGreaterThanOrEqualTo(String value) {
            addCriterion("PROV_NAME >=", value, "provName");
            return (Criteria) this;
        }

        public Criteria andProvNameLessThan(String value) {
            addCriterion("PROV_NAME <", value, "provName");
            return (Criteria) this;
        }

        public Criteria andProvNameLessThanOrEqualTo(String value) {
            addCriterion("PROV_NAME <=", value, "provName");
            return (Criteria) this;
        }

        public Criteria andProvNameLike(String value) {
            addCriterion("PROV_NAME like", value, "provName");
            return (Criteria) this;
        }

        public Criteria andProvNameNotLike(String value) {
            addCriterion("PROV_NAME not like", value, "provName");
            return (Criteria) this;
        }

        public Criteria andProvNameIn(List<String> values) {
            addCriterion("PROV_NAME in", values, "provName");
            return (Criteria) this;
        }

        public Criteria andProvNameNotIn(List<String> values) {
            addCriterion("PROV_NAME not in", values, "provName");
            return (Criteria) this;
        }

        public Criteria andProvNameBetween(String value1, String value2) {
            addCriterion("PROV_NAME between", value1, value2, "provName");
            return (Criteria) this;
        }

        public Criteria andProvNameNotBetween(String value1, String value2) {
            addCriterion("PROV_NAME not between", value1, value2, "provName");
            return (Criteria) this;
        }

        public Criteria andYtdIsNull() {
            addCriterion("YTD is null");
            return (Criteria) this;
        }

        public Criteria andYtdIsNotNull() {
            addCriterion("YTD is not null");
            return (Criteria) this;
        }

        public Criteria andYtdEqualTo(Long value) {
            addCriterion("YTD =", value, "ytd");
            return (Criteria) this;
        }

        public Criteria andYtdNotEqualTo(Long value) {
            addCriterion("YTD <>", value, "ytd");
            return (Criteria) this;
        }

        public Criteria andYtdGreaterThan(Long value) {
            addCriterion("YTD >", value, "ytd");
            return (Criteria) this;
        }

        public Criteria andYtdGreaterThanOrEqualTo(Long value) {
            addCriterion("YTD >=", value, "ytd");
            return (Criteria) this;
        }

        public Criteria andYtdLessThan(Long value) {
            addCriterion("YTD <", value, "ytd");
            return (Criteria) this;
        }

        public Criteria andYtdLessThanOrEqualTo(Long value) {
            addCriterion("YTD <=", value, "ytd");
            return (Criteria) this;
        }

        public Criteria andYtdIn(List<Long> values) {
            addCriterion("YTD in", values, "ytd");
            return (Criteria) this;
        }

        public Criteria andYtdNotIn(List<Long> values) {
            addCriterion("YTD not in", values, "ytd");
            return (Criteria) this;
        }

        public Criteria andYtdBetween(Long value1, Long value2) {
            addCriterion("YTD between", value1, value2, "ytd");
            return (Criteria) this;
        }

        public Criteria andYtdNotBetween(Long value1, Long value2) {
            addCriterion("YTD not between", value1, value2, "ytd");
            return (Criteria) this;
        }

        public Criteria andDAmtIsNull() {
            addCriterion("D_AMT is null");
            return (Criteria) this;
        }

        public Criteria andDAmtIsNotNull() {
            addCriterion("D_AMT is not null");
            return (Criteria) this;
        }

        public Criteria andDAmtEqualTo(Long value) {
            addCriterion("D_AMT =", value, "dAmt");
            return (Criteria) this;
        }

        public Criteria andDAmtNotEqualTo(Long value) {
            addCriterion("D_AMT <>", value, "dAmt");
            return (Criteria) this;
        }

        public Criteria andDAmtGreaterThan(Long value) {
            addCriterion("D_AMT >", value, "dAmt");
            return (Criteria) this;
        }

        public Criteria andDAmtGreaterThanOrEqualTo(Long value) {
            addCriterion("D_AMT >=", value, "dAmt");
            return (Criteria) this;
        }

        public Criteria andDAmtLessThan(Long value) {
            addCriterion("D_AMT <", value, "dAmt");
            return (Criteria) this;
        }

        public Criteria andDAmtLessThanOrEqualTo(Long value) {
            addCriterion("D_AMT <=", value, "dAmt");
            return (Criteria) this;
        }

        public Criteria andDAmtIn(List<Long> values) {
            addCriterion("D_AMT in", values, "dAmt");
            return (Criteria) this;
        }

        public Criteria andDAmtNotIn(List<Long> values) {
            addCriterion("D_AMT not in", values, "dAmt");
            return (Criteria) this;
        }

        public Criteria andDAmtBetween(Long value1, Long value2) {
            addCriterion("D_AMT between", value1, value2, "dAmt");
            return (Criteria) this;
        }

        public Criteria andDAmtNotBetween(Long value1, Long value2) {
            addCriterion("D_AMT not between", value1, value2, "dAmt");
            return (Criteria) this;
        }

        public Criteria andCAmtIsNull() {
            addCriterion("C_AMT is null");
            return (Criteria) this;
        }

        public Criteria andCAmtIsNotNull() {
            addCriterion("C_AMT is not null");
            return (Criteria) this;
        }

        public Criteria andCAmtEqualTo(Long value) {
            addCriterion("C_AMT =", value, "cAmt");
            return (Criteria) this;
        }

        public Criteria andCAmtNotEqualTo(Long value) {
            addCriterion("C_AMT <>", value, "cAmt");
            return (Criteria) this;
        }

        public Criteria andCAmtGreaterThan(Long value) {
            addCriterion("C_AMT >", value, "cAmt");
            return (Criteria) this;
        }

        public Criteria andCAmtGreaterThanOrEqualTo(Long value) {
            addCriterion("C_AMT >=", value, "cAmt");
            return (Criteria) this;
        }

        public Criteria andCAmtLessThan(Long value) {
            addCriterion("C_AMT <", value, "cAmt");
            return (Criteria) this;
        }

        public Criteria andCAmtLessThanOrEqualTo(Long value) {
            addCriterion("C_AMT <=", value, "cAmt");
            return (Criteria) this;
        }

        public Criteria andCAmtIn(List<Long> values) {
            addCriterion("C_AMT in", values, "cAmt");
            return (Criteria) this;
        }

        public Criteria andCAmtNotIn(List<Long> values) {
            addCriterion("C_AMT not in", values, "cAmt");
            return (Criteria) this;
        }

        public Criteria andCAmtBetween(Long value1, Long value2) {
            addCriterion("C_AMT between", value1, value2, "cAmt");
            return (Criteria) this;
        }

        public Criteria andCAmtNotBetween(Long value1, Long value2) {
            addCriterion("C_AMT not between", value1, value2, "cAmt");
            return (Criteria) this;
        }

        public Criteria andPtdIsNull() {
            addCriterion("PTD is null");
            return (Criteria) this;
        }

        public Criteria andPtdIsNotNull() {
            addCriterion("PTD is not null");
            return (Criteria) this;
        }

        public Criteria andPtdEqualTo(Short value) {
            addCriterion("PTD =", value, "ptd");
            return (Criteria) this;
        }

        public Criteria andPtdNotEqualTo(Short value) {
            addCriterion("PTD <>", value, "ptd");
            return (Criteria) this;
        }

        public Criteria andPtdGreaterThan(Short value) {
            addCriterion("PTD >", value, "ptd");
            return (Criteria) this;
        }

        public Criteria andPtdGreaterThanOrEqualTo(Short value) {
            addCriterion("PTD >=", value, "ptd");
            return (Criteria) this;
        }

        public Criteria andPtdLessThan(Short value) {
            addCriterion("PTD <", value, "ptd");
            return (Criteria) this;
        }

        public Criteria andPtdLessThanOrEqualTo(Short value) {
            addCriterion("PTD <=", value, "ptd");
            return (Criteria) this;
        }

        public Criteria andPtdIn(List<Short> values) {
            addCriterion("PTD in", values, "ptd");
            return (Criteria) this;
        }

        public Criteria andPtdNotIn(List<Short> values) {
            addCriterion("PTD not in", values, "ptd");
            return (Criteria) this;
        }

        public Criteria andPtdBetween(Short value1, Short value2) {
            addCriterion("PTD between", value1, value2, "ptd");
            return (Criteria) this;
        }

        public Criteria andPtdNotBetween(Short value1, Short value2) {
            addCriterion("PTD not between", value1, value2, "ptd");
            return (Criteria) this;
        }

        public Criteria andPeriodIsNull() {
            addCriterion("PERIOD is null");
            return (Criteria) this;
        }

        public Criteria andPeriodIsNotNull() {
            addCriterion("PERIOD is not null");
            return (Criteria) this;
        }

        public Criteria andPeriodEqualTo(String value) {
            addCriterion("PERIOD =", value, "period");
            return (Criteria) this;
        }

        public Criteria andPeriodNotEqualTo(String value) {
            addCriterion("PERIOD <>", value, "period");
            return (Criteria) this;
        }

        public Criteria andPeriodGreaterThan(String value) {
            addCriterion("PERIOD >", value, "period");
            return (Criteria) this;
        }

        public Criteria andPeriodGreaterThanOrEqualTo(String value) {
            addCriterion("PERIOD >=", value, "period");
            return (Criteria) this;
        }

        public Criteria andPeriodLessThan(String value) {
            addCriterion("PERIOD <", value, "period");
            return (Criteria) this;
        }

        public Criteria andPeriodLessThanOrEqualTo(String value) {
            addCriterion("PERIOD <=", value, "period");
            return (Criteria) this;
        }

        public Criteria andPeriodLike(String value) {
            addCriterion("PERIOD like", value, "period");
            return (Criteria) this;
        }

        public Criteria andPeriodNotLike(String value) {
            addCriterion("PERIOD not like", value, "period");
            return (Criteria) this;
        }

        public Criteria andPeriodIn(List<String> values) {
            addCriterion("PERIOD in", values, "period");
            return (Criteria) this;
        }

        public Criteria andPeriodNotIn(List<String> values) {
            addCriterion("PERIOD not in", values, "period");
            return (Criteria) this;
        }

        public Criteria andPeriodBetween(String value1, String value2) {
            addCriterion("PERIOD between", value1, value2, "period");
            return (Criteria) this;
        }

        public Criteria andPeriodNotBetween(String value1, String value2) {
            addCriterion("PERIOD not between", value1, value2, "period");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table CRM_COST_BALANCES_V
     *
     * @mbggenerated do_not_delete_during_merge Wed Sep 14 14:23:08 CST 2016
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table CRM_COST_BALANCES_V
     *
     * @mbggenerated Wed Sep 14 14:23:08 CST 2016
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}