package com.hhnz.monitor.mapper;

import com.hhnz.monitor.model.CrmTaskMain;
import com.hhnz.monitor.model.CrmTaskMainExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CrmTaskMainMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CRM_TASK_MAIN
     *
     * @mbggenerated Fri Sep 02 10:26:21 CST 2016
     */
    int countByExample(CrmTaskMainExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CRM_TASK_MAIN
     *
     * @mbggenerated Fri Sep 02 10:26:21 CST 2016
     */
    int deleteByExample(CrmTaskMainExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CRM_TASK_MAIN
     *
     * @mbggenerated Fri Sep 02 10:26:21 CST 2016
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CRM_TASK_MAIN
     *
     * @mbggenerated Fri Sep 02 10:26:21 CST 2016
     */
    int insert(CrmTaskMain record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CRM_TASK_MAIN
     *
     * @mbggenerated Fri Sep 02 10:26:21 CST 2016
     */
    int insertSelective(CrmTaskMain record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CRM_TASK_MAIN
     *
     * @mbggenerated Fri Sep 02 10:26:21 CST 2016
     */
    List<CrmTaskMain> selectByExample(CrmTaskMainExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CRM_TASK_MAIN
     *
     * @mbggenerated Fri Sep 02 10:26:21 CST 2016
     */
    CrmTaskMain selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CRM_TASK_MAIN
     *
     * @mbggenerated Fri Sep 02 10:26:21 CST 2016
     */
    int updateByExampleSelective(@Param("record") CrmTaskMain record, @Param("example") CrmTaskMainExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CRM_TASK_MAIN
     *
     * @mbggenerated Fri Sep 02 10:26:21 CST 2016
     */
    int updateByExample(@Param("record") CrmTaskMain record, @Param("example") CrmTaskMainExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CRM_TASK_MAIN
     *
     * @mbggenerated Fri Sep 02 10:26:21 CST 2016
     */
    int updateByPrimaryKeySelective(CrmTaskMain record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CRM_TASK_MAIN
     *
     * @mbggenerated Fri Sep 02 10:26:21 CST 2016
     */
    int updateByPrimaryKey(CrmTaskMain record);
}