CREATE OR REPLACE VIEW OM_ORDER_HEADERS_ALL_V AS
SELECT OH."ID",
       OH."ORGANIZATION_ID",
       OH."MERCH_CUST_ID",
       OH."SHIP_ID",
       OH."CREATE_TS",
       OH."CREATE_OID",
       OH."UPDATE_TS",
       OH."UPDATE_OID",
       OH."STATES",
       OH."INVOICE_NUMBER",
       OH."REGION_ID",
       OH."PROVI_ID",
       OH."ORDER_AMT",
       OH."DISCOUNT_AMT",
       OH."AMT",
       OH."STATION_ID",
       OH."BILL_TO",
       OH."ATTRIBUTE1",
       OH."ATTRIBUTE2",
       OH."ATTRIBUTE3",
       OH."ATTRIBUTE4",
       OH."ATTRIBUTE5",
       OH."SALESREP_ID",
       OH."SAP_ORDER_ID",
       OH."REMARK",
       OH."HB_AMT",
       OH."CASH_AMT",
       OH."CREDIT_AMT",
       (SELECT SO.NAME
          FROM CRM_SALES_ORGANIZATION SO
         WHERE SO.ID = SUBSTR(OH.ORGANIZATION_ID, 0, 5)) AS ORGANIZATION_NAME, --销售组织
       (SELECT MCB.NAME
          FROM C_MERCH_CUST_BASE MCB
         WHERE MCB.ID = OH.MERCH_CUST_ID) AS MERCH_CUST_NAME, --客户
       SUBSTR(CS.ORGANIZATION_ID, 0, 7) AS SALES_AREA_ID,
       (SELECT T.NAME
          FROM CRM_SALES_ORGANIZATION T
         WHERE T.ID = SUBSTR(CS.ORGANIZATION_ID, 0, 7)) AS SALES_AREA_NAME,
       SUBSTR(CS.ORGANIZATION_ID, 0, 9) AS SALES_PROV_ID,
       (SELECT T.NAME
          FROM CRM_SALES_ORGANIZATION T
         WHERE T.ID = SUBSTR(CS.ORGANIZATION_ID, 0, 9)) AS SALES_PROV_NAME,
       (SELECT E.NAME FROM T_EMPLOYEE E WHERE E.ID = OH.CREATE_OID) AS SALESMAN --销售人员
  FROM OM_ORDER_HEADERS_ALL OH 
  LEFT JOIN crm_station CS ON cs.id = oh.station_id;