CREATE OR REPLACE VIEW T_FACTORY_V AS SELECT
	(select name from CRM_SALES_ORGANIZATION where id=SUBSTR(f.ORGANIZATION_ID, 0, 3)) || '-' || cso. NAME orgname,
	f.ID,f.NAME,f.ZIP_CODE,f.CITY,f.ABBR_NAME,f.RETRIEVAL1,f.RETRIEVAL2,f.ORGANIZATION_ID,f.LEADER_NAME,f.CONTACT_NAME,f.CONTACT_TEL
FROM
	T_FACTORY f,
	CRM_SALES_ORGANIZATION cso
WHERE
	f.ORGANIZATION_ID = CSO. ID;

commit;