create or replace view CRM_BUDGET_MAIN_V as SELECT
	CSO1. NAME orgname,
	CSO2. NAME regionname,
	CSO3. NAME provincename,
	CMB. NAME custname,
	CBM."ID",CBM."ORGANIZATION_ID",CBM."COST_TYPE",CBM."COST_SUBJECT",CBM."MERCH_CUST_ID",CBM."ORG_ID",CBM."REGION_ID",CBM."PROVINCE_ID",CBM."AMT_1",CBM."AMT_2",CBM."AMT_3",CBM."AMT_4",CBM."AMT_5",CBM."AMT_6",CBM."AMT_7",CBM."AMT_8",CBM."AMT_9",CBM."AMT_10",CBM."AMT_11",CBM."AMT_12",CBM."AMT",CBM."CREATE_TS",CBM."CREATE_OID",CBM."TYPE",CBM."PERIOD",CBM."ATTRIBUTE1",CBM."ATTRIBUTE2",CBM."ATTRIBUTE3",CBM."ATTRIBUTE4",CBM."ATTRIBUTE5",CBM."SUBJECT_NAME",CBM."STATES"
FROM
	CRM_BUDGET_MAIN cbm,
	CRM_SALES_ORGANIZATION cso1,
	CRM_SALES_ORGANIZATION cso2,
	CRM_SALES_ORGANIZATION cso3,
	C_MERCH_CUST_BASE cmb
WHERE
	CBM.MERCH_CUST_ID = CMB. ID
AND CBM.ORGANIZATION_ID = CSO1. ID
AND CBM.REGION_ID = CSO2. ID
AND CBM.PROVINCE_ID = cso3. ID;
commit;