package com.hhnz.logistics.mapper;

import com.hhnz.logistics.model.TLogisticsArea;
import com.hhnz.logistics.model.TLogisticsAreaExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TLogisticsAreaMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_LOGISTICS_AREA
     *
     * @mbggenerated Fri Sep 08 16:00:23 CST 2017
     */
    int countByExample(TLogisticsAreaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_LOGISTICS_AREA
     *
     * @mbggenerated Fri Sep 08 16:00:23 CST 2017
     */
    int deleteByExample(TLogisticsAreaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_LOGISTICS_AREA
     *
     * @mbggenerated Fri Sep 08 16:00:23 CST 2017
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_LOGISTICS_AREA
     *
     * @mbggenerated Fri Sep 08 16:00:23 CST 2017
     */
    int insert(TLogisticsArea record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_LOGISTICS_AREA
     *
     * @mbggenerated Fri Sep 08 16:00:23 CST 2017
     */
    int insertSelective(TLogisticsArea record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_LOGISTICS_AREA
     *
     * @mbggenerated Fri Sep 08 16:00:23 CST 2017
     */
    List<TLogisticsArea> selectByExample(TLogisticsAreaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_LOGISTICS_AREA
     *
     * @mbggenerated Fri Sep 08 16:00:23 CST 2017
     */
    TLogisticsArea selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_LOGISTICS_AREA
     *
     * @mbggenerated Fri Sep 08 16:00:23 CST 2017
     */
    int updateByExampleSelective(@Param("record") TLogisticsArea record, @Param("example") TLogisticsAreaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_LOGISTICS_AREA
     *
     * @mbggenerated Fri Sep 08 16:00:23 CST 2017
     */
    int updateByExample(@Param("record") TLogisticsArea record, @Param("example") TLogisticsAreaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_LOGISTICS_AREA
     *
     * @mbggenerated Fri Sep 08 16:00:23 CST 2017
     */
    int updateByPrimaryKeySelective(TLogisticsArea record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_LOGISTICS_AREA
     *
     * @mbggenerated Fri Sep 08 16:00:23 CST 2017
     */
    int updateByPrimaryKey(TLogisticsArea record);
}