package com.hhnz.salepolicy.model;

import java.math.BigDecimal;
import java.util.Date;

import org.springframework.format.annotation.DateTimeFormat;

public class OmPolicyHeaders {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column OM_POLICY_HEADERS.ID
     *
     * @mbggenerated Tue Sep 06 09:20:12 CST 2016
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column OM_POLICY_HEADERS.DEPT
     *
     * @mbggenerated Tue Sep 06 09:20:12 CST 2016
     */
    private String dept;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column OM_POLICY_HEADERS.B_DATE
     *
     * @mbggenerated Tue Sep 06 09:20:12 CST 2016
     */
    @DateTimeFormat(pattern = "yyyy-MM-dd")
    private Date bDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column OM_POLICY_HEADERS.E_DATE
     *
     * @mbggenerated Tue Sep 06 09:20:12 CST 2016
     */
    @DateTimeFormat(pattern = "yyyy-MM-dd")
    private Date eDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column OM_POLICY_HEADERS.DESCRIPTION
     *
     * @mbggenerated Tue Sep 06 09:20:12 CST 2016
     */
    private String description;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column OM_POLICY_HEADERS.ORGANIZATION_ID
     *
     * @mbggenerated Tue Sep 06 09:20:12 CST 2016
     */
    private String organizationId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column OM_POLICY_HEADERS.AMT
     *
     * @mbggenerated Tue Sep 06 09:20:12 CST 2016
     */
    private BigDecimal amt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column OM_POLICY_HEADERS.COST_SUBJECTID
     *
     * @mbggenerated Tue Sep 06 09:20:12 CST 2016
     */
    private String costSubjectid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column OM_POLICY_HEADERS.STATES
     *
     * @mbggenerated Tue Sep 06 09:20:12 CST 2016
     */
    private String states;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column OM_POLICY_HEADERS.BALANCE_AMT
     *
     * @mbggenerated Tue Sep 06 09:20:12 CST 2016
     */
    private BigDecimal balanceAmt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column OM_POLICY_HEADERS.CREATE_TS
     *
     * @mbggenerated Tue Sep 06 09:20:12 CST 2016
     */
    private Date createTs;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column OM_POLICY_HEADERS.CREATE_OID
     *
     * @mbggenerated Tue Sep 06 09:20:12 CST 2016
     */
    private Long createOid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column OM_POLICY_HEADERS.AUDIT_TS
     *
     * @mbggenerated Tue Sep 06 09:20:12 CST 2016
     */
    private Date auditTs;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column OM_POLICY_HEADERS.AUDIT_OID
     *
     * @mbggenerated Tue Sep 06 09:20:12 CST 2016
     */
    private Long auditOid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column OM_POLICY_HEADERS.COST_TYPEID
     *
     * @mbggenerated Tue Sep 06 09:20:12 CST 2016
     */
    private String costTypeid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column OM_POLICY_HEADERS.POLICY_TYPE
     *
     * @mbggenerated Tue Sep 06 09:20:12 CST 2016
     */
    private Long policyType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column OM_POLICY_HEADERS.PROCESS_ID
     *
     * @mbggenerated Tue Sep 06 09:20:12 CST 2016
     */
    private String processId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column OM_POLICY_HEADERS.ATTRIBUTE1
     *
     * @mbggenerated Tue Sep 06 09:20:12 CST 2016
     */
    private String attribute1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column OM_POLICY_HEADERS.ATTRBUTE2
     *
     * @mbggenerated Tue Sep 06 09:20:12 CST 2016
     */
    private String attrbute2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column OM_POLICY_HEADERS.ATTRIBUTE3
     *
     * @mbggenerated Tue Sep 06 09:20:12 CST 2016
     */
    private String attribute3;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column OM_POLICY_HEADERS.ATTRIBUTE4
     *
     * @mbggenerated Tue Sep 06 09:20:12 CST 2016
     */
    private String attribute4;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column OM_POLICY_HEADERS.ATTRIBUTE5
     *
     * @mbggenerated Tue Sep 06 09:20:12 CST 2016
     */
    private String attribute5;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column OM_POLICY_HEADERS.ID
     *
     * @return the value of OM_POLICY_HEADERS.ID
     *
     * @mbggenerated Tue Sep 06 09:20:12 CST 2016
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column OM_POLICY_HEADERS.ID
     *
     * @param id the value for OM_POLICY_HEADERS.ID
     *
     * @mbggenerated Tue Sep 06 09:20:12 CST 2016
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column OM_POLICY_HEADERS.DEPT
     *
     * @return the value of OM_POLICY_HEADERS.DEPT
     *
     * @mbggenerated Tue Sep 06 09:20:12 CST 2016
     */
    public String getDept() {
        return dept;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column OM_POLICY_HEADERS.DEPT
     *
     * @param dept the value for OM_POLICY_HEADERS.DEPT
     *
     * @mbggenerated Tue Sep 06 09:20:12 CST 2016
     */
    public void setDept(String dept) {
        this.dept = dept;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column OM_POLICY_HEADERS.B_DATE
     *
     * @return the value of OM_POLICY_HEADERS.B_DATE
     *
     * @mbggenerated Tue Sep 06 09:20:12 CST 2016
     */
    public Date getbDate() {
        return bDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column OM_POLICY_HEADERS.B_DATE
     *
     * @param bDate the value for OM_POLICY_HEADERS.B_DATE
     *
     * @mbggenerated Tue Sep 06 09:20:12 CST 2016
     */
    public void setbDate(Date bDate) {
        this.bDate = bDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column OM_POLICY_HEADERS.E_DATE
     *
     * @return the value of OM_POLICY_HEADERS.E_DATE
     *
     * @mbggenerated Tue Sep 06 09:20:12 CST 2016
     */
    public Date geteDate() {
        return eDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column OM_POLICY_HEADERS.E_DATE
     *
     * @param eDate the value for OM_POLICY_HEADERS.E_DATE
     *
     * @mbggenerated Tue Sep 06 09:20:12 CST 2016
     */
    public void seteDate(Date eDate) {
        this.eDate = eDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column OM_POLICY_HEADERS.DESCRIPTION
     *
     * @return the value of OM_POLICY_HEADERS.DESCRIPTION
     *
     * @mbggenerated Tue Sep 06 09:20:12 CST 2016
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column OM_POLICY_HEADERS.DESCRIPTION
     *
     * @param description the value for OM_POLICY_HEADERS.DESCRIPTION
     *
     * @mbggenerated Tue Sep 06 09:20:12 CST 2016
     */
    public void setDescription(String description) {
        this.description = description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column OM_POLICY_HEADERS.ORGANIZATION_ID
     *
     * @return the value of OM_POLICY_HEADERS.ORGANIZATION_ID
     *
     * @mbggenerated Tue Sep 06 09:20:12 CST 2016
     */
    public String getOrganizationId() {
        return organizationId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column OM_POLICY_HEADERS.ORGANIZATION_ID
     *
     * @param organizationId the value for OM_POLICY_HEADERS.ORGANIZATION_ID
     *
     * @mbggenerated Tue Sep 06 09:20:12 CST 2016
     */
    public void setOrganizationId(String organizationId) {
        this.organizationId = organizationId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column OM_POLICY_HEADERS.AMT
     *
     * @return the value of OM_POLICY_HEADERS.AMT
     *
     * @mbggenerated Tue Sep 06 09:20:12 CST 2016
     */
    public BigDecimal getAmt() {
        return amt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column OM_POLICY_HEADERS.AMT
     *
     * @param amt the value for OM_POLICY_HEADERS.AMT
     *
     * @mbggenerated Tue Sep 06 09:20:12 CST 2016
     */
    public void setAmt(BigDecimal amt) {
        this.amt = amt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column OM_POLICY_HEADERS.COST_SUBJECTID
     *
     * @return the value of OM_POLICY_HEADERS.COST_SUBJECTID
     *
     * @mbggenerated Tue Sep 06 09:20:12 CST 2016
     */
    public String getCostSubjectid() {
        return costSubjectid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column OM_POLICY_HEADERS.COST_SUBJECTID
     *
     * @param costSubjectid the value for OM_POLICY_HEADERS.COST_SUBJECTID
     *
     * @mbggenerated Tue Sep 06 09:20:12 CST 2016
     */
    public void setCostSubjectid(String costSubjectid) {
        this.costSubjectid = costSubjectid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column OM_POLICY_HEADERS.STATES
     *
     * @return the value of OM_POLICY_HEADERS.STATES
     *
     * @mbggenerated Tue Sep 06 09:20:12 CST 2016
     */
    public String getStates() {
        return states;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column OM_POLICY_HEADERS.STATES
     *
     * @param states the value for OM_POLICY_HEADERS.STATES
     *
     * @mbggenerated Tue Sep 06 09:20:12 CST 2016
     */
    public void setStates(String states) {
        this.states = states;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column OM_POLICY_HEADERS.BALANCE_AMT
     *
     * @return the value of OM_POLICY_HEADERS.BALANCE_AMT
     *
     * @mbggenerated Tue Sep 06 09:20:12 CST 2016
     */
    public BigDecimal getBalanceAmt() {
        return balanceAmt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column OM_POLICY_HEADERS.BALANCE_AMT
     *
     * @param balanceAmt the value for OM_POLICY_HEADERS.BALANCE_AMT
     *
     * @mbggenerated Tue Sep 06 09:20:12 CST 2016
     */
    public void setBalanceAmt(BigDecimal balanceAmt) {
        this.balanceAmt = balanceAmt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column OM_POLICY_HEADERS.CREATE_TS
     *
     * @return the value of OM_POLICY_HEADERS.CREATE_TS
     *
     * @mbggenerated Tue Sep 06 09:20:12 CST 2016
     */
    public Date getCreateTs() {
        return createTs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column OM_POLICY_HEADERS.CREATE_TS
     *
     * @param createTs the value for OM_POLICY_HEADERS.CREATE_TS
     *
     * @mbggenerated Tue Sep 06 09:20:12 CST 2016
     */
    public void setCreateTs(Date createTs) {
        this.createTs = createTs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column OM_POLICY_HEADERS.CREATE_OID
     *
     * @return the value of OM_POLICY_HEADERS.CREATE_OID
     *
     * @mbggenerated Tue Sep 06 09:20:12 CST 2016
     */
    public Long getCreateOid() {
        return createOid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column OM_POLICY_HEADERS.CREATE_OID
     *
     * @param createOid the value for OM_POLICY_HEADERS.CREATE_OID
     *
     * @mbggenerated Tue Sep 06 09:20:12 CST 2016
     */
    public void setCreateOid(Long createOid) {
        this.createOid = createOid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column OM_POLICY_HEADERS.AUDIT_TS
     *
     * @return the value of OM_POLICY_HEADERS.AUDIT_TS
     *
     * @mbggenerated Tue Sep 06 09:20:12 CST 2016
     */
    public Date getAuditTs() {
        return auditTs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column OM_POLICY_HEADERS.AUDIT_TS
     *
     * @param auditTs the value for OM_POLICY_HEADERS.AUDIT_TS
     *
     * @mbggenerated Tue Sep 06 09:20:12 CST 2016
     */
    public void setAuditTs(Date auditTs) {
        this.auditTs = auditTs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column OM_POLICY_HEADERS.AUDIT_OID
     *
     * @return the value of OM_POLICY_HEADERS.AUDIT_OID
     *
     * @mbggenerated Tue Sep 06 09:20:12 CST 2016
     */
    public Long getAuditOid() {
        return auditOid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column OM_POLICY_HEADERS.AUDIT_OID
     *
     * @param auditOid the value for OM_POLICY_HEADERS.AUDIT_OID
     *
     * @mbggenerated Tue Sep 06 09:20:12 CST 2016
     */
    public void setAuditOid(Long auditOid) {
        this.auditOid = auditOid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column OM_POLICY_HEADERS.COST_TYPEID
     *
     * @return the value of OM_POLICY_HEADERS.COST_TYPEID
     *
     * @mbggenerated Tue Sep 06 09:20:12 CST 2016
     */
    public String getCostTypeid() {
        return costTypeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column OM_POLICY_HEADERS.COST_TYPEID
     *
     * @param costTypeid the value for OM_POLICY_HEADERS.COST_TYPEID
     *
     * @mbggenerated Tue Sep 06 09:20:12 CST 2016
     */
    public void setCostTypeid(String costTypeid) {
        this.costTypeid = costTypeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column OM_POLICY_HEADERS.POLICY_TYPE
     *
     * @return the value of OM_POLICY_HEADERS.POLICY_TYPE
     *
     * @mbggenerated Tue Sep 06 09:20:12 CST 2016
     */
    public Long getPolicyType() {
        return policyType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column OM_POLICY_HEADERS.POLICY_TYPE
     *
     * @param policyType the value for OM_POLICY_HEADERS.POLICY_TYPE
     *
     * @mbggenerated Tue Sep 06 09:20:12 CST 2016
     */
    public void setPolicyType(Long policyType) {
        this.policyType = policyType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column OM_POLICY_HEADERS.PROCESS_ID
     *
     * @return the value of OM_POLICY_HEADERS.PROCESS_ID
     *
     * @mbggenerated Tue Sep 06 09:20:12 CST 2016
     */
    public String getProcessId() {
        return processId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column OM_POLICY_HEADERS.PROCESS_ID
     *
     * @param processId the value for OM_POLICY_HEADERS.PROCESS_ID
     *
     * @mbggenerated Tue Sep 06 09:20:12 CST 2016
     */
    public void setProcessId(String processId) {
        this.processId = processId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column OM_POLICY_HEADERS.ATTRIBUTE1
     *
     * @return the value of OM_POLICY_HEADERS.ATTRIBUTE1
     *
     * @mbggenerated Tue Sep 06 09:20:12 CST 2016
     */
    public String getAttribute1() {
        return attribute1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column OM_POLICY_HEADERS.ATTRIBUTE1
     *
     * @param attribute1 the value for OM_POLICY_HEADERS.ATTRIBUTE1
     *
     * @mbggenerated Tue Sep 06 09:20:12 CST 2016
     */
    public void setAttribute1(String attribute1) {
        this.attribute1 = attribute1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column OM_POLICY_HEADERS.ATTRBUTE2
     *
     * @return the value of OM_POLICY_HEADERS.ATTRBUTE2
     *
     * @mbggenerated Tue Sep 06 09:20:12 CST 2016
     */
    public String getAttrbute2() {
        return attrbute2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column OM_POLICY_HEADERS.ATTRBUTE2
     *
     * @param attrbute2 the value for OM_POLICY_HEADERS.ATTRBUTE2
     *
     * @mbggenerated Tue Sep 06 09:20:12 CST 2016
     */
    public void setAttrbute2(String attrbute2) {
        this.attrbute2 = attrbute2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column OM_POLICY_HEADERS.ATTRIBUTE3
     *
     * @return the value of OM_POLICY_HEADERS.ATTRIBUTE3
     *
     * @mbggenerated Tue Sep 06 09:20:12 CST 2016
     */
    public String getAttribute3() {
        return attribute3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column OM_POLICY_HEADERS.ATTRIBUTE3
     *
     * @param attribute3 the value for OM_POLICY_HEADERS.ATTRIBUTE3
     *
     * @mbggenerated Tue Sep 06 09:20:12 CST 2016
     */
    public void setAttribute3(String attribute3) {
        this.attribute3 = attribute3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column OM_POLICY_HEADERS.ATTRIBUTE4
     *
     * @return the value of OM_POLICY_HEADERS.ATTRIBUTE4
     *
     * @mbggenerated Tue Sep 06 09:20:12 CST 2016
     */
    public String getAttribute4() {
        return attribute4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column OM_POLICY_HEADERS.ATTRIBUTE4
     *
     * @param attribute4 the value for OM_POLICY_HEADERS.ATTRIBUTE4
     *
     * @mbggenerated Tue Sep 06 09:20:12 CST 2016
     */
    public void setAttribute4(String attribute4) {
        this.attribute4 = attribute4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column OM_POLICY_HEADERS.ATTRIBUTE5
     *
     * @return the value of OM_POLICY_HEADERS.ATTRIBUTE5
     *
     * @mbggenerated Tue Sep 06 09:20:12 CST 2016
     */
    public String getAttribute5() {
        return attribute5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column OM_POLICY_HEADERS.ATTRIBUTE5
     *
     * @param attribute5 the value for OM_POLICY_HEADERS.ATTRIBUTE5
     *
     * @mbggenerated Tue Sep 06 09:20:12 CST 2016
     */
    public void setAttribute5(String attribute5) {
        this.attribute5 = attribute5;
    }
}