package com.hhnz.customer.mapper;

import com.hhnz.customer.model.CMerchCustDistribution;
import com.hhnz.customer.model.CMerchCustDistributionExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CMerchCustDistributionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table C_MERCH_CUST_DISTRIBUTION
     *
     * @mbggenerated Fri Aug 12 16:39:09 CST 2016
     */
    int countByExample(CMerchCustDistributionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table C_MERCH_CUST_DISTRIBUTION
     *
     * @mbggenerated Fri Aug 12 16:39:09 CST 2016
     */
    int deleteByExample(CMerchCustDistributionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table C_MERCH_CUST_DISTRIBUTION
     *
     * @mbggenerated Fri Aug 12 16:39:09 CST 2016
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table C_MERCH_CUST_DISTRIBUTION
     *
     * @mbggenerated Fri Aug 12 16:39:09 CST 2016
     */
    int insert(CMerchCustDistribution record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table C_MERCH_CUST_DISTRIBUTION
     *
     * @mbggenerated Fri Aug 12 16:39:09 CST 2016
     */
    int insertSelective(CMerchCustDistribution record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table C_MERCH_CUST_DISTRIBUTION
     *
     * @mbggenerated Fri Aug 12 16:39:09 CST 2016
     */
    List<CMerchCustDistribution> selectByExample(CMerchCustDistributionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table C_MERCH_CUST_DISTRIBUTION
     *
     * @mbggenerated Fri Aug 12 16:39:09 CST 2016
     */
    CMerchCustDistribution selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table C_MERCH_CUST_DISTRIBUTION
     *
     * @mbggenerated Fri Aug 12 16:39:09 CST 2016
     */
    int updateByExampleSelective(@Param("record") CMerchCustDistribution record, @Param("example") CMerchCustDistributionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table C_MERCH_CUST_DISTRIBUTION
     *
     * @mbggenerated Fri Aug 12 16:39:09 CST 2016
     */
    int updateByExample(@Param("record") CMerchCustDistribution record, @Param("example") CMerchCustDistributionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table C_MERCH_CUST_DISTRIBUTION
     *
     * @mbggenerated Fri Aug 12 16:39:09 CST 2016
     */
    int updateByPrimaryKeySelective(CMerchCustDistribution record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table C_MERCH_CUST_DISTRIBUTION
     *
     * @mbggenerated Fri Aug 12 16:39:09 CST 2016
     */
    int updateByPrimaryKey(CMerchCustDistribution record);
}