package com.hhnz.customer.mapper;

import com.hhnz.customer.model.CMerchCustContract;
import com.hhnz.customer.model.CMerchCustContractExample;

import java.util.List;

import org.apache.ibatis.annotations.Param;

public interface CMerchCustContractMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table C_MERCH_CUST_CONTRACT
     *
     * @mbggenerated Wed Aug 31 16:38:33 CST 2016
     */
    int countByExample(CMerchCustContractExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table C_MERCH_CUST_CONTRACT
     *
     * @mbggenerated Wed Aug 31 16:38:33 CST 2016
     */
    int deleteByExample(CMerchCustContractExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table C_MERCH_CUST_CONTRACT
     *
     * @mbggenerated Wed Aug 31 16:38:33 CST 2016
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table C_MERCH_CUST_CONTRACT
     *
     * @mbggenerated Wed Aug 31 16:38:33 CST 2016
     */
    int insert(CMerchCustContract record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table C_MERCH_CUST_CONTRACT
     *
     * @mbggenerated Wed Aug 31 16:38:33 CST 2016
     */
    int insertSelective(CMerchCustContract record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table C_MERCH_CUST_CONTRACT
     *
     * @mbggenerated Wed Aug 31 16:38:33 CST 2016
     */
    List<CMerchCustContract> selectByExample(CMerchCustContractExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table C_MERCH_CUST_CONTRACT
     *
     * @mbggenerated Wed Aug 31 16:38:33 CST 2016
     */
    CMerchCustContract selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table C_MERCH_CUST_CONTRACT
     *
     * @mbggenerated Wed Aug 31 16:38:33 CST 2016
     */
    int updateByExampleSelective(@Param("record") CMerchCustContract record, @Param("example") CMerchCustContractExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table C_MERCH_CUST_CONTRACT
     *
     * @mbggenerated Wed Aug 31 16:38:33 CST 2016
     */
    int updateByExample(@Param("record") CMerchCustContract record, @Param("example") CMerchCustContractExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table C_MERCH_CUST_CONTRACT
     *
     * @mbggenerated Wed Aug 31 16:38:33 CST 2016
     */
    int updateByPrimaryKeySelective(CMerchCustContract record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table C_MERCH_CUST_CONTRACT
     *
     * @mbggenerated Wed Aug 31 16:38:33 CST 2016
     */
    int updateByPrimaryKey(CMerchCustContract record);

	int addContractLine(CMerchCustContract record);
}