package com.hhnz.customer.mapper;

import com.hhnz.customer.model.CrmBusinessModel;
import com.hhnz.customer.model.CrmBusinessModelExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CrmBusinessModelMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CRM_BUSINESS_MODEL
     *
     * @mbggenerated Wed Nov 30 14:17:05 CST 2016
     */
    int countByExample(CrmBusinessModelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CRM_BUSINESS_MODEL
     *
     * @mbggenerated Wed Nov 30 14:17:05 CST 2016
     */
    int deleteByExample(CrmBusinessModelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CRM_BUSINESS_MODEL
     *
     * @mbggenerated Wed Nov 30 14:17:05 CST 2016
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CRM_BUSINESS_MODEL
     *
     * @mbggenerated Wed Nov 30 14:17:05 CST 2016
     */
    int insert(CrmBusinessModel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CRM_BUSINESS_MODEL
     *
     * @mbggenerated Wed Nov 30 14:17:05 CST 2016
     */
    int insertSelective(CrmBusinessModel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CRM_BUSINESS_MODEL
     *
     * @mbggenerated Wed Nov 30 14:17:05 CST 2016
     */
    List<CrmBusinessModel> selectByExample(CrmBusinessModelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CRM_BUSINESS_MODEL
     *
     * @mbggenerated Wed Nov 30 14:17:05 CST 2016
     */
    CrmBusinessModel selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CRM_BUSINESS_MODEL
     *
     * @mbggenerated Wed Nov 30 14:17:05 CST 2016
     */
    int updateByExampleSelective(@Param("record") CrmBusinessModel record, @Param("example") CrmBusinessModelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CRM_BUSINESS_MODEL
     *
     * @mbggenerated Wed Nov 30 14:17:05 CST 2016
     */
    int updateByExample(@Param("record") CrmBusinessModel record, @Param("example") CrmBusinessModelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CRM_BUSINESS_MODEL
     *
     * @mbggenerated Wed Nov 30 14:17:05 CST 2016
     */
    int updateByPrimaryKeySelective(CrmBusinessModel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CRM_BUSINESS_MODEL
     *
     * @mbggenerated Wed Nov 30 14:17:05 CST 2016
     */
    int updateByPrimaryKey(CrmBusinessModel record);
}