package com.hhnz.account.mapper;

import com.hhnz.account.model.CMerchCustAccount;
import com.hhnz.account.model.CMerchCustAccountExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CMerchCustAccountMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table C_MERCH_CUST_ACCOUNT
     *
     * @mbggenerated Mon Oct 24 14:39:16 CST 2016
     */
    int countByExample(CMerchCustAccountExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table C_MERCH_CUST_ACCOUNT
     *
     * @mbggenerated Mon Oct 24 14:39:16 CST 2016
     */
    int deleteByExample(CMerchCustAccountExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table C_MERCH_CUST_ACCOUNT
     *
     * @mbggenerated Mon Oct 24 14:39:16 CST 2016
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table C_MERCH_CUST_ACCOUNT
     *
     * @mbggenerated Mon Oct 24 14:39:16 CST 2016
     */
    int insert(CMerchCustAccount record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table C_MERCH_CUST_ACCOUNT
     *
     * @mbggenerated Mon Oct 24 14:39:16 CST 2016
     */
    int insertSelective(CMerchCustAccount record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table C_MERCH_CUST_ACCOUNT
     *
     * @mbggenerated Mon Oct 24 14:39:16 CST 2016
     */
    List<CMerchCustAccount> selectByExample(CMerchCustAccountExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table C_MERCH_CUST_ACCOUNT
     *
     * @mbggenerated Mon Oct 24 14:39:16 CST 2016
     */
    CMerchCustAccount selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table C_MERCH_CUST_ACCOUNT
     *
     * @mbggenerated Mon Oct 24 14:39:16 CST 2016
     */
    int updateByExampleSelective(@Param("record") CMerchCustAccount record, @Param("example") CMerchCustAccountExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table C_MERCH_CUST_ACCOUNT
     *
     * @mbggenerated Mon Oct 24 14:39:16 CST 2016
     */
    int updateByExample(@Param("record") CMerchCustAccount record, @Param("example") CMerchCustAccountExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table C_MERCH_CUST_ACCOUNT
     *
     * @mbggenerated Mon Oct 24 14:39:16 CST 2016
     */
    int updateByPrimaryKeySelective(CMerchCustAccount record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table C_MERCH_CUST_ACCOUNT
     *
     * @mbggenerated Mon Oct 24 14:39:16 CST 2016
     */
    int updateByPrimaryKey(CMerchCustAccount record);
}