package com.hhnz.report.model;

import java.util.Date;

public class Accountdetailsreport {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ACCOUNTDETAILSREPORT.MERCHN_NAME
     *
     * @mbggenerated Thu Nov 17 09:44:16 CST 2016
     */
    private String merchnName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ACCOUNTDETAILSREPORT.ORGNAME
     *
     * @mbggenerated Thu Nov 17 09:44:16 CST 2016
     */
    private String orgname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ACCOUNTDETAILSREPORT.ID
     *
     * @mbggenerated Thu Nov 17 09:44:16 CST 2016
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ACCOUNTDETAILSREPORT.MERCH_CUST_ID
     *
     * @mbggenerated Thu Nov 17 09:44:16 CST 2016
     */
    private Long merchCustId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ACCOUNTDETAILSREPORT.ORGANIZATION_ID
     *
     * @mbggenerated Thu Nov 17 09:44:16 CST 2016
     */
    private String organizationId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ACCOUNTDETAILSREPORT.TYPE
     *
     * @mbggenerated Thu Nov 17 09:44:16 CST 2016
     */
    private String type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ACCOUNTDETAILSREPORT.D_AMT
     *
     * @mbggenerated Thu Nov 17 09:44:16 CST 2016
     */
    private Long dAmt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ACCOUNTDETAILSREPORT.C_AMT
     *
     * @mbggenerated Thu Nov 17 09:44:16 CST 2016
     */
    private Long cAmt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ACCOUNTDETAILSREPORT.ACCOUNT_TYPE
     *
     * @mbggenerated Thu Nov 17 09:44:16 CST 2016
     */
    private String accountType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ACCOUNTDETAILSREPORT.ORDER_ID
     *
     * @mbggenerated Thu Nov 17 09:44:16 CST 2016
     */
    private Long orderId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ACCOUNTDETAILSREPORT.PERIOD
     *
     * @mbggenerated Thu Nov 17 09:44:16 CST 2016
     */
    private String period;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ACCOUNTDETAILSREPORT.CREATE_TS
     *
     * @mbggenerated Thu Nov 17 09:44:16 CST 2016
     */
    private Date createTs;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ACCOUNTDETAILSREPORT.CREATER
     *
     * @mbggenerated Thu Nov 17 09:44:16 CST 2016
     */
    private String creater;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ACCOUNTDETAILSREPORT.ATTRIBUTE1
     *
     * @mbggenerated Thu Nov 17 09:44:16 CST 2016
     */
    private String attribute1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ACCOUNTDETAILSREPORT.ATTRIBUTE2
     *
     * @mbggenerated Thu Nov 17 09:44:16 CST 2016
     */
    private String attribute2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ACCOUNTDETAILSREPORT.ATTRIBUTE3
     *
     * @mbggenerated Thu Nov 17 09:44:16 CST 2016
     */
    private String attribute3;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ACCOUNTDETAILSREPORT.ATTRIBUTE4
     *
     * @mbggenerated Thu Nov 17 09:44:16 CST 2016
     */
    private String attribute4;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ACCOUNTDETAILSREPORT.ATTRIBUTE5
     *
     * @mbggenerated Thu Nov 17 09:44:16 CST 2016
     */
    private String attribute5;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ACCOUNTDETAILSREPORT.SAP_VOUCHER_ID
     *
     * @mbggenerated Thu Nov 17 09:44:16 CST 2016
     */
    private String sapVoucherId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ACCOUNTDETAILSREPORT.MERCHN_NAME
     *
     * @return the value of ACCOUNTDETAILSREPORT.MERCHN_NAME
     *
     * @mbggenerated Thu Nov 17 09:44:16 CST 2016
     */
    public String getMerchnName() {
        return merchnName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ACCOUNTDETAILSREPORT.MERCHN_NAME
     *
     * @param merchnName the value for ACCOUNTDETAILSREPORT.MERCHN_NAME
     *
     * @mbggenerated Thu Nov 17 09:44:16 CST 2016
     */
    public void setMerchnName(String merchnName) {
        this.merchnName = merchnName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ACCOUNTDETAILSREPORT.ORGNAME
     *
     * @return the value of ACCOUNTDETAILSREPORT.ORGNAME
     *
     * @mbggenerated Thu Nov 17 09:44:16 CST 2016
     */
    public String getOrgname() {
        return orgname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ACCOUNTDETAILSREPORT.ORGNAME
     *
     * @param orgname the value for ACCOUNTDETAILSREPORT.ORGNAME
     *
     * @mbggenerated Thu Nov 17 09:44:16 CST 2016
     */
    public void setOrgname(String orgname) {
        this.orgname = orgname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ACCOUNTDETAILSREPORT.ID
     *
     * @return the value of ACCOUNTDETAILSREPORT.ID
     *
     * @mbggenerated Thu Nov 17 09:44:16 CST 2016
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ACCOUNTDETAILSREPORT.ID
     *
     * @param id the value for ACCOUNTDETAILSREPORT.ID
     *
     * @mbggenerated Thu Nov 17 09:44:16 CST 2016
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ACCOUNTDETAILSREPORT.MERCH_CUST_ID
     *
     * @return the value of ACCOUNTDETAILSREPORT.MERCH_CUST_ID
     *
     * @mbggenerated Thu Nov 17 09:44:16 CST 2016
     */
    public Long getMerchCustId() {
        return merchCustId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ACCOUNTDETAILSREPORT.MERCH_CUST_ID
     *
     * @param merchCustId the value for ACCOUNTDETAILSREPORT.MERCH_CUST_ID
     *
     * @mbggenerated Thu Nov 17 09:44:16 CST 2016
     */
    public void setMerchCustId(Long merchCustId) {
        this.merchCustId = merchCustId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ACCOUNTDETAILSREPORT.ORGANIZATION_ID
     *
     * @return the value of ACCOUNTDETAILSREPORT.ORGANIZATION_ID
     *
     * @mbggenerated Thu Nov 17 09:44:16 CST 2016
     */
    public String getOrganizationId() {
        return organizationId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ACCOUNTDETAILSREPORT.ORGANIZATION_ID
     *
     * @param organizationId the value for ACCOUNTDETAILSREPORT.ORGANIZATION_ID
     *
     * @mbggenerated Thu Nov 17 09:44:16 CST 2016
     */
    public void setOrganizationId(String organizationId) {
        this.organizationId = organizationId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ACCOUNTDETAILSREPORT.TYPE
     *
     * @return the value of ACCOUNTDETAILSREPORT.TYPE
     *
     * @mbggenerated Thu Nov 17 09:44:16 CST 2016
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ACCOUNTDETAILSREPORT.TYPE
     *
     * @param type the value for ACCOUNTDETAILSREPORT.TYPE
     *
     * @mbggenerated Thu Nov 17 09:44:16 CST 2016
     */
    public void setType(String type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ACCOUNTDETAILSREPORT.D_AMT
     *
     * @return the value of ACCOUNTDETAILSREPORT.D_AMT
     *
     * @mbggenerated Thu Nov 17 09:44:16 CST 2016
     */
    public Long getdAmt() {
        return dAmt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ACCOUNTDETAILSREPORT.D_AMT
     *
     * @param dAmt the value for ACCOUNTDETAILSREPORT.D_AMT
     *
     * @mbggenerated Thu Nov 17 09:44:16 CST 2016
     */
    public void setdAmt(Long dAmt) {
        this.dAmt = dAmt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ACCOUNTDETAILSREPORT.C_AMT
     *
     * @return the value of ACCOUNTDETAILSREPORT.C_AMT
     *
     * @mbggenerated Thu Nov 17 09:44:16 CST 2016
     */
    public Long getcAmt() {
        return cAmt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ACCOUNTDETAILSREPORT.C_AMT
     *
     * @param cAmt the value for ACCOUNTDETAILSREPORT.C_AMT
     *
     * @mbggenerated Thu Nov 17 09:44:16 CST 2016
     */
    public void setcAmt(Long cAmt) {
        this.cAmt = cAmt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ACCOUNTDETAILSREPORT.ACCOUNT_TYPE
     *
     * @return the value of ACCOUNTDETAILSREPORT.ACCOUNT_TYPE
     *
     * @mbggenerated Thu Nov 17 09:44:16 CST 2016
     */
    public String getAccountType() {
        return accountType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ACCOUNTDETAILSREPORT.ACCOUNT_TYPE
     *
     * @param accountType the value for ACCOUNTDETAILSREPORT.ACCOUNT_TYPE
     *
     * @mbggenerated Thu Nov 17 09:44:16 CST 2016
     */
    public void setAccountType(String accountType) {
        this.accountType = accountType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ACCOUNTDETAILSREPORT.ORDER_ID
     *
     * @return the value of ACCOUNTDETAILSREPORT.ORDER_ID
     *
     * @mbggenerated Thu Nov 17 09:44:16 CST 2016
     */
    public Long getOrderId() {
        return orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ACCOUNTDETAILSREPORT.ORDER_ID
     *
     * @param orderId the value for ACCOUNTDETAILSREPORT.ORDER_ID
     *
     * @mbggenerated Thu Nov 17 09:44:16 CST 2016
     */
    public void setOrderId(Long orderId) {
        this.orderId = orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ACCOUNTDETAILSREPORT.PERIOD
     *
     * @return the value of ACCOUNTDETAILSREPORT.PERIOD
     *
     * @mbggenerated Thu Nov 17 09:44:16 CST 2016
     */
    public String getPeriod() {
        return period;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ACCOUNTDETAILSREPORT.PERIOD
     *
     * @param period the value for ACCOUNTDETAILSREPORT.PERIOD
     *
     * @mbggenerated Thu Nov 17 09:44:16 CST 2016
     */
    public void setPeriod(String period) {
        this.period = period;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ACCOUNTDETAILSREPORT.CREATE_TS
     *
     * @return the value of ACCOUNTDETAILSREPORT.CREATE_TS
     *
     * @mbggenerated Thu Nov 17 09:44:16 CST 2016
     */
    public Date getCreateTs() {
        return createTs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ACCOUNTDETAILSREPORT.CREATE_TS
     *
     * @param createTs the value for ACCOUNTDETAILSREPORT.CREATE_TS
     *
     * @mbggenerated Thu Nov 17 09:44:16 CST 2016
     */
    public void setCreateTs(Date createTs) {
        this.createTs = createTs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ACCOUNTDETAILSREPORT.CREATER
     *
     * @return the value of ACCOUNTDETAILSREPORT.CREATER
     *
     * @mbggenerated Thu Nov 17 09:44:16 CST 2016
     */
    public String getCreater() {
        return creater;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ACCOUNTDETAILSREPORT.CREATER
     *
     * @param creater the value for ACCOUNTDETAILSREPORT.CREATER
     *
     * @mbggenerated Thu Nov 17 09:44:16 CST 2016
     */
    public void setCreater(String creater) {
        this.creater = creater;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ACCOUNTDETAILSREPORT.ATTRIBUTE1
     *
     * @return the value of ACCOUNTDETAILSREPORT.ATTRIBUTE1
     *
     * @mbggenerated Thu Nov 17 09:44:16 CST 2016
     */
    public String getAttribute1() {
        return attribute1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ACCOUNTDETAILSREPORT.ATTRIBUTE1
     *
     * @param attribute1 the value for ACCOUNTDETAILSREPORT.ATTRIBUTE1
     *
     * @mbggenerated Thu Nov 17 09:44:16 CST 2016
     */
    public void setAttribute1(String attribute1) {
        this.attribute1 = attribute1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ACCOUNTDETAILSREPORT.ATTRIBUTE2
     *
     * @return the value of ACCOUNTDETAILSREPORT.ATTRIBUTE2
     *
     * @mbggenerated Thu Nov 17 09:44:16 CST 2016
     */
    public String getAttribute2() {
        return attribute2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ACCOUNTDETAILSREPORT.ATTRIBUTE2
     *
     * @param attribute2 the value for ACCOUNTDETAILSREPORT.ATTRIBUTE2
     *
     * @mbggenerated Thu Nov 17 09:44:16 CST 2016
     */
    public void setAttribute2(String attribute2) {
        this.attribute2 = attribute2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ACCOUNTDETAILSREPORT.ATTRIBUTE3
     *
     * @return the value of ACCOUNTDETAILSREPORT.ATTRIBUTE3
     *
     * @mbggenerated Thu Nov 17 09:44:16 CST 2016
     */
    public String getAttribute3() {
        return attribute3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ACCOUNTDETAILSREPORT.ATTRIBUTE3
     *
     * @param attribute3 the value for ACCOUNTDETAILSREPORT.ATTRIBUTE3
     *
     * @mbggenerated Thu Nov 17 09:44:16 CST 2016
     */
    public void setAttribute3(String attribute3) {
        this.attribute3 = attribute3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ACCOUNTDETAILSREPORT.ATTRIBUTE4
     *
     * @return the value of ACCOUNTDETAILSREPORT.ATTRIBUTE4
     *
     * @mbggenerated Thu Nov 17 09:44:16 CST 2016
     */
    public String getAttribute4() {
        return attribute4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ACCOUNTDETAILSREPORT.ATTRIBUTE4
     *
     * @param attribute4 the value for ACCOUNTDETAILSREPORT.ATTRIBUTE4
     *
     * @mbggenerated Thu Nov 17 09:44:16 CST 2016
     */
    public void setAttribute4(String attribute4) {
        this.attribute4 = attribute4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ACCOUNTDETAILSREPORT.ATTRIBUTE5
     *
     * @return the value of ACCOUNTDETAILSREPORT.ATTRIBUTE5
     *
     * @mbggenerated Thu Nov 17 09:44:16 CST 2016
     */
    public String getAttribute5() {
        return attribute5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ACCOUNTDETAILSREPORT.ATTRIBUTE5
     *
     * @param attribute5 the value for ACCOUNTDETAILSREPORT.ATTRIBUTE5
     *
     * @mbggenerated Thu Nov 17 09:44:16 CST 2016
     */
    public void setAttribute5(String attribute5) {
        this.attribute5 = attribute5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ACCOUNTDETAILSREPORT.SAP_VOUCHER_ID
     *
     * @return the value of ACCOUNTDETAILSREPORT.SAP_VOUCHER_ID
     *
     * @mbggenerated Thu Nov 17 09:44:16 CST 2016
     */
    public String getSapVoucherId() {
        return sapVoucherId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ACCOUNTDETAILSREPORT.SAP_VOUCHER_ID
     *
     * @param sapVoucherId the value for ACCOUNTDETAILSREPORT.SAP_VOUCHER_ID
     *
     * @mbggenerated Thu Nov 17 09:44:16 CST 2016
     */
    public void setSapVoucherId(String sapVoucherId) {
        this.sapVoucherId = sapVoucherId;
    }
}