package com.hhnz.report.model;

public class CMerchCustAccountDetails {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column C_MERCH_CUST_ACCOUNT_DETAILS.NAME
     *
     * @mbggenerated Mon Nov 21 14:38:28 CST 2016
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column C_MERCH_CUST_ACCOUNT_DETAILS.SAP_CUSTOMER_ID
     *
     * @mbggenerated Mon Nov 21 14:38:28 CST 2016
     */
    private String sapCustomerId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column C_MERCH_CUST_ACCOUNT_DETAILS.CUST_TYPE
     *
     * @mbggenerated Mon Nov 21 14:38:28 CST 2016
     */
    private String custType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column C_MERCH_CUST_ACCOUNT_DETAILS.TYPE
     *
     * @mbggenerated Mon Nov 21 14:38:28 CST 2016
     */
    private String type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column C_MERCH_CUST_ACCOUNT_DETAILS.STATION_ID
     *
     * @mbggenerated Mon Nov 21 14:38:28 CST 2016
     */
    private Long stationId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column C_MERCH_CUST_ACCOUNT_DETAILS.PORV_ID
     *
     * @mbggenerated Mon Nov 21 14:38:28 CST 2016
     */
    private String porvId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column C_MERCH_CUST_ACCOUNT_DETAILS.PROVNAME
     *
     * @mbggenerated Mon Nov 21 14:38:28 CST 2016
     */
    private String provname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column C_MERCH_CUST_ACCOUNT_DETAILS.REGION_ID
     *
     * @mbggenerated Mon Nov 21 14:38:28 CST 2016
     */
    private String regionId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column C_MERCH_CUST_ACCOUNT_DETAILS.REGINNAME
     *
     * @mbggenerated Mon Nov 21 14:38:28 CST 2016
     */
    private String reginname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column C_MERCH_CUST_ACCOUNT_DETAILS.SALESREP_ID
     *
     * @mbggenerated Mon Nov 21 14:38:28 CST 2016
     */
    private Long salesrepId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column C_MERCH_CUST_ACCOUNT_DETAILS.SALER_NAME
     *
     * @mbggenerated Mon Nov 21 14:38:28 CST 2016
     */
    private String salerName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column C_MERCH_CUST_ACCOUNT_DETAILS.ORGID
     *
     * @mbggenerated Mon Nov 21 14:38:28 CST 2016
     */
    private String orgid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column C_MERCH_CUST_ACCOUNT_DETAILS.ORGNAME
     *
     * @mbggenerated Mon Nov 21 14:38:28 CST 2016
     */
    private String orgname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column C_MERCH_CUST_ACCOUNT_DETAILS.D_AMT
     *
     * @mbggenerated Mon Nov 21 14:38:28 CST 2016
     */
    private Long dAmt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column C_MERCH_CUST_ACCOUNT_DETAILS.C_AMT
     *
     * @mbggenerated Mon Nov 21 14:38:28 CST 2016
     */
    private Long cAmt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column C_MERCH_CUST_ACCOUNT_DETAILS.ACCOUNT_TYPE
     *
     * @mbggenerated Mon Nov 21 14:38:28 CST 2016
     */
    private String accountType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column C_MERCH_CUST_ACCOUNT_DETAILS.ORDER_ID
     *
     * @mbggenerated Mon Nov 21 14:38:28 CST 2016
     */
    private Long orderId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column C_MERCH_CUST_ACCOUNT_DETAILS.SAP_VOUCHER_ID
     *
     * @mbggenerated Mon Nov 21 14:38:28 CST 2016
     */
    private String sapVoucherId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column C_MERCH_CUST_ACCOUNT_DETAILS.PERIOD
     *
     * @mbggenerated Mon Nov 21 14:38:28 CST 2016
     */
    private String period;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column C_MERCH_CUST_ACCOUNT_DETAILS.NAME
     *
     * @return the value of C_MERCH_CUST_ACCOUNT_DETAILS.NAME
     *
     * @mbggenerated Mon Nov 21 14:38:28 CST 2016
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column C_MERCH_CUST_ACCOUNT_DETAILS.NAME
     *
     * @param name the value for C_MERCH_CUST_ACCOUNT_DETAILS.NAME
     *
     * @mbggenerated Mon Nov 21 14:38:28 CST 2016
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column C_MERCH_CUST_ACCOUNT_DETAILS.SAP_CUSTOMER_ID
     *
     * @return the value of C_MERCH_CUST_ACCOUNT_DETAILS.SAP_CUSTOMER_ID
     *
     * @mbggenerated Mon Nov 21 14:38:28 CST 2016
     */
    public String getSapCustomerId() {
        return sapCustomerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column C_MERCH_CUST_ACCOUNT_DETAILS.SAP_CUSTOMER_ID
     *
     * @param sapCustomerId the value for C_MERCH_CUST_ACCOUNT_DETAILS.SAP_CUSTOMER_ID
     *
     * @mbggenerated Mon Nov 21 14:38:28 CST 2016
     */
    public void setSapCustomerId(String sapCustomerId) {
        this.sapCustomerId = sapCustomerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column C_MERCH_CUST_ACCOUNT_DETAILS.CUST_TYPE
     *
     * @return the value of C_MERCH_CUST_ACCOUNT_DETAILS.CUST_TYPE
     *
     * @mbggenerated Mon Nov 21 14:38:28 CST 2016
     */
    public String getCustType() {
        return custType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column C_MERCH_CUST_ACCOUNT_DETAILS.CUST_TYPE
     *
     * @param custType the value for C_MERCH_CUST_ACCOUNT_DETAILS.CUST_TYPE
     *
     * @mbggenerated Mon Nov 21 14:38:28 CST 2016
     */
    public void setCustType(String custType) {
        this.custType = custType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column C_MERCH_CUST_ACCOUNT_DETAILS.TYPE
     *
     * @return the value of C_MERCH_CUST_ACCOUNT_DETAILS.TYPE
     *
     * @mbggenerated Mon Nov 21 14:38:28 CST 2016
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column C_MERCH_CUST_ACCOUNT_DETAILS.TYPE
     *
     * @param type the value for C_MERCH_CUST_ACCOUNT_DETAILS.TYPE
     *
     * @mbggenerated Mon Nov 21 14:38:28 CST 2016
     */
    public void setType(String type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column C_MERCH_CUST_ACCOUNT_DETAILS.STATION_ID
     *
     * @return the value of C_MERCH_CUST_ACCOUNT_DETAILS.STATION_ID
     *
     * @mbggenerated Mon Nov 21 14:38:28 CST 2016
     */
    public Long getStationId() {
        return stationId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column C_MERCH_CUST_ACCOUNT_DETAILS.STATION_ID
     *
     * @param stationId the value for C_MERCH_CUST_ACCOUNT_DETAILS.STATION_ID
     *
     * @mbggenerated Mon Nov 21 14:38:28 CST 2016
     */
    public void setStationId(Long stationId) {
        this.stationId = stationId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column C_MERCH_CUST_ACCOUNT_DETAILS.PORV_ID
     *
     * @return the value of C_MERCH_CUST_ACCOUNT_DETAILS.PORV_ID
     *
     * @mbggenerated Mon Nov 21 14:38:28 CST 2016
     */
    public String getPorvId() {
        return porvId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column C_MERCH_CUST_ACCOUNT_DETAILS.PORV_ID
     *
     * @param porvId the value for C_MERCH_CUST_ACCOUNT_DETAILS.PORV_ID
     *
     * @mbggenerated Mon Nov 21 14:38:28 CST 2016
     */
    public void setPorvId(String porvId) {
        this.porvId = porvId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column C_MERCH_CUST_ACCOUNT_DETAILS.PROVNAME
     *
     * @return the value of C_MERCH_CUST_ACCOUNT_DETAILS.PROVNAME
     *
     * @mbggenerated Mon Nov 21 14:38:28 CST 2016
     */
    public String getProvname() {
        return provname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column C_MERCH_CUST_ACCOUNT_DETAILS.PROVNAME
     *
     * @param provname the value for C_MERCH_CUST_ACCOUNT_DETAILS.PROVNAME
     *
     * @mbggenerated Mon Nov 21 14:38:28 CST 2016
     */
    public void setProvname(String provname) {
        this.provname = provname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column C_MERCH_CUST_ACCOUNT_DETAILS.REGION_ID
     *
     * @return the value of C_MERCH_CUST_ACCOUNT_DETAILS.REGION_ID
     *
     * @mbggenerated Mon Nov 21 14:38:28 CST 2016
     */
    public String getRegionId() {
        return regionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column C_MERCH_CUST_ACCOUNT_DETAILS.REGION_ID
     *
     * @param regionId the value for C_MERCH_CUST_ACCOUNT_DETAILS.REGION_ID
     *
     * @mbggenerated Mon Nov 21 14:38:28 CST 2016
     */
    public void setRegionId(String regionId) {
        this.regionId = regionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column C_MERCH_CUST_ACCOUNT_DETAILS.REGINNAME
     *
     * @return the value of C_MERCH_CUST_ACCOUNT_DETAILS.REGINNAME
     *
     * @mbggenerated Mon Nov 21 14:38:28 CST 2016
     */
    public String getReginname() {
        return reginname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column C_MERCH_CUST_ACCOUNT_DETAILS.REGINNAME
     *
     * @param reginname the value for C_MERCH_CUST_ACCOUNT_DETAILS.REGINNAME
     *
     * @mbggenerated Mon Nov 21 14:38:28 CST 2016
     */
    public void setReginname(String reginname) {
        this.reginname = reginname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column C_MERCH_CUST_ACCOUNT_DETAILS.SALESREP_ID
     *
     * @return the value of C_MERCH_CUST_ACCOUNT_DETAILS.SALESREP_ID
     *
     * @mbggenerated Mon Nov 21 14:38:28 CST 2016
     */
    public Long getSalesrepId() {
        return salesrepId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column C_MERCH_CUST_ACCOUNT_DETAILS.SALESREP_ID
     *
     * @param salesrepId the value for C_MERCH_CUST_ACCOUNT_DETAILS.SALESREP_ID
     *
     * @mbggenerated Mon Nov 21 14:38:28 CST 2016
     */
    public void setSalesrepId(Long salesrepId) {
        this.salesrepId = salesrepId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column C_MERCH_CUST_ACCOUNT_DETAILS.SALER_NAME
     *
     * @return the value of C_MERCH_CUST_ACCOUNT_DETAILS.SALER_NAME
     *
     * @mbggenerated Mon Nov 21 14:38:28 CST 2016
     */
    public String getSalerName() {
        return salerName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column C_MERCH_CUST_ACCOUNT_DETAILS.SALER_NAME
     *
     * @param salerName the value for C_MERCH_CUST_ACCOUNT_DETAILS.SALER_NAME
     *
     * @mbggenerated Mon Nov 21 14:38:28 CST 2016
     */
    public void setSalerName(String salerName) {
        this.salerName = salerName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column C_MERCH_CUST_ACCOUNT_DETAILS.ORGID
     *
     * @return the value of C_MERCH_CUST_ACCOUNT_DETAILS.ORGID
     *
     * @mbggenerated Mon Nov 21 14:38:28 CST 2016
     */
    public String getOrgid() {
        return orgid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column C_MERCH_CUST_ACCOUNT_DETAILS.ORGID
     *
     * @param orgid the value for C_MERCH_CUST_ACCOUNT_DETAILS.ORGID
     *
     * @mbggenerated Mon Nov 21 14:38:28 CST 2016
     */
    public void setOrgid(String orgid) {
        this.orgid = orgid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column C_MERCH_CUST_ACCOUNT_DETAILS.ORGNAME
     *
     * @return the value of C_MERCH_CUST_ACCOUNT_DETAILS.ORGNAME
     *
     * @mbggenerated Mon Nov 21 14:38:28 CST 2016
     */
    public String getOrgname() {
        return orgname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column C_MERCH_CUST_ACCOUNT_DETAILS.ORGNAME
     *
     * @param orgname the value for C_MERCH_CUST_ACCOUNT_DETAILS.ORGNAME
     *
     * @mbggenerated Mon Nov 21 14:38:28 CST 2016
     */
    public void setOrgname(String orgname) {
        this.orgname = orgname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column C_MERCH_CUST_ACCOUNT_DETAILS.D_AMT
     *
     * @return the value of C_MERCH_CUST_ACCOUNT_DETAILS.D_AMT
     *
     * @mbggenerated Mon Nov 21 14:38:28 CST 2016
     */
    public Long getdAmt() {
        return dAmt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column C_MERCH_CUST_ACCOUNT_DETAILS.D_AMT
     *
     * @param dAmt the value for C_MERCH_CUST_ACCOUNT_DETAILS.D_AMT
     *
     * @mbggenerated Mon Nov 21 14:38:28 CST 2016
     */
    public void setdAmt(Long dAmt) {
        this.dAmt = dAmt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column C_MERCH_CUST_ACCOUNT_DETAILS.C_AMT
     *
     * @return the value of C_MERCH_CUST_ACCOUNT_DETAILS.C_AMT
     *
     * @mbggenerated Mon Nov 21 14:38:28 CST 2016
     */
    public Long getcAmt() {
        return cAmt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column C_MERCH_CUST_ACCOUNT_DETAILS.C_AMT
     *
     * @param cAmt the value for C_MERCH_CUST_ACCOUNT_DETAILS.C_AMT
     *
     * @mbggenerated Mon Nov 21 14:38:28 CST 2016
     */
    public void setcAmt(Long cAmt) {
        this.cAmt = cAmt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column C_MERCH_CUST_ACCOUNT_DETAILS.ACCOUNT_TYPE
     *
     * @return the value of C_MERCH_CUST_ACCOUNT_DETAILS.ACCOUNT_TYPE
     *
     * @mbggenerated Mon Nov 21 14:38:28 CST 2016
     */
    public String getAccountType() {
        return accountType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column C_MERCH_CUST_ACCOUNT_DETAILS.ACCOUNT_TYPE
     *
     * @param accountType the value for C_MERCH_CUST_ACCOUNT_DETAILS.ACCOUNT_TYPE
     *
     * @mbggenerated Mon Nov 21 14:38:28 CST 2016
     */
    public void setAccountType(String accountType) {
        this.accountType = accountType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column C_MERCH_CUST_ACCOUNT_DETAILS.ORDER_ID
     *
     * @return the value of C_MERCH_CUST_ACCOUNT_DETAILS.ORDER_ID
     *
     * @mbggenerated Mon Nov 21 14:38:28 CST 2016
     */
    public Long getOrderId() {
        return orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column C_MERCH_CUST_ACCOUNT_DETAILS.ORDER_ID
     *
     * @param orderId the value for C_MERCH_CUST_ACCOUNT_DETAILS.ORDER_ID
     *
     * @mbggenerated Mon Nov 21 14:38:28 CST 2016
     */
    public void setOrderId(Long orderId) {
        this.orderId = orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column C_MERCH_CUST_ACCOUNT_DETAILS.SAP_VOUCHER_ID
     *
     * @return the value of C_MERCH_CUST_ACCOUNT_DETAILS.SAP_VOUCHER_ID
     *
     * @mbggenerated Mon Nov 21 14:38:28 CST 2016
     */
    public String getSapVoucherId() {
        return sapVoucherId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column C_MERCH_CUST_ACCOUNT_DETAILS.SAP_VOUCHER_ID
     *
     * @param sapVoucherId the value for C_MERCH_CUST_ACCOUNT_DETAILS.SAP_VOUCHER_ID
     *
     * @mbggenerated Mon Nov 21 14:38:28 CST 2016
     */
    public void setSapVoucherId(String sapVoucherId) {
        this.sapVoucherId = sapVoucherId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column C_MERCH_CUST_ACCOUNT_DETAILS.PERIOD
     *
     * @return the value of C_MERCH_CUST_ACCOUNT_DETAILS.PERIOD
     *
     * @mbggenerated Mon Nov 21 14:38:28 CST 2016
     */
    public String getPeriod() {
        return period;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column C_MERCH_CUST_ACCOUNT_DETAILS.PERIOD
     *
     * @param period the value for C_MERCH_CUST_ACCOUNT_DETAILS.PERIOD
     *
     * @mbggenerated Mon Nov 21 14:38:28 CST 2016
     */
    public void setPeriod(String period) {
        this.period = period;
    }
}