package com.hhnz.customerInv.model;

import java.math.BigDecimal;
import java.util.Date;

public class CMerchCustProductAdjust {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column C_MERCH_CUST_PRODUCT_ADJUST.ID
     *
     * @mbggenerated Mon Apr 10 13:25:27 CST 2017
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column C_MERCH_CUST_PRODUCT_ADJUST.MERCH_CUST_ID
     *
     * @mbggenerated Mon Apr 10 13:25:27 CST 2017
     */
    private Long merchCustId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column C_MERCH_CUST_PRODUCT_ADJUST.ORGANIZATION_ID
     *
     * @mbggenerated Mon Apr 10 13:25:27 CST 2017
     */
    private String organizationId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column C_MERCH_CUST_PRODUCT_ADJUST.MATERIAL_ID
     *
     * @mbggenerated Mon Apr 10 13:25:27 CST 2017
     */
    private String materialId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column C_MERCH_CUST_PRODUCT_ADJUST.ADJUST_NUM
     *
     * @mbggenerated Mon Apr 10 13:25:27 CST 2017
     */
    private BigDecimal adjustNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column C_MERCH_CUST_PRODUCT_ADJUST.CREATE_TS
     *
     * @mbggenerated Mon Apr 10 13:25:27 CST 2017
     */
    private Date createTs;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column C_MERCH_CUST_PRODUCT_ADJUST.TYPE
     *
     * @mbggenerated Mon Apr 10 13:25:27 CST 2017
     */
    private String type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column C_MERCH_CUST_PRODUCT_ADJUST.CREATE_OID
     *
     * @mbggenerated Mon Apr 10 13:25:27 CST 2017
     */
    private Long createOid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column C_MERCH_CUST_PRODUCT_ADJUST.REMARK
     *
     * @mbggenerated Mon Apr 10 13:25:27 CST 2017
     */
    private String remark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column C_MERCH_CUST_PRODUCT_ADJUST.REASON
     *
     * @mbggenerated Mon Apr 10 13:25:27 CST 2017
     */
    private String reason;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column C_MERCH_CUST_PRODUCT_ADJUST.ATTRIBUTE1
     *
     * @mbggenerated Mon Apr 10 13:25:27 CST 2017
     */
    private String attribute1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column C_MERCH_CUST_PRODUCT_ADJUST.ATTRIBUTE2
     *
     * @mbggenerated Mon Apr 10 13:25:27 CST 2017
     */
    private String attribute2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column C_MERCH_CUST_PRODUCT_ADJUST.ATTRIBUTE3
     *
     * @mbggenerated Mon Apr 10 13:25:27 CST 2017
     */
    private String attribute3;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column C_MERCH_CUST_PRODUCT_ADJUST.ATTRIBUTE4
     *
     * @mbggenerated Mon Apr 10 13:25:27 CST 2017
     */
    private String attribute4;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column C_MERCH_CUST_PRODUCT_ADJUST.ATTRIBUTE5
     *
     * @mbggenerated Mon Apr 10 13:25:27 CST 2017
     */
    private String attribute5;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column C_MERCH_CUST_PRODUCT_ADJUST.STATES
     *
     * @mbggenerated Mon Apr 10 13:25:27 CST 2017
     */
    private String states;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column C_MERCH_CUST_PRODUCT_ADJUST.UPDATE_TS
     *
     * @mbggenerated Mon Apr 10 13:25:27 CST 2017
     */
    private Date updateTs;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column C_MERCH_CUST_PRODUCT_ADJUST.UPDATE_OID
     *
     * @mbggenerated Mon Apr 10 13:25:27 CST 2017
     */
    private Long updateOid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column C_MERCH_CUST_PRODUCT_ADJUST.AUDIT_TS
     *
     * @mbggenerated Mon Apr 10 13:25:27 CST 2017
     */
    private Date auditTs;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column C_MERCH_CUST_PRODUCT_ADJUST.AUDIT_OID
     *
     * @mbggenerated Mon Apr 10 13:25:27 CST 2017
     */
    private Long auditOid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column C_MERCH_CUST_PRODUCT_ADJUST.ADJUST_PRICE
     *
     * @mbggenerated Mon Apr 10 13:25:27 CST 2017
     */
    private BigDecimal adjustPrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column C_MERCH_CUST_PRODUCT_ADJUST.ADJUST_AMT
     *
     * @mbggenerated Mon Apr 10 13:25:27 CST 2017
     */
    private BigDecimal adjustAmt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column C_MERCH_CUST_PRODUCT_ADJUST.OTHER_MERCH_CUST_ID
     *
     * @mbggenerated Mon Apr 10 13:25:27 CST 2017
     */
    private Long otherMerchCustId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column C_MERCH_CUST_PRODUCT_ADJUST.ID
     *
     * @return the value of C_MERCH_CUST_PRODUCT_ADJUST.ID
     *
     * @mbggenerated Mon Apr 10 13:25:27 CST 2017
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column C_MERCH_CUST_PRODUCT_ADJUST.ID
     *
     * @param id the value for C_MERCH_CUST_PRODUCT_ADJUST.ID
     *
     * @mbggenerated Mon Apr 10 13:25:27 CST 2017
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column C_MERCH_CUST_PRODUCT_ADJUST.MERCH_CUST_ID
     *
     * @return the value of C_MERCH_CUST_PRODUCT_ADJUST.MERCH_CUST_ID
     *
     * @mbggenerated Mon Apr 10 13:25:27 CST 2017
     */
    public Long getMerchCustId() {
        return merchCustId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column C_MERCH_CUST_PRODUCT_ADJUST.MERCH_CUST_ID
     *
     * @param merchCustId the value for C_MERCH_CUST_PRODUCT_ADJUST.MERCH_CUST_ID
     *
     * @mbggenerated Mon Apr 10 13:25:27 CST 2017
     */
    public void setMerchCustId(Long merchCustId) {
        this.merchCustId = merchCustId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column C_MERCH_CUST_PRODUCT_ADJUST.ORGANIZATION_ID
     *
     * @return the value of C_MERCH_CUST_PRODUCT_ADJUST.ORGANIZATION_ID
     *
     * @mbggenerated Mon Apr 10 13:25:27 CST 2017
     */
    public String getOrganizationId() {
        return organizationId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column C_MERCH_CUST_PRODUCT_ADJUST.ORGANIZATION_ID
     *
     * @param organizationId the value for C_MERCH_CUST_PRODUCT_ADJUST.ORGANIZATION_ID
     *
     * @mbggenerated Mon Apr 10 13:25:27 CST 2017
     */
    public void setOrganizationId(String organizationId) {
        this.organizationId = organizationId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column C_MERCH_CUST_PRODUCT_ADJUST.MATERIAL_ID
     *
     * @return the value of C_MERCH_CUST_PRODUCT_ADJUST.MATERIAL_ID
     *
     * @mbggenerated Mon Apr 10 13:25:27 CST 2017
     */
    public String getMaterialId() {
        return materialId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column C_MERCH_CUST_PRODUCT_ADJUST.MATERIAL_ID
     *
     * @param materialId the value for C_MERCH_CUST_PRODUCT_ADJUST.MATERIAL_ID
     *
     * @mbggenerated Mon Apr 10 13:25:27 CST 2017
     */
    public void setMaterialId(String materialId) {
        this.materialId = materialId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column C_MERCH_CUST_PRODUCT_ADJUST.ADJUST_NUM
     *
     * @return the value of C_MERCH_CUST_PRODUCT_ADJUST.ADJUST_NUM
     *
     * @mbggenerated Mon Apr 10 13:25:27 CST 2017
     */
    public BigDecimal getAdjustNum() {
        return adjustNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column C_MERCH_CUST_PRODUCT_ADJUST.ADJUST_NUM
     *
     * @param adjustNum the value for C_MERCH_CUST_PRODUCT_ADJUST.ADJUST_NUM
     *
     * @mbggenerated Mon Apr 10 13:25:27 CST 2017
     */
    public void setAdjustNum(BigDecimal adjustNum) {
        this.adjustNum = adjustNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column C_MERCH_CUST_PRODUCT_ADJUST.CREATE_TS
     *
     * @return the value of C_MERCH_CUST_PRODUCT_ADJUST.CREATE_TS
     *
     * @mbggenerated Mon Apr 10 13:25:27 CST 2017
     */
    public Date getCreateTs() {
        return createTs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column C_MERCH_CUST_PRODUCT_ADJUST.CREATE_TS
     *
     * @param createTs the value for C_MERCH_CUST_PRODUCT_ADJUST.CREATE_TS
     *
     * @mbggenerated Mon Apr 10 13:25:27 CST 2017
     */
    public void setCreateTs(Date createTs) {
        this.createTs = createTs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column C_MERCH_CUST_PRODUCT_ADJUST.TYPE
     *
     * @return the value of C_MERCH_CUST_PRODUCT_ADJUST.TYPE
     *
     * @mbggenerated Mon Apr 10 13:25:27 CST 2017
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column C_MERCH_CUST_PRODUCT_ADJUST.TYPE
     *
     * @param type the value for C_MERCH_CUST_PRODUCT_ADJUST.TYPE
     *
     * @mbggenerated Mon Apr 10 13:25:27 CST 2017
     */
    public void setType(String type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column C_MERCH_CUST_PRODUCT_ADJUST.CREATE_OID
     *
     * @return the value of C_MERCH_CUST_PRODUCT_ADJUST.CREATE_OID
     *
     * @mbggenerated Mon Apr 10 13:25:27 CST 2017
     */
    public Long getCreateOid() {
        return createOid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column C_MERCH_CUST_PRODUCT_ADJUST.CREATE_OID
     *
     * @param createOid the value for C_MERCH_CUST_PRODUCT_ADJUST.CREATE_OID
     *
     * @mbggenerated Mon Apr 10 13:25:27 CST 2017
     */
    public void setCreateOid(Long createOid) {
        this.createOid = createOid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column C_MERCH_CUST_PRODUCT_ADJUST.REMARK
     *
     * @return the value of C_MERCH_CUST_PRODUCT_ADJUST.REMARK
     *
     * @mbggenerated Mon Apr 10 13:25:27 CST 2017
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column C_MERCH_CUST_PRODUCT_ADJUST.REMARK
     *
     * @param remark the value for C_MERCH_CUST_PRODUCT_ADJUST.REMARK
     *
     * @mbggenerated Mon Apr 10 13:25:27 CST 2017
     */
    public void setRemark(String remark) {
        this.remark = remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column C_MERCH_CUST_PRODUCT_ADJUST.REASON
     *
     * @return the value of C_MERCH_CUST_PRODUCT_ADJUST.REASON
     *
     * @mbggenerated Mon Apr 10 13:25:27 CST 2017
     */
    public String getReason() {
        return reason;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column C_MERCH_CUST_PRODUCT_ADJUST.REASON
     *
     * @param reason the value for C_MERCH_CUST_PRODUCT_ADJUST.REASON
     *
     * @mbggenerated Mon Apr 10 13:25:27 CST 2017
     */
    public void setReason(String reason) {
        this.reason = reason;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column C_MERCH_CUST_PRODUCT_ADJUST.ATTRIBUTE1
     *
     * @return the value of C_MERCH_CUST_PRODUCT_ADJUST.ATTRIBUTE1
     *
     * @mbggenerated Mon Apr 10 13:25:27 CST 2017
     */
    public String getAttribute1() {
        return attribute1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column C_MERCH_CUST_PRODUCT_ADJUST.ATTRIBUTE1
     *
     * @param attribute1 the value for C_MERCH_CUST_PRODUCT_ADJUST.ATTRIBUTE1
     *
     * @mbggenerated Mon Apr 10 13:25:27 CST 2017
     */
    public void setAttribute1(String attribute1) {
        this.attribute1 = attribute1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column C_MERCH_CUST_PRODUCT_ADJUST.ATTRIBUTE2
     *
     * @return the value of C_MERCH_CUST_PRODUCT_ADJUST.ATTRIBUTE2
     *
     * @mbggenerated Mon Apr 10 13:25:27 CST 2017
     */
    public String getAttribute2() {
        return attribute2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column C_MERCH_CUST_PRODUCT_ADJUST.ATTRIBUTE2
     *
     * @param attribute2 the value for C_MERCH_CUST_PRODUCT_ADJUST.ATTRIBUTE2
     *
     * @mbggenerated Mon Apr 10 13:25:27 CST 2017
     */
    public void setAttribute2(String attribute2) {
        this.attribute2 = attribute2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column C_MERCH_CUST_PRODUCT_ADJUST.ATTRIBUTE3
     *
     * @return the value of C_MERCH_CUST_PRODUCT_ADJUST.ATTRIBUTE3
     *
     * @mbggenerated Mon Apr 10 13:25:27 CST 2017
     */
    public String getAttribute3() {
        return attribute3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column C_MERCH_CUST_PRODUCT_ADJUST.ATTRIBUTE3
     *
     * @param attribute3 the value for C_MERCH_CUST_PRODUCT_ADJUST.ATTRIBUTE3
     *
     * @mbggenerated Mon Apr 10 13:25:27 CST 2017
     */
    public void setAttribute3(String attribute3) {
        this.attribute3 = attribute3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column C_MERCH_CUST_PRODUCT_ADJUST.ATTRIBUTE4
     *
     * @return the value of C_MERCH_CUST_PRODUCT_ADJUST.ATTRIBUTE4
     *
     * @mbggenerated Mon Apr 10 13:25:27 CST 2017
     */
    public String getAttribute4() {
        return attribute4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column C_MERCH_CUST_PRODUCT_ADJUST.ATTRIBUTE4
     *
     * @param attribute4 the value for C_MERCH_CUST_PRODUCT_ADJUST.ATTRIBUTE4
     *
     * @mbggenerated Mon Apr 10 13:25:27 CST 2017
     */
    public void setAttribute4(String attribute4) {
        this.attribute4 = attribute4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column C_MERCH_CUST_PRODUCT_ADJUST.ATTRIBUTE5
     *
     * @return the value of C_MERCH_CUST_PRODUCT_ADJUST.ATTRIBUTE5
     *
     * @mbggenerated Mon Apr 10 13:25:27 CST 2017
     */
    public String getAttribute5() {
        return attribute5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column C_MERCH_CUST_PRODUCT_ADJUST.ATTRIBUTE5
     *
     * @param attribute5 the value for C_MERCH_CUST_PRODUCT_ADJUST.ATTRIBUTE5
     *
     * @mbggenerated Mon Apr 10 13:25:27 CST 2017
     */
    public void setAttribute5(String attribute5) {
        this.attribute5 = attribute5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column C_MERCH_CUST_PRODUCT_ADJUST.STATES
     *
     * @return the value of C_MERCH_CUST_PRODUCT_ADJUST.STATES
     *
     * @mbggenerated Mon Apr 10 13:25:27 CST 2017
     */
    public String getStates() {
        return states;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column C_MERCH_CUST_PRODUCT_ADJUST.STATES
     *
     * @param states the value for C_MERCH_CUST_PRODUCT_ADJUST.STATES
     *
     * @mbggenerated Mon Apr 10 13:25:27 CST 2017
     */
    public void setStates(String states) {
        this.states = states;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column C_MERCH_CUST_PRODUCT_ADJUST.UPDATE_TS
     *
     * @return the value of C_MERCH_CUST_PRODUCT_ADJUST.UPDATE_TS
     *
     * @mbggenerated Mon Apr 10 13:25:27 CST 2017
     */
    public Date getUpdateTs() {
        return updateTs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column C_MERCH_CUST_PRODUCT_ADJUST.UPDATE_TS
     *
     * @param updateTs the value for C_MERCH_CUST_PRODUCT_ADJUST.UPDATE_TS
     *
     * @mbggenerated Mon Apr 10 13:25:27 CST 2017
     */
    public void setUpdateTs(Date updateTs) {
        this.updateTs = updateTs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column C_MERCH_CUST_PRODUCT_ADJUST.UPDATE_OID
     *
     * @return the value of C_MERCH_CUST_PRODUCT_ADJUST.UPDATE_OID
     *
     * @mbggenerated Mon Apr 10 13:25:27 CST 2017
     */
    public Long getUpdateOid() {
        return updateOid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column C_MERCH_CUST_PRODUCT_ADJUST.UPDATE_OID
     *
     * @param updateOid the value for C_MERCH_CUST_PRODUCT_ADJUST.UPDATE_OID
     *
     * @mbggenerated Mon Apr 10 13:25:27 CST 2017
     */
    public void setUpdateOid(Long updateOid) {
        this.updateOid = updateOid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column C_MERCH_CUST_PRODUCT_ADJUST.AUDIT_TS
     *
     * @return the value of C_MERCH_CUST_PRODUCT_ADJUST.AUDIT_TS
     *
     * @mbggenerated Mon Apr 10 13:25:27 CST 2017
     */
    public Date getAuditTs() {
        return auditTs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column C_MERCH_CUST_PRODUCT_ADJUST.AUDIT_TS
     *
     * @param auditTs the value for C_MERCH_CUST_PRODUCT_ADJUST.AUDIT_TS
     *
     * @mbggenerated Mon Apr 10 13:25:27 CST 2017
     */
    public void setAuditTs(Date auditTs) {
        this.auditTs = auditTs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column C_MERCH_CUST_PRODUCT_ADJUST.AUDIT_OID
     *
     * @return the value of C_MERCH_CUST_PRODUCT_ADJUST.AUDIT_OID
     *
     * @mbggenerated Mon Apr 10 13:25:27 CST 2017
     */
    public Long getAuditOid() {
        return auditOid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column C_MERCH_CUST_PRODUCT_ADJUST.AUDIT_OID
     *
     * @param auditOid the value for C_MERCH_CUST_PRODUCT_ADJUST.AUDIT_OID
     *
     * @mbggenerated Mon Apr 10 13:25:27 CST 2017
     */
    public void setAuditOid(Long auditOid) {
        this.auditOid = auditOid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column C_MERCH_CUST_PRODUCT_ADJUST.ADJUST_PRICE
     *
     * @return the value of C_MERCH_CUST_PRODUCT_ADJUST.ADJUST_PRICE
     *
     * @mbggenerated Mon Apr 10 13:25:27 CST 2017
     */
    public BigDecimal getAdjustPrice() {
        return adjustPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column C_MERCH_CUST_PRODUCT_ADJUST.ADJUST_PRICE
     *
     * @param adjustPrice the value for C_MERCH_CUST_PRODUCT_ADJUST.ADJUST_PRICE
     *
     * @mbggenerated Mon Apr 10 13:25:27 CST 2017
     */
    public void setAdjustPrice(BigDecimal adjustPrice) {
        this.adjustPrice = adjustPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column C_MERCH_CUST_PRODUCT_ADJUST.ADJUST_AMT
     *
     * @return the value of C_MERCH_CUST_PRODUCT_ADJUST.ADJUST_AMT
     *
     * @mbggenerated Mon Apr 10 13:25:27 CST 2017
     */
    public BigDecimal getAdjustAmt() {
        return adjustAmt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column C_MERCH_CUST_PRODUCT_ADJUST.ADJUST_AMT
     *
     * @param adjustAmt the value for C_MERCH_CUST_PRODUCT_ADJUST.ADJUST_AMT
     *
     * @mbggenerated Mon Apr 10 13:25:27 CST 2017
     */
    public void setAdjustAmt(BigDecimal adjustAmt) {
        this.adjustAmt = adjustAmt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column C_MERCH_CUST_PRODUCT_ADJUST.OTHER_MERCH_CUST_ID
     *
     * @return the value of C_MERCH_CUST_PRODUCT_ADJUST.OTHER_MERCH_CUST_ID
     *
     * @mbggenerated Mon Apr 10 13:25:27 CST 2017
     */
    public Long getOtherMerchCustId() {
        return otherMerchCustId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column C_MERCH_CUST_PRODUCT_ADJUST.OTHER_MERCH_CUST_ID
     *
     * @param otherMerchCustId the value for C_MERCH_CUST_PRODUCT_ADJUST.OTHER_MERCH_CUST_ID
     *
     * @mbggenerated Mon Apr 10 13:25:27 CST 2017
     */
    public void setOtherMerchCustId(Long otherMerchCustId) {
        this.otherMerchCustId = otherMerchCustId;
    }
}