package com.hhnz.combination.mapper;

import com.hhnz.combination.model.CrmMaterialPackageHeader;
import com.hhnz.combination.model.CrmMaterialPackageHeaderExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CrmMaterialPackageHeaderMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CRM_MATERIAL_PACKAGE_HEADER
     *
     * @mbggenerated Tue Dec 20 17:23:22 CST 2016
     */
    int countByExample(CrmMaterialPackageHeaderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CRM_MATERIAL_PACKAGE_HEADER
     *
     * @mbggenerated Tue Dec 20 17:23:22 CST 2016
     */
    int deleteByExample(CrmMaterialPackageHeaderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CRM_MATERIAL_PACKAGE_HEADER
     *
     * @mbggenerated Tue Dec 20 17:23:22 CST 2016
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CRM_MATERIAL_PACKAGE_HEADER
     *
     * @mbggenerated Tue Dec 20 17:23:22 CST 2016
     */
    int insert(CrmMaterialPackageHeader record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CRM_MATERIAL_PACKAGE_HEADER
     *
     * @mbggenerated Tue Dec 20 17:23:22 CST 2016
     */
    int insertSelective(CrmMaterialPackageHeader record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CRM_MATERIAL_PACKAGE_HEADER
     *
     * @mbggenerated Tue Dec 20 17:23:22 CST 2016
     */
    List<CrmMaterialPackageHeader> selectByExample(CrmMaterialPackageHeaderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CRM_MATERIAL_PACKAGE_HEADER
     *
     * @mbggenerated Tue Dec 20 17:23:22 CST 2016
     */
    CrmMaterialPackageHeader selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CRM_MATERIAL_PACKAGE_HEADER
     *
     * @mbggenerated Tue Dec 20 17:23:22 CST 2016
     */
    int updateByExampleSelective(@Param("record") CrmMaterialPackageHeader record, @Param("example") CrmMaterialPackageHeaderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CRM_MATERIAL_PACKAGE_HEADER
     *
     * @mbggenerated Tue Dec 20 17:23:22 CST 2016
     */
    int updateByExample(@Param("record") CrmMaterialPackageHeader record, @Param("example") CrmMaterialPackageHeaderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CRM_MATERIAL_PACKAGE_HEADER
     *
     * @mbggenerated Tue Dec 20 17:23:22 CST 2016
     */
    int updateByPrimaryKeySelective(CrmMaterialPackageHeader record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CRM_MATERIAL_PACKAGE_HEADER
     *
     * @mbggenerated Tue Dec 20 17:23:22 CST 2016
     */
    int updateByPrimaryKey(CrmMaterialPackageHeader record);
}