package com.hhnz.combination.mapper;

import com.hhnz.combination.model.CrmMaterialPackageApply;
import com.hhnz.combination.model.CrmMaterialPackageApplyExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CrmMaterialPackageApplyMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CRM_MATERIAL_PACKAGE_APPLY
     *
     * @mbggenerated Thu Dec 22 14:14:08 CST 2016
     */
    int countByExample(CrmMaterialPackageApplyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CRM_MATERIAL_PACKAGE_APPLY
     *
     * @mbggenerated Thu Dec 22 14:14:08 CST 2016
     */
    int deleteByExample(CrmMaterialPackageApplyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CRM_MATERIAL_PACKAGE_APPLY
     *
     * @mbggenerated Thu Dec 22 14:14:08 CST 2016
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CRM_MATERIAL_PACKAGE_APPLY
     *
     * @mbggenerated Thu Dec 22 14:14:08 CST 2016
     */
    int insert(CrmMaterialPackageApply record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CRM_MATERIAL_PACKAGE_APPLY
     *
     * @mbggenerated Thu Dec 22 14:14:08 CST 2016
     */
    int insertSelective(CrmMaterialPackageApply record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CRM_MATERIAL_PACKAGE_APPLY
     *
     * @mbggenerated Thu Dec 22 14:14:08 CST 2016
     */
    List<CrmMaterialPackageApply> selectByExample(CrmMaterialPackageApplyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CRM_MATERIAL_PACKAGE_APPLY
     *
     * @mbggenerated Thu Dec 22 14:14:08 CST 2016
     */
    CrmMaterialPackageApply selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CRM_MATERIAL_PACKAGE_APPLY
     *
     * @mbggenerated Thu Dec 22 14:14:08 CST 2016
     */
    int updateByExampleSelective(@Param("record") CrmMaterialPackageApply record, @Param("example") CrmMaterialPackageApplyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CRM_MATERIAL_PACKAGE_APPLY
     *
     * @mbggenerated Thu Dec 22 14:14:08 CST 2016
     */
    int updateByExample(@Param("record") CrmMaterialPackageApply record, @Param("example") CrmMaterialPackageApplyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CRM_MATERIAL_PACKAGE_APPLY
     *
     * @mbggenerated Thu Dec 22 14:14:08 CST 2016
     */
    int updateByPrimaryKeySelective(CrmMaterialPackageApply record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CRM_MATERIAL_PACKAGE_APPLY
     *
     * @mbggenerated Thu Dec 22 14:14:08 CST 2016
     */
    int updateByPrimaryKey(CrmMaterialPackageApply record);
}