-- 客户付款方关联表
DROP TABLE C_MERCH_PAYER;
CREATE TABLE C_MERCH_PAYER (
MERCHID NUMBER(14) NOT NULL ,
PAYER NUMBER(14) NOT NULL 
);

ALTER TABLE C_MERCH_PAYER ADD CHECK (MERCHID IS NOT NULL);
ALTER TABLE C_MERCH_PAYER ADD CHECK (PAYER IS NOT NULL);

ALTER TABLE C_MERCH_PAYER ADD PRIMARY KEY (MERCHID, PAYER);

comment on column C_MERCH_PAYER.MERCHID
  is '客户id';
comment on column C_MERCH_PAYER.PAYER
  is '付款方客户id';
commit;
